Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 2
	farbank "Cries"
	fardw Cry_CRika
	fardw Cry_CKongara
	fardw Cry_DLuize
	fardw Cry_SRemilia
	fardw Cry_CMarisa
	fardw Cry_EYuki
	fardw Cry_DDaichan
	fardw Cry_CYumeko
	fardw Cry_EKotohime
	fardw Cry_CSariel
	fardw Cry_EKongara
	fardw Cry_CChiyuri
	fardw Cry_CYuki
	fardw Cry_Rumia
	fardw Cry_EMagan
	fardw Cry_CReimu
	fardw Cry_Farfetch_d
	fardw Cry_TPatchouli
	fardw Cry_ESara
	fardw Cry_HSakuya
	fardw Cry_CMima
	fardw Cry_OGyoku
	fardw Cry_CGyoku
	fardw Cry_CKikuri
	fardw Cry_Yumeko
	fardw Cry_CMeira
	fardw Cry_Rikako
	fardw Cry_CLyrica
	fardw Cry_MGyoku
	fardw Cry_CSakuya
	fardw Cry_EKana
	fardw Cry_EOrange
	fardw Cry_CDaichan
	fardw Cry_Yumemi
	fardw Cry_EMima
	fardw Cry_Kana
	fardw Cry_EMeira
	fardw Cry_EMugetsu
	fardw Cry_Aya
	fardw Cry_CKeine
	fardw Cry_TEirin
	fardw Cry_CNitori
	fardw Cry_SKoishi
	fardw Cry_CMokou
	fardw Cry_CKaguya
	fardw Cry_SWriggle
	fardw Cry_Sentret
	fardw Cry_HMinoriko
	fardw Cry_CReisen
	fardw Cry_CYoumu
	fardw Cry_CSanae
	fardw Cry_Momiji
	fardw Cry_CAya
	fardw Cry_Tenshi
	fardw Cry_Mystia
	fardw Cry_CNazrin
	fardw Cry_CShizuha
	fardw Cry_CParsee
	fardw Cry_TReisen
	fardw Cry_Kaguya
	fardw Cry_AIku
	fardw Cry_CYamame
	fardw Cry_AMokou
	fardw Cry_STenshi
	fardw Cry_TTei
	fardw Cry_Rin
	fardw Cry_CMomiji
	fardw Cry_CSatori
	assert_table_length NUM_CRIES
