Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 2, Cries
	farbank "Cries"
	fardw Cry_CRika
	fardw Cry_CKongara
	fardw Cry_ELuize
	fardw Cry_Kangaskhan
	fardw Cry_CMarisa
	fardw Cry_EYuki
	fardw Cry_EDaichan
	fardw Cry_CYumeko
	fardw Cry_EKotohime
	fardw Cry_CSariel
	fardw Cry_EKongara
	fardw Cry_CChiyuri
	fardw Cry_CYuki
	fardw Cry_Rumia
	fardw Cry_EMagan
	fardw Cry_CReimu
	fardw Cry_Farfetch_d
	fardw Cry_Rhydon
	fardw Cry_ESara
	fardw Cry_ESakuya
	fardw Cry_CMima
	fardw Cry_OGyoku
	fardw Cry_CGyoku
	fardw Cry_CKikuri
	fardw Cry_Yumeko
	fardw Cry_CMeira
	fardw Cry_Rikako
	fardw Cry_Lapras
	fardw Cry_MGyoku
	fardw Cry_CSakuya
	fardw Cry_EKana
	fardw Cry_EOrange
	fardw Cry_CDaichan
	fardw Cry_Yumemi
	fardw Cry_EMima
	fardw Cry_Kana
	fardw Cry_EMeira
	fardw Cry_EMugetsu
	fardw Cry_Marill
	fardw Cry_Spinarak
	fardw Cry_Togepi
	fardw Cry_Girafarig
	fardw Cry_Raikou
	fardw Cry_Mareep
	fardw Cry_Togetic
	fardw Cry_Hoothoot
	fardw Cry_Sentret
	fardw Cry_Slowking
	fardw Cry_CReisen
	fardw Cry_CYoumu
	fardw Cry_CSanae
	fardw Cry_Gligar
	fardw Cry_Bellossom
	fardw Cry_Slugma
	fardw Cry_Ledyba
	fardw Cry_Entei
	fardw Cry_Wooper
	fardw Cry_Mantine
	fardw Cry_EReisen
	fardw Cry_Natu
	fardw Cry_Teddiursa
	fardw Cry_Remoraid
	fardw Cry_Ampharos
	fardw Cry_Magcargo
	fardw Cry_Pichu
	fardw Cry_Tyrogue
	fardw Cry_Dunsparce
	fardw Cry_Donphan
	assert_table_length NUM_CRIES
