AnimationPointers:
	table_width 2
	dw CReimuAnimation
	dw ReimuAnimation
	dw TReimuAnimation
	dw CMarisaAnimation
	dw MarisaAnimation
	dw AMarisaAnimation
	dw CSakuyaAnimation
	dw SakuyaAnimation
	dw HSakuyaAnimation
	dw CGyokuAnimation
	dw MGyokuAnimation
	dw FGyokuAnimation
	dw OGyokuAnimation
	dw CMaganAnimation
	dw MaganAnimation
	dw CMimaAnimation
	dw MimaAnimation
	dw CElisAnimation
	dw ElisAnimation
	dw CKikuriAnimation
	dw KikuriJohtoAnimation
	dw CSarielAnimation
	dw SarielAnimation
	dw CKongaraAnimation
	dw KongaraAnimation
	dw CRikaAnimation
	dw RikaAnimation
	dw ARikaAnimation
	dw CMeiraAnimation
	dw MeiraAnimation
	dw CEllenAnimation
	dw EllenAnimation
	dw CKotohimeAnimation
	dw KotohimeAnimation
	dw CKanaAnimation
	dw KanaAnimation
	dw CRikakoAnimation
	dw RikakoAnimation
	dw CChiyuriAnimation
	dw ChiyuriAnimation
	dw CYumemiAnimation
	dw YumemiAnimation
	dw COrangeAnimation
	dw OrangeAnimation
	dw CKurumiAnimation
	dw KurumiAnimation
	dw CEllyAnimation
	dw EllyAnimation
	dw CYukaAnimation
	dw YukaAnimation
	dw AYukaAnimation
	dw CMugetsuAnimation
	dw MugetsuAnimation
	dw CGengetsuAnimation
	dw GengetsuAnimation
	dw CSaraAnimation
	dw SaraAnimation
	dw CLuizeAnimation
	dw LuizeAnimation
	dw DLuizeAnimation
	dw CAliceAnimation
	dw AliceAnimation
	dw AAliceAnimation
	dw CMaiAnimation
	dw MaiAnimation
	dw CYukiAnimation
	dw YukiAnimation
	dw CYumekoAnimation
	dw YumekoAnimation
	dw CShinkiAnimation
	dw ShinkiAnimation
	dw CRumiaAnimation
	dw RumiaAnimation
	dw ARumiaAnimation
	dw CDaichanAnimation
	dw DaichanAnimation
	dw DDaichanAnimation
	dw CCirnoAnimation
	dw CirnoAnimation
	dw SCirnoAnimation
	dw CMeilingAnimation
	dw MeilingAnimation
	dw AMeilingAnimation
	dw CKoakumaAnimation
	dw KoakumaAnimation
	dw HKoakumaAnimation
	dw CPatchouliAnimation
	dw PatchouliAnimation
	dw TPatchouliAnimation
	dw CRemiliaAnimation
	dw RemiliaAnimation
	dw SRemiliaAnimation
	dw CFlandreAnimation
	dw FlandreAnimation
	dw AFlandreAnimation
	dw CLettyAnimation
	dw LettyAnimation
	dw DLettyAnimation
	dw CChenAnimation
	dw ChenAnimation
	dw HChenAnimation
	dw CLilyWhiteAnimation
	dw LilyWhiteAnimation
	dw DLilyWhiteAnimation
	dw CLilyBlackAnimation
	dw LilyBlackAnimation
	dw SLilyBlackAnimation
	dw CLyricaAnimation
	dw LyricaAnimation
	dw TLyricaAnimation
	dw CMerlinAnimation
	dw MerlinAnimation
	dw SMerlinAnimation
	dw CLunasaAnimation
	dw LunasaAnimation
	dw ALunasaAnimation
	dw CYuyukoAnimation
	dw YuyukoAnimation
	dw AYuyukoAnimation
	dw CRanAnimation
	dw RanAnimation
	dw TRanAnimation
	dw CYukariAnimation
	dw YukariAnimation
	dw TYukariAnimation
	dw CSuikaAnimation
	dw SuikaAnimation
	dw TSuikaAnimation
	dw CYoumuAnimation
	dw YoumuAnimation
	dw SYoumuAnimation
	dw CReisenAnimation
	dw ReisenAnimation
	dw TReisenAnimation
	dw CSanaeAnimation
	dw SanaeAnimation
	dw DSanaeAnimation
	dw CWriggleAnimation
	dw WriggleAnimation
	dw SWriggleAnimation
	dw CMystiaAnimation
	dw MystiaAnimation
	dw TMystiaAnimation
	dw CKeineAnimation
	dw KeineAnimation
	dw AKeineAnimation
	dw CTeiAnimation
	dw TeiAnimation
	dw TTeiAnimation
	dw CEirinAnimation
	dw EirinAnimation
	dw TEirinAnimation
	dw CKaguyaAnimation
	dw KaguyaAnimation
	dw TKaguyaAnimation
	dw CMokouAnimation
	dw MokouAnimation
	dw AMokouAnimation
	dw CAyaAnimation
	dw AyaAnimation
	dw SAyaAnimation
	dw CMedicineAnimation
	dw MedicineAnimation
	dw AMedicineAnimation
	dw CKomachiAnimation
	dw KomachiAnimation
	dw AKomachiAnimation
	dw CEikiAnimation
	dw EikiAnimation
	dw AEikiAnimation
	dw CShizuhaAnimation
	dw ShizuhaAnimation
	dw SShizuhaAnimation
	dw CMinorikoAnimation
	dw MinorikoAnimation
	dw HMinorikoAnimation
	dw CHinaAnimation
	dw HinaAAnimation
	dw AHinaAnimation
	dw CNitoriAnimation
	dw NitoriAnimation
	dw ANitoriAnimation
	dw CMomijiAnimation
	dw MomijiAnimation
	dw CKanakoAnimation
	dw KanakoAnimation
	dw AKanakoAnimation
	dw CSuwakoAnimation
	dw SuwakoAnimation
	dw DSuwakoAnimation
	dw CIkuAnimation
	dw IkuAnimation
	dw AIkuAnimation
	dw CTenshiAnimation
	dw TenshiAnimation
	dw STenshiAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw CLunasa2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw AzurillAnimation
	dw WynautAnimation
	dw AmbipomAnimation
	dw EggAnimation
	dw EggAnimation
	dw MismagiusAnimation
	dw HonchkrowAnimation
	dw BonslyAnimation
	dw MimeJrAnimation
	dw HappinyAnimation
	dw MunchlaxAnimation
	dw MantykeAnimation
	dw WeavileAnimation
	dw MagnezoneAnimation
	dw LickilickyAnimation
	dw RhyperiorAnimation
	dw TangrowthAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw TogekissAnimation
	dw YanmegaAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw AMomijiAnimation
	dw MamoswineAnimation
	dw CLunasaZAnimation
	dw SylveonAnimation
	dw PerrserkerAnimation
	dw CursolaAnimation
	dw SirfetchDAnimation
	dw MrRimeAnimation
	dw WyrdeerAnimation
	dw KleavorAnimation
	dw UrsalunaAnimation
	dw SneaslerAnimation
	dw OverqwilAnimation
	dw PlacethmTwoSegmentAnimation
	dw FarigirafAnimation
	dw ClodsireAnimation
	dw AnnihilapeAnimation
	assert_table_length NUM_SPECIES

	dw HinaBAnimation
	dw HinaCAnimation
	dw HinaDAnimation
	dw HinaEAnimation
	dw HinaFAnimation
	dw HinaGAnimation
	dw HinaHAnimation
	dw HinaIAnimation
	dw HinaJAnimation
	dw HinaKAnimation
	dw HinaLAnimation
	dw HinaMAnimation
	dw HinaNAnimation
	dw HinaOAnimation
	dw HinaPAnimation
	dw HinaQAnimation
	dw HinaRAnimation
	dw HinaSAnimation
	dw HinaTAnimation
	dw HinaUAnimation
	dw HinaVAnimation
	dw HinaWAnimation
	dw HinaXAnimation
	dw HinaYAnimation
	dw HinaZAnimation
	dw HinaExclamationAnimation
	dw HinaQuestionAnimation

	dw KikuriKantoAnimation
	dw KikuriKogaAnimation
	dw KikuriAgathaAnimation
	dw KikuriArianaAnimation

	dw TTeiSpikyAnimation

	dw LilyBlackSkellyAnimation
	dw LilyBlackCalico1Animation
	dw LilyBlackCalico2Animation
	dw LilyBlackCalico3Animation
	dw LilyBlackTwoToneAnimation
	dw LilyBlackOrcaAnimation
	dw LilyBlackDapplesAnimation
	dw LilyBlackTigerAnimation
	dw LilyBlackZebraAnimation
	dw LilyBlackStripeAnimation
	dw LilyBlackBubblesAnimation
	dw LilyBlackDiamondsAnimation
	dw LilyBlackPatchesAnimation
	dw LilyBlackForehead1Animation
	dw LilyBlackMask1Animation
	dw LilyBlackForehead2Animation
	dw LilyBlackMask2Animation
	dw LilyBlackSaucyAnimation
	dw LilyBlackRaindropAnimation

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedAnimation

	dw SuikaArmoredAnimation

	dw PlacethmThreeSegmentAnimation

	assert_table_length NUM_UNIQUE_TOHOMON
