BitmasksPointers:
	table_width 2
	dw CReimuBitmasks
	dw ReimuBitmasks
	dw TReimuBitmasks
	dw CMarisaBitmasks
	dw MarisaBitmasks
	dw AMarisaBitmasks
	dw CSakuyaBitmasks
	dw SakuyaBitmasks
	dw HSakuyaBitmasks
	dw CGyokuBitmasks
	dw MGyokuBitmasks
	dw FGyokuBitmasks
	dw OGyokuBitmasks
	dw CMaganBitmasks
	dw MaganBitmasks
	dw CMimaBitmasks
	dw MimaBitmasks
	dw CElisBitmasks
	dw ElisBitmasks
	dw CKikuriBitmasks
	dw KikuriJohtoBitmasks
	dw CSarielBitmasks
	dw SarielBitmasks
	dw CKongaraBitmasks
	dw KongaraBitmasks
	dw CRikaBitmasks
	dw RikaBitmasks
	dw ARikaBitmasks
	dw CMeiraBitmasks
	dw MeiraBitmasks
	dw CEllenBitmasks
	dw EllenBitmasks
	dw CKotohimeBitmasks
	dw KotohimeBitmasks
	dw CKanaBitmasks
	dw KanaBitmasks
	dw CRikakoBitmasks
	dw RikakoBitmasks
	dw CChiyuriBitmasks
	dw ChiyuriBitmasks
	dw CYumemiBitmasks
	dw YumemiBitmasks
	dw COrangeBitmasks
	dw OrangeBitmasks
	dw CKurumiBitmasks
	dw KurumiBitmasks
	dw CEllyBitmasks
	dw EllyBitmasks
	dw CYukaBitmasks
	dw YukaBitmasks
	dw AYukaBitmasks
	dw CMugetsuBitmasks
	dw MugetsuBitmasks
	dw CGengetsuBitmasks
	dw GengetsuBitmasks
	dw CSaraBitmasks
	dw SaraBitmasks
	dw CLuizeBitmasks
	dw LuizeBitmasks
	dw DLuizeBitmasks
	dw CAliceBitmasks
	dw AliceBitmasks
	dw AAliceBitmasks
	dw CMaiBitmasks
	dw MaiBitmasks
	dw CYukiBitmasks
	dw YukiBitmasks
	dw CYumekoBitmasks
	dw YumekoBitmasks
	dw CShinkiBitmasks
	dw ShinkiBitmasks
	dw CRumiaBitmasks
	dw RumiaBitmasks
	dw ARumiaBitmasks
	dw CDaichanBitmasks
	dw DaichanBitmasks
	dw DDaichanBitmasks
	dw CCirnoBitmasks
	dw CirnoBitmasks
	dw SCirnoBitmasks
	dw CMeilingBitmasks
	dw MeilingBitmasks
	dw AMeilingBitmasks
	dw CKoakumaBitmasks
	dw KoakumaBitmasks
	dw HKoakumaBitmasks
	dw CPatchouliBitmasks
	dw PatchouliBitmasks
	dw TPatchouliBitmasks
	dw CRemiliaBitmasks
	dw RemiliaBitmasks
	dw SRemiliaBitmasks
	dw CFlandreBitmasks
	dw FlandreBitmasks
	dw AFlandreBitmasks
	dw CLettyBitmasks
	dw LettyBitmasks
	dw DLettyBitmasks
	dw CChenBitmasks
	dw ChenBitmasks
	dw HChenBitmasks
	dw CLilyWhiteBitmasks
	dw LilyWhiteBitmasks
	dw DLilyWhiteBitmasks
	dw CLilyBlackBitmasks
	dw LilyBlackBitmasks
	dw SLilyBlackBitmasks
	dw CLyricaBitmasks
	dw LyricaBitmasks
	dw TLyricaBitmasks
	dw CMerlinBitmasks
	dw MerlinBitmasks
	dw SMerlinBitmasks
	dw CLunasaBitmasks
	dw LunasaBitmasks
	dw ALunasaBitmasks
	dw CYuyukoBitmasks
	dw YuyukoBitmasks
	dw AYuyukoBitmasks
	dw CRanBitmasks
	dw RanBitmasks
	dw TRanBitmasks
	dw CYukariBitmasks
	dw YukariBitmasks
	dw TYukariBitmasks
	dw CSuikaBitmasks
	dw SuikaBitmasks
	dw TSuikaBitmasks
	dw CYoumuBitmasks
	dw YoumuBitmasks
	dw SYoumuBitmasks
	dw CReisenBitmasks
	dw ReisenBitmasks
	dw TReisenBitmasks
	dw CSanaeBitmasks
	dw SanaeBitmasks
	dw DSanaeBitmasks
	dw CWriggleBitmasks
	dw WriggleBitmasks
	dw SWriggleBitmasks
	dw CMystiaBitmasks
	dw MystiaBitmasks
	dw TMystiaBitmasks
	dw CKeineBitmasks
	dw KeineBitmasks
	dw AKeineBitmasks
	dw CTeiBitmasks
	dw TeiBitmasks
	dw TTeiBitmasks
	dw CEirinBitmasks
	dw EirinBitmasks
	dw TEirinBitmasks
	dw CKaguyaBitmasks
	dw KaguyaBitmasks
	dw TKaguyaBitmasks
	dw CMokouBitmasks
	dw MokouBitmasks
	dw AMokouBitmasks
	dw CAyaBitmasks
	dw AyaBitmasks
	dw SAyaBitmasks
	dw CMedicineBitmasks
	dw MedicineBitmasks
	dw AMedicineBitmasks
	dw CKomachiBitmasks
	dw KomachiBitmasks
	dw AKomachiBitmasks
	dw CEikiBitmasks
	dw EikiBitmasks
	dw AEikiBitmasks
	dw CShizuhaBitmasks
	dw ShizuhaBitmasks
	dw SShizuhaBitmasks
	dw CMinorikoBitmasks
	dw MinorikoBitmasks
	dw HMinorikoBitmasks
	dw CHinaBitmasks
	dw HinaABitmasks
	dw AHinaBitmasks
	dw CNitoriBitmasks
	dw NitoriBitmasks
	dw ANitoriBitmasks
	dw CMomijiBitmasks
	dw MomijiBitmasks
	dw CKanakoBitmasks
	dw KanakoBitmasks
	dw AKanakoBitmasks
	dw CSuwakoBitmasks
	dw SuwakoBitmasks
	dw DSuwakoBitmasks
	dw CIkuBitmasks
	dw IkuBitmasks
	dw AIkuBitmasks
	dw CTenshiBitmasks
	dw TenshiBitmasks
	dw STenshiBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw CLunasa2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw AzurillBitmasks
	dw WynautBitmasks
	dw AmbipomBitmasks
	dw EggBitmasks
	dw EggBitmasks ; $100
	dw MismagiusBitmasks
	dw HonchkrowBitmasks
	dw BonslyBitmasks
	dw MimeJrBitmasks
	dw HappinyBitmasks
	dw MunchlaxBitmasks
	dw MantykeBitmasks
	dw WeavileBitmasks
	dw MagnezoneBitmasks
	dw LickilickyBitmasks
	dw RhyperiorBitmasks
	dw TangrowthBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw TogekissBitmasks
	dw YanmegaBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw AMomijiBitmasks
	dw MamoswineBitmasks
	dw CLunasaZBitmasks
	dw SylveonBitmasks
	dw PerrserkerBitmasks
	dw CursolaBitmasks
	dw SirfetchDBitmasks
	dw MrRimeBitmasks
	dw WyrdeerBitmasks
	dw KleavorBitmasks
	dw UrsalunaPlainBitmasks
	dw SneaslerBitmasks
	dw OverqwilBitmasks
	dw DucmomijiTwoSegmentBitmasks
	dw FarigirafBitmasks
	dw ClodsireBitmasks
	dw AnnihilapeBitmasks
	assert_table_length NUM_SPECIES

	dw HinaBBitmasks
	dw HinaCBitmasks
	dw HinaDBitmasks
	dw HinaEBitmasks
	dw HinaFBitmasks
	dw HinaGBitmasks
	dw HinaHBitmasks
	dw HinaIBitmasks
	dw HinaJBitmasks
	dw HinaKBitmasks
	dw HinaLBitmasks
	dw HinaMBitmasks
	dw HinaNBitmasks
	dw HinaOBitmasks
	dw HinaPBitmasks
	dw HinaQBitmasks
	dw HinaRBitmasks
	dw HinaSBitmasks
	dw HinaTBitmasks
	dw HinaUBitmasks
	dw HinaVBitmasks
	dw HinaWBitmasks
	dw HinaXBitmasks
	dw HinaYBitmasks
	dw HinaZBitmasks
	dw HinaExclamationBitmasks
	dw HinaQuestionBitmasks

	dw KikuriKantoBitmasks
	dw KikuriKogaBitmasks
	dw KikuriAgathaBitmasks
	dw KikuriArianaBitmasks

	dw TTeiSpikyBitmasks

	dw LilyBlackSkellyBitmasks
	dw LilyBlackCalico1Bitmasks
	dw LilyBlackCalico2Bitmasks
	dw LilyBlackCalico3Bitmasks
	dw LilyBlackTwoToneBitmasks
	dw LilyBlackOrcaBitmasks
	dw LilyBlackDapplesBitmasks
	dw LilyBlackTigerBitmasks
	dw LilyBlackZebraBitmasks
	dw LilyBlackStripeBitmasks
	dw LilyBlackBubblesBitmasks
	dw LilyBlackDiamondsBitmasks
	dw LilyBlackPatchesBitmasks
	dw LilyBlackForehead1Bitmasks
	dw LilyBlackMask1Bitmasks
	dw LilyBlackForehead2Bitmasks
	dw LilyBlackMask2Bitmasks
	dw LilyBlackSaucyBitmasks
	dw LilyBlackRaindropBitmasks

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedBitmasks

	dw SuikaArmoredBitmasks

	dw DucmomijiThreeSegmentBitmasks

	dw UrsalunaBloodmoonBitmasks

	assert_table_length NUM_UNIQUE_TOHOMON
