CReimuBitmasks:  INCLUDE "gfx/tohomon/creimu/bitmask.asm"
ReimuBitmasks:    INCLUDE "gfx/tohomon/reimu/bitmask.asm"
TReimuBitmasks:   INCLUDE "gfx/tohomon/treimu/bitmask.asm"
CMarisaBitmasks: INCLUDE "gfx/tohomon/cmarisa/bitmask.asm"
MarisaBitmasks: INCLUDE "gfx/tohomon/marisa/bitmask.asm"
AMarisaBitmasks:  INCLUDE "gfx/tohomon/amarisa/bitmask.asm"
CSakuyaBitmasks:   INCLUDE "gfx/tohomon/csakuya/bitmask.asm"
SakuyaBitmasks:  INCLUDE "gfx/tohomon/sakuya/bitmask.asm"
HSakuyaBitmasks:  INCLUDE "gfx/tohomon/hsakuya/bitmask.asm"
CGyokuBitmasks:   INCLUDE "gfx/tohomon/cgyoku/bitmask.asm"
MGyokuBitmasks:    INCLUDE "gfx/tohomon/mgyoku/bitmask.asm"
FGyokuBitmasks: INCLUDE "gfx/tohomon/fgyoku/bitmask.asm"
OGyokuBitmasks:     INCLUDE "gfx/tohomon/ogyoku/bitmask.asm"
CMaganBitmasks:     INCLUDE "gfx/tohomon/cmagan/bitmask.asm"
MaganBitmasks:   INCLUDE "gfx/tohomon/magan/bitmask.asm"
CMimaBitmasks:  INCLUDE "gfx/tohomon/cmima/bitmask.asm"
MimaBitmasks:    INCLUDE "gfx/tohomon/mima/bitmask.asm"
ElisBitmasks:    INCLUDE "gfx/tohomon/elis/bitmask.asm"
CKikuriBitmasks:      INCLUDE "gfx/tohomon/ckikuri/bitmask.asm"
CKongaraBitmasks:   INCLUDE "gfx/tohomon/ckongara/bitmask.asm"
KongaraBitmasks:   INCLUDE "gfx/tohomon/kongara/bitmask.asm"
CRikaBitmasks:   INCLUDE "gfx/tohomon/crika/bitmask.asm"
RikaBitmasks:   INCLUDE "gfx/tohomon/rika/bitmask.asm"
ARikaBitmasks:   INCLUDE "gfx/tohomon/arika/bitmask.asm"
CMeiraBitmasks:   INCLUDE "gfx/tohomon/cmeira/bitmask.asm"
MeiraBitmasks:   INCLUDE "gfx/tohomon/meira/bitmask.asm"
EllenBitmasks: INCLUDE "gfx/tohomon/ellen/bitmask.asm"
CKotohimeBitmasks:      INCLUDE "gfx/tohomon/ckotohime/bitmask.asm"
KotohimeBitmasks:     INCLUDE "gfx/tohomon/kotohime/bitmask.asm"
CKanaBitmasks:      INCLUDE "gfx/tohomon/ckana/bitmask.asm"
KanaBitmasks:  INCLUDE "gfx/tohomon/kana/bitmask.asm"
CRikakoBitmasks:   INCLUDE "gfx/tohomon/crikako/bitmask.asm"
RikakoBitmasks:    INCLUDE "gfx/tohomon/rikako/bitmask.asm"
YumemiBitmasks:    INCLUDE "gfx/tohomon/yumemi/bitmask.asm"
COrangeBitmasks:     INCLUDE "gfx/tohomon/corange/bitmask.asm"
OrangeBitmasks:   INCLUDE "gfx/tohomon/orange/bitmask.asm"
KurumiBitmasks:    INCLUDE "gfx/tohomon/kurumi/bitmask.asm"
CEllyBitmasks:  INCLUDE "gfx/tohomon/celly/bitmask.asm"
EllyBitmasks:       INCLUDE "gfx/tohomon/elly/bitmask.asm"
CYukaBitmasks:   INCLUDE "gfx/tohomon/cyuka/bitmask.asm"
YukaBitmasks:     INCLUDE "gfx/tohomon/yuka/bitmask.asm"
AYukaBitmasks:    INCLUDE "gfx/tohomon/ayuka/bitmask.asm"
CMugetsuBitmasks:    INCLUDE "gfx/tohomon/cmugetsu/bitmask.asm"
MugetsuBitmasks: INCLUDE "gfx/tohomon/mugetsu/bitmask.asm"
CGengetsuBitmasks: INCLUDE "gfx/tohomon/cgengetsu/bitmask.asm"
GengetsuBitmasks:  INCLUDE "gfx/tohomon/gengetsu/bitmask.asm"
AliceBitmasks:  INCLUDE "gfx/tohomon/alice/bitmask.asm"
AAliceBitmasks:   INCLUDE "gfx/tohomon/aalice/bitmask.asm"
MaiBitmasks:      INCLUDE "gfx/tohomon/mai/bitmask.asm"
CYukiBitmasks:       INCLUDE "gfx/tohomon/cyuki/bitmask.asm"
YukiBitmasks:    INCLUDE "gfx/tohomon/yuki/bitmask.asm"
YumekoBitmasks:   INCLUDE "gfx/tohomon/yumeko/bitmask.asm"
CShinkiBitmasks:     INCLUDE "gfx/tohomon/cshinki/bitmask.asm"
ShinkiBitmasks:    INCLUDE "gfx/tohomon/shinki/bitmask.asm"
CRumiaBitmasks:       INCLUDE "gfx/tohomon/crumia/bitmask.asm"
RumiaBitmasks:    INCLUDE "gfx/tohomon/rumia/bitmask.asm"
ARumiaBitmasks:      INCLUDE "gfx/tohomon/arumia/bitmask.asm"
CDaichanBitmasks:     INCLUDE "gfx/tohomon/cdaichan/bitmask.asm"
DaichanBitmasks:    INCLUDE "gfx/tohomon/daichan/bitmask.asm"
CirnoBitmasks:  INCLUDE "gfx/tohomon/cirno/bitmask.asm"
CMeilingBitmasks:     INCLUDE "gfx/tohomon/cmeiling/bitmask.asm"
AMeilingBitmasks:  INCLUDE "gfx/tohomon/ameiling/bitmask.asm"
CKoakumaBitmasks: INCLUDE "gfx/tohomon/ckoakuma/bitmask.asm"
KoakumaBitmasks:  INCLUDE "gfx/tohomon/koakuma/bitmask.asm"
HKoakumaBitmasks:    INCLUDE "gfx/tohomon/hkoakuma/bitmask.asm"
PatchouliBitmasks:    INCLUDE "gfx/tohomon/patchouli/bitmask.asm"
TPatchouliBitmasks:     INCLUDE "gfx/tohomon/tpatchouli/bitmask.asm"
CRemiliaBitmasks:    INCLUDE "gfx/tohomon/cremilia/bitmask.asm"
RemiliaBitmasks:    INCLUDE "gfx/tohomon/remilia/bitmask.asm"
SRemiliaBitmasks: INCLUDE "gfx/tohomon/sremilia/bitmask.asm"
CFlandreBitmasks:     INCLUDE "gfx/tohomon/cflandre/bitmask.asm"
FlandreBitmasks:     INCLUDE "gfx/tohomon/flandre/bitmask.asm"
AFlandreBitmasks:    INCLUDE "gfx/tohomon/aflandre/bitmask.asm"
CLettyBitmasks:    INCLUDE "gfx/tohomon/cletty/bitmask.asm"
LettyBitmasks:     INCLUDE "gfx/tohomon/letty/bitmask.asm"
DLettyBitmasks:    INCLUDE "gfx/tohomon/dletty/bitmask.asm"
ChenBitmasks:    INCLUDE "gfx/tohomon/chen/bitmask.asm"
HChenBitmasks:       INCLUDE "gfx/tohomon/hchen/bitmask.asm"
CLilyWhiteBitmasks: INCLUDE "gfx/tohomon/clilywhite/bitmask.asm"
LilyWhiteBitmasks:     INCLUDE "gfx/tohomon/lilywhite/bitmask.asm"
DLilyWhiteBitmasks:     INCLUDE "gfx/tohomon/dlilywhite/bitmask.asm"
CLyricaBitmasks:     INCLUDE "gfx/tohomon/clyrica/bitmask.asm"
LyricaBitmasks:      INCLUDE "gfx/tohomon/lyrica/bitmask.asm"
TLyricaBitmasks:      INCLUDE "gfx/tohomon/tlyrica/bitmask.asm"
CMerlinBitmasks:   INCLUDE "gfx/tohomon/cmerlin/bitmask.asm"
MerlinBitmasks:    INCLUDE "gfx/tohomon/merlin/bitmask.asm"
SMerlinBitmasks:    INCLUDE "gfx/tohomon/smerlin/bitmask.asm"
CLunasaBitmasks:    INCLUDE "gfx/tohomon/clunasa/bitmask.asm"
LunasaBitmasks:    INCLUDE "gfx/tohomon/lunasa/bitmask.asm"
ALunasaBitmasks:    INCLUDE "gfx/tohomon/alunasa/bitmask.asm"
CYuyukoBitmasks:     INCLUDE "gfx/tohomon/cyuyuko/bitmask.asm"
YuyukoBitmasks:   INCLUDE "gfx/tohomon/yuyuko/bitmask.asm"
AYuyukoBitmasks: INCLUDE "gfx/tohomon/ayuyuko/bitmask.asm"
CRanBitmasks:    INCLUDE "gfx/tohomon/cran/bitmask.asm"
YukariBitmasks:    INCLUDE "gfx/tohomon/yukari/bitmask.asm"
TYukariBitmasks:  INCLUDE "gfx/tohomon/tyukari/bitmask.asm"
CSuikaBitmasks:  INCLUDE "gfx/tohomon/csuika/bitmask.asm"
TSuikaBitmasks:        INCLUDE "gfx/tohomon/tsuika/bitmask.asm"
CYoumuBitmasks:  INCLUDE "gfx/tohomon/cyoumu/bitmask.asm"
YoumuBitmasks:    INCLUDE "gfx/tohomon/youmu/bitmask.asm"
SYoumuBitmasks:   INCLUDE "gfx/tohomon/syoumu/bitmask.asm"
CReisenBitmasks:  INCLUDE "gfx/tohomon/creisen/bitmask.asm"
ReisenBitmasks:    INCLUDE "gfx/tohomon/reisen/bitmask.asm"
CSanaeBitmasks:   INCLUDE "gfx/tohomon/csanae/bitmask.asm"
SanaeBitmasks:   INCLUDE "gfx/tohomon/sanae/bitmask.asm"
DSanaeBitmasks: INCLUDE "gfx/tohomon/dsanae/bitmask.asm"
CWriggleBitmasks:    INCLUDE "gfx/tohomon/cwriggle/bitmask.asm"
WriggleBitmasks:     INCLUDE "gfx/tohomon/wriggle/bitmask.asm"
SWriggleBitmasks:   INCLUDE "gfx/tohomon/swriggle/bitmask.asm"
CMystiaBitmasks:    INCLUDE "gfx/tohomon/cmystia/bitmask.asm"
MystiaBitmasks:     INCLUDE "gfx/tohomon/mystia/bitmask.asm"
TMystiaBitmasks:     INCLUDE "gfx/tohomon/tmystia/bitmask.asm"
CKeineBitmasks:   INCLUDE "gfx/tohomon/ckeine/bitmask.asm"
KeineBitmasks:    INCLUDE "gfx/tohomon/keine/bitmask.asm"
AKeineBitmasks:     INCLUDE "gfx/tohomon/akeine/bitmask.asm"
CTeiBitmasks:   INCLUDE "gfx/tohomon/ctei/bitmask.asm"
TeiBitmasks:    INCLUDE "gfx/tohomon/tei/bitmask.asm"
CEirinBitmasks:     INCLUDE "gfx/tohomon/ceirin/bitmask.asm"
EirinBitmasks:  INCLUDE "gfx/tohomon/eirin/bitmask.asm"
TEirinBitmasks:     INCLUDE "gfx/tohomon/teirin/bitmask.asm"
CKaguyaBitmasks:    INCLUDE "gfx/tohomon/ckaguya/bitmask.asm"
KaguyaBitmasks:       INCLUDE "gfx/tohomon/kaguya/bitmask.asm"
TKaguyaBitmasks:       INCLUDE "gfx/tohomon/tkaguya/bitmask.asm"
CMokouBitmasks:     INCLUDE "gfx/tohomon/cmokou/bitmask.asm"
MokouBitmasks:    INCLUDE "gfx/tohomon/mokou/bitmask.asm"
AMokouBitmasks:   INCLUDE "gfx/tohomon/amokou/bitmask.asm"
CAyaBitmasks:  INCLUDE "gfx/tohomon/caya/bitmask.asm"
CMedicineBitmasks:  INCLUDE "gfx/tohomon/cmedicine/bitmask.asm"
AyaBitmasks:     INCLUDE "gfx/tohomon/aya/bitmask.asm"
SAyaBitmasks:  INCLUDE "gfx/tohomon/saya/bitmask.asm"
MedicineBitmasks:   INCLUDE "gfx/tohomon/medicine/bitmask.asm"
AMedicineBitmasks:     INCLUDE "gfx/tohomon/amedicine/bitmask.asm"
CKomachiBitmasks:   INCLUDE "gfx/tohomon/ckomachi/bitmask.asm"
KomachiBitmasks:   INCLUDE "gfx/tohomon/komachi/bitmask.asm"
AKomachiBitmasks:      INCLUDE "gfx/tohomon/akomachi/bitmask.asm"
CEikiBitmasks:    INCLUDE "gfx/tohomon/ceiki/bitmask.asm"
EikiBitmasks:   INCLUDE "gfx/tohomon/eiki/bitmask.asm"
AEikiBitmasks:      INCLUDE "gfx/tohomon/aeiki/bitmask.asm"
ShizuhaBitmasks:   INCLUDE "gfx/tohomon/shizuha/bitmask.asm"
SShizuhaBitmasks:     INCLUDE "gfx/tohomon/sshizuha/bitmask.asm"
CMinorikoBitmasks:    INCLUDE "gfx/tohomon/cminoriko/bitmask.asm"
MinorikoBitmasks:    INCLUDE "gfx/tohomon/minoriko/bitmask.asm"
CHinaBitmasks: INCLUDE "gfx/tohomon/china/bitmask.asm"
AHinaBitmasks:  INCLUDE "gfx/tohomon/ahina/bitmask.asm"
CNitoriBitmasks:  INCLUDE "gfx/tohomon/cnitori/bitmask.asm"
NitoriBitmasks:     INCLUDE "gfx/tohomon/nitori/bitmask.asm"
ANitoriBitmasks: INCLUDE "gfx/tohomon/anitori/bitmask.asm"
CMomijiBitmasks:  INCLUDE "gfx/tohomon/cmomiji/bitmask.asm"
MomijiBitmasks:     INCLUDE "gfx/tohomon/momiji/bitmask.asm"
CKanakoBitmasks:    INCLUDE "gfx/tohomon/ckanako/bitmask.asm"
KanakoBitmasks:   INCLUDE "gfx/tohomon/kanako/bitmask.asm"
AKanakoBitmasks:   INCLUDE "gfx/tohomon/akanako/bitmask.asm"
SuwakoBitmasks:     INCLUDE "gfx/tohomon/suwako/bitmask.asm"
DSuwakoBitmasks:    INCLUDE "gfx/tohomon/dsuwako/bitmask.asm"
CIkuBitmasks:  INCLUDE "gfx/tohomon/ciku/bitmask.asm"
AIkuBitmasks:  INCLUDE "gfx/tohomon/aiku/bitmask.asm"
CTenshiBitmasks:   INCLUDE "gfx/tohomon/ctenshi/bitmask.asm"
TenshiBitmasks:     INCLUDE "gfx/tohomon/tenshi/bitmask.asm"
STenshiBitmasks:   INCLUDE "gfx/tohomon/stenshi/bitmask.asm"
SwinubBitmasks:     INCLUDE "gfx/tohomon/swinub/bitmask.asm"
PiloswineBitmasks:  INCLUDE "gfx/tohomon/piloswine/bitmask.asm"
RemoraidBitmasks:   INCLUDE "gfx/tohomon/remoraid/bitmask.asm"
OctilleryBitmasks:  INCLUDE "gfx/tohomon/octillery/bitmask.asm"
DelibirdBitmasks:   INCLUDE "gfx/tohomon/delibird/bitmask.asm"
MantineBitmasks:    INCLUDE "gfx/tohomon/mantine/bitmask.asm"
SkarmoryBitmasks:   INCLUDE "gfx/tohomon/skarmory/bitmask.asm"
HoundourBitmasks:   INCLUDE "gfx/tohomon/houndour/bitmask.asm"
HoundoomBitmasks:   INCLUDE "gfx/tohomon/houndoom/bitmask.asm"
KingdraBitmasks:    INCLUDE "gfx/tohomon/kingdra/bitmask.asm"
PhanpyBitmasks:     INCLUDE "gfx/tohomon/phanpy/bitmask.asm"
DonphanBitmasks:    INCLUDE "gfx/tohomon/donphan/bitmask.asm"
CLunasa2Bitmasks:   INCLUDE "gfx/tohomon/clunasa2/bitmask.asm"
StantlerBitmasks:   INCLUDE "gfx/tohomon/stantler/bitmask.asm"
SmeargleBitmasks:   INCLUDE "gfx/tohomon/smeargle/bitmask.asm"
TyrogueBitmasks:    INCLUDE "gfx/tohomon/tyrogue/bitmask.asm"
HitmontopBitmasks:  INCLUDE "gfx/tohomon/hitmontop/bitmask.asm"
SmoochumBitmasks:   INCLUDE "gfx/tohomon/smoochum/bitmask.asm"
ElekidBitmasks:     INCLUDE "gfx/tohomon/elekid/bitmask.asm"
MagbyBitmasks:      INCLUDE "gfx/tohomon/magby/bitmask.asm"
MiltankBitmasks:    INCLUDE "gfx/tohomon/miltank/bitmask.asm"
BlisseyBitmasks:    INCLUDE "gfx/tohomon/blissey/bitmask.asm"
RaikouBitmasks:     INCLUDE "gfx/tohomon/raikou/bitmask.asm"
EnteiBitmasks:      INCLUDE "gfx/tohomon/entei/bitmask.asm"
SuicuneBitmasks:    INCLUDE "gfx/tohomon/suicune/bitmask.asm"
LarvitarBitmasks:   INCLUDE "gfx/tohomon/larvitar/bitmask.asm"
PupitarBitmasks:    INCLUDE "gfx/tohomon/pupitar/bitmask.asm"
TyranitarBitmasks:  INCLUDE "gfx/tohomon/tyranitar/bitmask.asm"
LugiaBitmasks:      INCLUDE "gfx/tohomon/lugia/bitmask.asm"
HoOhBitmasks:       INCLUDE "gfx/tohomon/ho_oh/bitmask.asm"
CelebiBitmasks:     INCLUDE "gfx/tohomon/celebi/bitmask.asm"
AzurillBitmasks:    INCLUDE "gfx/tohomon/azurill/bitmask.asm"
WynautBitmasks:     INCLUDE "gfx/tohomon/wynaut/bitmask.asm"
AmbipomBitmasks:    INCLUDE "gfx/tohomon/ambipom/bitmask.asm"
MismagiusBitmasks:  INCLUDE "gfx/tohomon/mismagius/bitmask.asm"
HonchkrowBitmasks:  INCLUDE "gfx/tohomon/honchkrow/bitmask.asm"
BonslyBitmasks:     INCLUDE "gfx/tohomon/bonsly/bitmask.asm"
MimeJrBitmasks:     INCLUDE "gfx/tohomon/mime_jr_/bitmask.asm"
HappinyBitmasks:    INCLUDE "gfx/tohomon/happiny/bitmask.asm"
MunchlaxBitmasks:   INCLUDE "gfx/tohomon/munchlax/bitmask.asm"
MantykeBitmasks:    INCLUDE "gfx/tohomon/mantyke/bitmask.asm"
WeavileBitmasks:    INCLUDE "gfx/tohomon/weavile/bitmask.asm"
MagnezoneBitmasks:  INCLUDE "gfx/tohomon/magnezone/bitmask.asm"
LickilickyBitmasks: INCLUDE "gfx/tohomon/lickilicky/bitmask.asm"
RhyperiorBitmasks:  INCLUDE "gfx/tohomon/rhyperior/bitmask.asm"
TangrowthBitmasks:  INCLUDE "gfx/tohomon/tangrowth/bitmask.asm"
ElectivireBitmasks: INCLUDE "gfx/tohomon/electivire/bitmask.asm"
MagmortarBitmasks:  INCLUDE "gfx/tohomon/magmortar/bitmask.asm"
TogekissBitmasks:   INCLUDE "gfx/tohomon/togekiss/bitmask.asm"
YanmegaBitmasks:    INCLUDE "gfx/tohomon/yanmega/bitmask.asm"
LeafeonBitmasks:    INCLUDE "gfx/tohomon/leafeon/bitmask.asm"
GlaceonBitmasks:    INCLUDE "gfx/tohomon/glaceon/bitmask.asm"
AMomijiBitmasks:    INCLUDE "gfx/tohomon/amomiji/bitmask.asm"
MamoswineBitmasks:  INCLUDE "gfx/tohomon/mamoswine/bitmask.asm"
CLunasaZBitmasks:   INCLUDE "gfx/tohomon/clunasa_z/bitmask.asm"
SylveonBitmasks:    INCLUDE "gfx/tohomon/sylveon/bitmask.asm"
PerrserkerBitmasks: INCLUDE "gfx/tohomon/perrserker/bitmask.asm"
CursolaBitmasks:    INCLUDE "gfx/tohomon/cursola/bitmask.asm"
SirfetchDBitmasks:  INCLUDE "gfx/tohomon/sirfetch_d/bitmask.asm"
MrRimeBitmasks:     INCLUDE "gfx/tohomon/mr__rime/bitmask.asm"
WyrdeerBitmasks:    INCLUDE "gfx/tohomon/wyrdeer/bitmask.asm"
KleavorBitmasks:    INCLUDE "gfx/tohomon/kleavor/bitmask.asm"
SneaslerBitmasks:   INCLUDE "gfx/tohomon/sneasler/bitmask.asm"
OverqwilBitmasks:   INCLUDE "gfx/tohomon/overqwil/bitmask.asm"
FarigirafBitmasks:  INCLUDE "gfx/tohomon/farigiraf/bitmask.asm"
ClodsireBitmasks:   INCLUDE "gfx/tohomon/clodsire/bitmask.asm"
AnnihilapeBitmasks: INCLUDE "gfx/tohomon/annihilape/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/tohomon/egg/bitmask.asm"

HinaABitmasks: INCLUDE "gfx/tohomon/hina_a/bitmask.asm"
HinaBBitmasks: INCLUDE "gfx/tohomon/hina_b/bitmask.asm"
HinaCBitmasks: INCLUDE "gfx/tohomon/hina_c/bitmask.asm"
HinaDBitmasks: INCLUDE "gfx/tohomon/hina_d/bitmask.asm"
HinaEBitmasks: INCLUDE "gfx/tohomon/hina_e/bitmask.asm"
HinaFBitmasks: INCLUDE "gfx/tohomon/hina_f/bitmask.asm"
HinaGBitmasks: INCLUDE "gfx/tohomon/hina_g/bitmask.asm"
HinaHBitmasks: INCLUDE "gfx/tohomon/hina_h/bitmask.asm"
HinaIBitmasks: INCLUDE "gfx/tohomon/hina_i/bitmask.asm"
HinaJBitmasks: INCLUDE "gfx/tohomon/hina_j/bitmask.asm"
HinaKBitmasks: INCLUDE "gfx/tohomon/hina_k/bitmask.asm"
HinaLBitmasks: INCLUDE "gfx/tohomon/hina_l/bitmask.asm"
HinaMBitmasks: INCLUDE "gfx/tohomon/hina_m/bitmask.asm"
HinaNBitmasks: INCLUDE "gfx/tohomon/hina_n/bitmask.asm"
HinaOBitmasks: INCLUDE "gfx/tohomon/hina_o/bitmask.asm"
HinaPBitmasks: INCLUDE "gfx/tohomon/hina_p/bitmask.asm"
HinaQBitmasks: INCLUDE "gfx/tohomon/hina_q/bitmask.asm"
HinaRBitmasks: INCLUDE "gfx/tohomon/hina_r/bitmask.asm"
HinaSBitmasks: INCLUDE "gfx/tohomon/hina_s/bitmask.asm"
HinaTBitmasks: INCLUDE "gfx/tohomon/hina_t/bitmask.asm"
HinaUBitmasks: INCLUDE "gfx/tohomon/hina_u/bitmask.asm"
HinaVBitmasks: INCLUDE "gfx/tohomon/hina_v/bitmask.asm"
HinaWBitmasks: INCLUDE "gfx/tohomon/hina_w/bitmask.asm"
HinaXBitmasks: INCLUDE "gfx/tohomon/hina_x/bitmask.asm"
HinaYBitmasks: INCLUDE "gfx/tohomon/hina_y/bitmask.asm"
HinaZBitmasks: INCLUDE "gfx/tohomon/hina_z/bitmask.asm"
HinaExclamationBitmasks: INCLUDE "gfx/tohomon/hina_exclamation/bitmask.asm"
HinaQuestionBitmasks:    INCLUDE "gfx/tohomon/hina_question/bitmask.asm"

TTeiBitmasks: INCLUDE "gfx/tohomon/ttei/bitmask.asm"
TTeiSpikyBitmasks: INCLUDE "gfx/tohomon/ttei_spiky/bitmask.asm"

KikuriPlainBitmasks:  INCLUDE "gfx/tohomon/kikuri/bitmask.asm"
KikuriFlyBitmasks:    INCLUDE "gfx/tohomon/kikuri_fly/bitmask.asm"
KikuriSurfBitmasks:   INCLUDE "gfx/tohomon/kikuri_surf/bitmask.asm"
KikuriPikaBitmasks:   INCLUDE "gfx/tohomon/kikuri_pika/bitmask.asm"
KikuriChuchuBitmasks: INCLUDE "gfx/tohomon/kikuri_chuchu/bitmask.asm"
KikuriSparkBitmasks:  INCLUDE "gfx/tohomon/kikuri_spark/bitmask.asm"

LilyBlackBitmasks:     INCLUDE "gfx/tohomon/lilyblack/bitmask.asm"
LilyBlackSkellyBitmasks:    INCLUDE "gfx/tohomon/lilyblack_skelly/bitmask.asm"
LilyBlackCalico1Bitmasks:   INCLUDE "gfx/tohomon/lilyblack_calico1/bitmask.asm"
LilyBlackCalico2Bitmasks:   INCLUDE "gfx/tohomon/lilyblack_calico2/bitmask.asm"
LilyBlackCalico3Bitmasks:   INCLUDE "gfx/tohomon/lilyblack_calico3/bitmask.asm"
LilyBlackTwoToneBitmasks:   INCLUDE "gfx/tohomon/lilyblack_twotone/bitmask.asm"
LilyBlackOrcaBitmasks:      INCLUDE "gfx/tohomon/lilyblack_orca/bitmask.asm"
LilyBlackDapplesBitmasks:   INCLUDE "gfx/tohomon/lilyblack_dapples/bitmask.asm"
LilyBlackTigerBitmasks:     INCLUDE "gfx/tohomon/lilyblack_tiger/bitmask.asm"
LilyBlackZebraBitmasks:     INCLUDE "gfx/tohomon/lilyblack_zebra/bitmask.asm"
LilyBlackStripeBitmasks:    INCLUDE "gfx/tohomon/lilyblack_stripe/bitmask.asm"
LilyBlackBubblesBitmasks:   INCLUDE "gfx/tohomon/lilyblack_bubbles/bitmask.asm"
LilyBlackDiamondsBitmasks:  INCLUDE "gfx/tohomon/lilyblack_diamonds/bitmask.asm"
LilyBlackPatchesBitmasks:   INCLUDE "gfx/tohomon/lilyblack_patches/bitmask.asm"
LilyBlackForehead1Bitmasks: INCLUDE "gfx/tohomon/lilyblack_forehead1/bitmask.asm"
LilyBlackMask1Bitmasks:     INCLUDE "gfx/tohomon/lilyblack_mask1/bitmask.asm"
LilyBlackForehead2Bitmasks: INCLUDE "gfx/tohomon/lilyblack_forehead2/bitmask.asm"
LilyBlackMask2Bitmasks:     INCLUDE "gfx/tohomon/lilyblack_mask2/bitmask.asm"
LilyBlackSaucyBitmasks:     INCLUDE "gfx/tohomon/lilyblack_saucy/bitmask.asm"
LilyBlackRaindropBitmasks:  INCLUDE "gfx/tohomon/lilyblack_raindrop/bitmask.asm"

PlacethmTwoSegmentBitmasks:   INCLUDE "gfx/tohomon/placethm_two_segment/bitmask.asm"
PlacethmThreeSegmentBitmasks: INCLUDE "gfx/tohomon/placethm_three_segment/bitmask.asm"

SLilyBlackBitmasks: INCLUDE "gfx/tohomon/slilyblack/bitmask.asm"
SLilyBlackRedBitmasks:   INCLUDE "gfx/tohomon/slilyblack_red/bitmask.asm"

SuikaBitmasks:   INCLUDE "gfx/tohomon/suika/bitmask.asm"
SuikaArmoredBitmasks: INCLUDE "gfx/tohomon/suika_armored/bitmask.asm"

CElisBitmasks:  INCLUDE "gfx/tohomon/celis/bitmask.asm"

CSarielBitmasks:  INCLUDE "gfx/tohomon/csariel/bitmask.asm"

SarielBitmasks:  INCLUDE "gfx/tohomon/sariel/bitmask.asm"

CEllenBitmasks:  INCLUDE "gfx/tohomon/cellen/bitmask.asm"

CChiyuriBitmasks:  INCLUDE "gfx/tohomon/cchiyuri/bitmask.asm"

ChiyuriBitmasks:  INCLUDE "gfx/tohomon/chiyuri/bitmask.asm"

CYumemiBitmasks:  INCLUDE "gfx/tohomon/cyumemi/bitmask.asm"

CSaraBitmasks:  INCLUDE "gfx/tohomon/csara/bitmask.asm"

SaraBitmasks:  INCLUDE "gfx/tohomon/sara/bitmask.asm"


CYumekoBitmasks:  INCLUDE "gfx/tohomon/cyumeko/bitmask.asm"

SCirnoBitmasks:  INCLUDE "gfx/tohomon/scirno/bitmask.asm"

MeilingBitmasks:  INCLUDE "gfx/tohomon/meiling/bitmask.asm"

CLuizeBitmasks:    INCLUDE "gfx/tohomon/cluize/bitmask.asm"

LuizeBitmasks:    INCLUDE "gfx/tohomon/luize/bitmask.asm"

DLuizeBitmasks:   INCLUDE "gfx/tohomon/dluize/bitmask.asm"

CAliceBitmasks:    INCLUDE "gfx/tohomon/calice/bitmask.asm"

CMaiBitmasks:     INCLUDE "gfx/tohomon/cmai/bitmask.asm"

CPatchouliBitmasks:    INCLUDE "gfx/tohomon/cpatchouli/bitmask.asm"

CChenBitmasks:    INCLUDE "gfx/tohomon/cchen/bitmask.asm"

RanBitmasks:    INCLUDE "gfx/tohomon/ran/bitmask.asm"

TRanBitmasks:    INCLUDE "gfx/tohomon/tran/bitmask.asm"

CYukariBitmasks:    INCLUDE "gfx/tohomon/cyukari/bitmask.asm"

HMinorikoBitmasks:    INCLUDE "gfx/tohomon/hminoriko/bitmask.asm"

CorsolaBitmasks:    INCLUDE "gfx/tohomon/corsola/bitmask.asm"

CKurumiBitmasks:   INCLUDE "gfx/tohomon/ckurumi/bitmask.asm"

DDaichanBitmasks:   INCLUDE "gfx/tohomon/ddaichan/bitmask.asm"

CCirnoBitmasks:   INCLUDE "gfx/tohomon/ccirno/bitmask.asm"

TReisenBitmasks:   INCLUDE "gfx/tohomon/treisen/bitmask.asm"

CSuwakoBitmasks:   INCLUDE "gfx/tohomon/csuwako/bitmask.asm"

IkuBitmasks:   INCLUDE "gfx/tohomon/iku/bitmask.asm"

CShizuhaBitmasks:    INCLUDE "gfx/tohomon/cshizuha/bitmask.asm"
CLilyBlackBitmasks:        INCLUDE "gfx/tohomon/clilyblack/bitmask.asm"
