Footprints:: ; needed for BANK(Footprints)

BlankFootprint::
CYuyukoFootprint::
CKeineFootprint::
CGyokuFootprint::
OGyokuFootprint::
LettyFootprint::
DLettyFootprint::
CLunasaZFootprint::
CMinorikoFootprint::
LeafeonFootprint::
GlaceonFootprint::
ElisFootprint::
CorsolaFootprint::
CursolaFootprint:: 
KikuriFootprint::
CAyaFootprint::
CTeiFootprint::
AKeineFootprint::
YukiFootprint::
CChiyuriFootprint::
LyricaFootprint::
TYukariFootprint::
YukariFootprint::
PlacethmFootprint::
ChiyuriFootprint::
CMomijiFootprint::
CKikuriFootprint::
CCirnoFootprint::
CirnoFootprint::
ANitoriFootprint::
CShinkiFootprint::
CSaraFootprint::
AFlandreFootprint::
SLilyBlackFootprint::
ShinkiFootprint::
CFlandreFootprint::
HChenFootprint::
CMaganFootprint::
KingdraFootprint::
HKoakumaFootprint::
TeiFootprint::
CLyricaFootprint::
STenshiFootprint::
LilyBlackFootprint::
MagnezoneFootprint::
MantineFootprint::
MantykeFootprint::
MGyokuFootprint::
CHinaFootprint::
MismagiusFootprint::
CYumekoFootprint::
CRumiaFootprint::
OverqwilFootprint::
NitoriFootprint::
PupitarFootprint::
CSuwakoFootprint::
RemoraidFootprint::
FlandreFootprint::
CLettyFootprint::
CYukiFootprint::
YumekoFootprint::
TenshiFootprint::
CKanakoFootprint::
CEikiFootprint::
GengetsuFootprint::
HinaFootprint::
CGengetsuFootprint::
DDaichanFootprint::
CPatchouliFootprint::
CKotohimeFootprint::
CReimuFootprint::
ReimuFootprint::
TReimuFootprint::
CMarisaFootprint::
MarisaFootprint::
AMarisaFootprint::
CSakuyaFootprint::
SakuyaFootprint::
HSakuyaFootprint::
FGyokuFootprint:: 
MaganFootprint::
CMimaFootprint:: 
MimaFootprint::

CElisFootprint::
CSarielFootprint::
SarielFootprint::
CKongaraFootprint::
KongaraFootprint::
CRikaFootprint::
RikaFootprint::
ARikaFootprint::
CMeiraFootprint:: 
MeiraFootprint:: 
CEllenFootprint:: 
EllenFootprint:: 
KotohimeFootprint:: 
CKanaFootprint:: 
KanaFootprint:: 
CRikakoFootprint:: 
RikakoFootprint:: 
CYumemiFootprint:: 
YumemiFootprint:: 
COrangeFootprint:: 
OrangeFootprint:: 
CKurumiFootprint:: 
KurumiFootprint:: 
CEllyFootprint:: 
EllyFootprint:: 
CYukaFootprint:: 
YukaFootprint:: 
AYukaFootprint:: 
CMugetsuFootprint:: 
MugetsuFootprint:: 
SaraFootprint:: 
CLuizeFootprint:: 
LuizeFootprint:: 
DLuizeFootprint:: 
CAliceFootprint:: 
AliceFootprint:: 
AAliceFootprint:: 
CMaiFootprint:: 
MaiFootprint::  
RumiaFootprint:: 
ARumiaFootprint:: 
CDaichanFootprint:: 
DaichanFootprint:: 
SCirnoFootprint:: 
CMeilingFootprint:: 
MeilingFootprint:: 
AMeilingFootprint:: 
CKoakumaFootprint:: 
KoakumaFootprint:: 
PatchouliFootprint:: 
TPatchouliFootprint:: 
CRemiliaFootprint:: 
RemiliaFootprint:: 
SRemiliaFootprint:: 
CChenFootprint:: 
ChenFootprint:: 
CLilyWhiteFootprint:: 
LilyWhiteFootprint:: 
DLilyWhiteFootprint:: 
CLilyBlackFootprint:: 
TLyricaFootprint:: 
CMerlinFootprint:: 
MerlinFootprint:: 
SMerlinFootprint:: 
CLunasaFootprint:: 
LunasaFootprint:: 
ALunasaFootprint:: 
YuyukoFootprint:: 
AYuyukoFootprint:: 
CRanFootprint:: 
RanFootprint:: 
TRanFootprint:: 
CYukariFootprint:: 
CSuikaFootprint:: 
SuikaFootprint:: 
TSuikaFootprint:: 
CYoumuFootprint::
YoumuFootprint:: 
SYoumuFootprint:: 
CReisenFootprint:: 
ReisenFootprint:: 
TReisenFootprint:: 
CSanaeFootprint:: 
SanaeFootprint:: 
DSanaeFootprint:: 
CWriggleFootprint:: 
WriggleFootprint:: 
SWriggleFootprint:: 
CMystiaFootprint:: 
MystiaFootprint:: 
TMystiaFootprint:: 
KeineFootprint:: 
TTeiFootprint:: 
CEirinFootprint:: 
EirinFootprint:: 
TEirinFootprint:: 
CKaguyaFootprint:: 
KaguyaFootprint:: 
TKaguyaFootprint:: 
CMokouFootprint:: 
MokouFootprint:: 
AMokouFootprint:: 
AyaFootprint:: 
SAyaFootprint::
CMedicineFootprint::
MedicineFootprint::
AMedicineFootprint:: 
CKomachiFootprint::
KomachiFootprint::
AKomachiFootprint::
EikiFootprint::
AEikiFootprint::
CShizuhaFootprint::
ShizuhaFootprint::
SShizuhaFootprint::
MinorikoFootprint::
HMinorikoFootprint::
AHinaFootprint:: 
CNitoriFootprint::
MomijiFootprint::
KanakoFootprint::
AKanakoFootprint::
SuwakoFootprint::
DSuwakoFootprint:: 
CIkuFootprint::
IkuFootprint::
AIkuFootprint::
CTenshiFootprint::
SwinubFootprint::
PiloswineFootprint::
OctilleryFootprint::
DelibirdFootprint:: 
SkarmoryFootprint::
HoundourFootprint::
HoundoomFootprint::
PhanpyFootprint::
DonphanFootprint::
CLunasa2Footprint:: 
StantlerFootprint::
SmeargleFootprint:: 
TyrogueFootprint:: 
HitmontopFootprint:: 
SmoochumFootprint:: 
ElekidFootprint::
MagbyFootprint:: 
MiltankFootprint::
BlisseyFootprint::
RaikouFootprint::
EnteiFootprint::
SuicuneFootprint::
LarvitarFootprint::
TyranitarFootprint::
LugiaFootprint:: 
HoOhFootprint:: 
CelebiFootprint::
AzurillFootprint::
WynautFootprint::
AmbipomFootprint::
EggFootprint::
HonchkrowFootprint::
BonslyFootprint:: 
MimeJrFootprint::
HappinyFootprint::
MunchlaxFootprint::
WeavileFootprint::
LickilickyFootprint::
RhyperiorFootprint::
TangrowthFootprint:: 
ElectivireFootprint::
MagmortarFootprint::
TogekissFootprint::
YanmegaFootprint::
AMomijiFootprint::
MamoswineFootprint::
SylveonFootprint::
PerrserkerFootprint::
SirfetchDFootprint::
MrRimeFootprint::
WyrdeerFootprint::
KleavorFootprint::
UrsalunaFootprint::
SneaslerFootprint:: 
FarigirafFootprint::
ClodsireFootprint:: 
AnnihilapeFootprint:: INCBIN "gfx/footprints/blank.1bpp.lz"
