FramesPointers:
	table_width 2
	dw CReimuFrames
	dw ReimuFrames
	dw TReimuFrames
	dw CMarisaFrames
	dw MarisaFrames
	dw AMarisaFrames
	dw CSakuyaFrames
	dw SakuyaFrames
	dw HSakuyaFrames
	dw CGyokuFrames
	dw MGyokuFrames
	dw FGyokuFrames
	dw OGyokuFrames
	dw CMaganFrames
	dw MaganFrames
	dw CMimaFrames
	dw MimaFrames
	dw CElisFrames
	dw ElisFrames
	dw CKikuriFrames
	dw KikuriJohtoFrames
	dw CSarielFrames
	dw SarielFrames
	dw CKongaraFrames
	dw KongaraFrames
	dw CRikaFrames
	dw RikaFrames
	dw ARikaFrames
	dw CMeiraFrames
	dw MeiraFrames
	dw CEllenFrames
	dw EllenFrames
	dw CKotohimeFrames
	dw KotohimeFrames
	dw CKanaFrames
	dw KanaFrames
	dw CRikakoFrames
	dw RikakoFrames
	dw CChiyuriFrames
	dw ChiyuriFrames
	dw CYumemiFrames
	dw YumemiFrames
	dw COrangeFrames
	dw OrangeFrames
	dw CKurumiFrames
	dw KurumiFrames
	dw CEllyFrames
	dw EllyFrames
	dw CYukaFrames
	dw YukaFrames
	dw AYukaFrames
	dw CMugetsuFrames
	dw MugetsuFrames
	dw CGengetsuFrames
	dw GengetsuFrames
	dw CSaraFrames
	dw SaraFrames
	dw CLuizeFrames
	dw LuizeFrames
	dw DLuizeFrames
	dw CAliceFrames
	dw AliceFrames
	dw AAliceFrames
	dw CMaiFrames
	dw MaiFrames
	dw CYukiFrames
	dw YukiFrames
	dw CYumekoFrames
	dw YumekoFrames
	dw CShinkiFrames
	dw ShinkiFrames
	dw CRumiaFrames
	dw RumiaFrames
	dw ARumiaFrames
	dw CDaichanFrames
	dw DaichanFrames
	dw DDaichanFrames
	dw CCirnoFrames
	dw CirnoFrames
	dw SCirnoFrames
	dw CMeilingFrames
	dw MeilingFrames
	dw AMeilingFrames
	dw CKoakumaFrames
	dw KoakumaFrames
	dw HKoakumaFrames
	dw CPatchouliFrames
	dw PatchouliFrames
	dw TPatchouliFrames
	dw CRemiliaFrames
	dw RemiliaFrames
	dw SRemiliaFrames
	dw CFlandreFrames
	dw FlandreFrames
	dw AFlandreFrames
	dw CLettyFrames
	dw LettyFrames
	dw DLettyFrames
	dw CChenFrames
	dw ChenFrames
	dw HChenFrames
	dw CLilyWhiteFrames
	dw LilyWhiteFrames
	dw DLilyWhiteFrames
	dw CLilyBlackFrames
	dw LilyBlackFrames
	dw SLilyBlackFrames
	dw CLyricaFrames
	dw LyricaFrames
	dw TLyricaFrames
	dw CMerlinFrames
	dw MerlinFrames
	dw SMerlinFrames
	dw CLunasaFrames
	dw LunasaFrames
	dw ALunasaFrames
	dw CYuyukoFrames
	dw YuyukoFrames
	dw AYuyukoFrames
	dw CRanFrames
	dw RanFrames
	dw TRanFrames
	dw CYukariFrames
	dw YukariFrames
	dw TYukariFrames
	dw CSuikaFrames
	dw SuikaFrames
	dw TSuikaFrames
	dw CYoumuFrames
	dw YoumuFrames
	dw SYoumuFrames
	dw CReisenFrames
	dw ReisenFrames
	dw TReisenFrames
	dw CSanaeFrames
	dw SanaeFrames
	dw DSanaeFrames
	dw CWriggleFrames
	dw WriggleFrames
	dw SWriggleFrames
	dw CMystiaFrames
	dw MystiaFrames
	dw TMystiaFrames
	dw CKeineFrames
	dw KeineFrames
	dw AKeineFrames
	dw CTeiFrames
	dw TeiFrames
	dw TTeiFrames
	dw CEirinFrames
	dw EirinFrames
	dw TEirinFrames
	dw CKaguyaFrames
	dw KaguyaFrames
	dw TKaguyaFrames
	dw CMokouFrames
	dw MokouFrames
	dw AMokouFrames
	dw CAyaFrames
	dw AyaFrames
	dw SAyaFrames
	dw CMedicineFrames
	dw MedicineFrames
	dw AMedicineFrames
	dw CKomachiFrames
	dw KomachiFrames
	dw AKomachiFrames
	dw CEikiFrames
	dw EikiFrames
	dw AEikiFrames
	dw CShizuhaFrames
	dw ShizuhaFrames
	dw SShizuhaFrames
	dw CMinorikoFrames
	dw MinorikoFrames
	dw HMinorikoFrames
	dw CHinaFrames
	dw HinaAFrames
	dw AHinaFrames
	dw CNitoriFrames
	dw NitoriFrames
	dw ANitoriFrames
	dw CMomijiFrames
	dw MomijiFrames
	dw CKanakoFrames
	dw KanakoFrames
	dw AKanakoFrames
	dw CSuwakoFrames
	dw SuwakoFrames
	dw DSuwakoFrames
	dw CIkuFrames
	dw IkuFrames
	dw AIkuFrames
	dw CTenshiFrames
	dw TenshiFrames
	dw STenshiFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw CLunasa2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw AzurillFrames
	dw WynautFrames
	dw AmbipomFrames
	dw EggFrames
	dw EggFrames ; $100
	dw MismagiusFrames
	dw HonchkrowFrames
	dw BonslyFrames
	dw MimeJrFrames
	dw HappinyFrames
	dw MunchlaxFrames
	dw MantykeFrames
	dw WeavileFrames
	dw MagnezoneFrames
	dw LickilickyFrames
	dw RhyperiorFrames
	dw TangrowthFrames
	dw ElectivireFrames
	dw MagmortarFrames
	dw TogekissFrames
	dw YanmegaFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw AMomijiFrames
	dw MamoswineFrames
	dw CLunasaZFrames
	dw SylveonFrames
	dw PerrserkerFrames
	dw CursolaFrames
	dw SirfetchDFrames
	dw MrRimeFrames
	dw WyrdeerFrames
	dw KleavorFrames
	dw UrsalunaFrames
	dw SneaslerFrames
	dw OverqwilFrames
	dw PlacethmTwoSegmentFrames
	dw FarigirafFrames
	dw ClodsireFrames
	dw AnnihilapeFrames
	assert_table_length NUM_SPECIES

	dw HinaBFrames
	dw HinaCFrames
	dw HinaDFrames
	dw HinaEFrames
	dw HinaFFrames
	dw HinaGFrames
	dw HinaHFrames
	dw HinaIFrames
	dw HinaJFrames
	dw HinaKFrames
	dw HinaLFrames
	dw HinaMFrames
	dw HinaNFrames
	dw HinaOFrames
	dw HinaPFrames
	dw HinaQFrames
	dw HinaRFrames
	dw HinaSFrames
	dw HinaTFrames
	dw HinaUFrames
	dw HinaVFrames
	dw HinaWFrames
	dw HinaXFrames
	dw HinaYFrames
	dw HinaZFrames
	dw HinaExclamationFrames
	dw HinaQuestionFrames

	dw KikuriKantoFrames
	dw KikuriKogaFrames
	dw KikuriAgathaFrames
	dw KikuriArianaFrames



	dw TTeiSpikyFrames

	dw LilyBlackSkellyFrames
	dw LilyBlackCalico1Frames
	dw LilyBlackCalico2Frames
	dw LilyBlackCalico3Frames
	dw LilyBlackTwoToneFrames
	dw LilyBlackOrcaFrames
	dw LilyBlackDapplesFrames
	dw LilyBlackTigerFrames
	dw LilyBlackZebraFrames
	dw LilyBlackStripeFrames
	dw LilyBlackBubblesFrames
	dw LilyBlackDiamondsFrames
	dw LilyBlackPatchesFrames
	dw LilyBlackForehead1Frames
	dw LilyBlackMask1Frames
	dw LilyBlackForehead2Frames
	dw LilyBlackMask2Frames
	dw LilyBlackSaucyFrames
	dw LilyBlackRaindropFrames

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedFrames

	dw SuikaArmoredFrames

	dw PlacethmThreeSegmentFrames

	assert_table_length NUM_UNIQUE_TOHOMON
