KantoFrames:

CReimuFrames:  INCLUDE "gfx/tohomon/creimu/frames.asm"
ReimuFrames:    INCLUDE "gfx/tohomon/reimu/frames.asm"
TReimuFrames:   INCLUDE "gfx/tohomon/treimu/frames.asm"
CMarisaFrames: INCLUDE "gfx/tohomon/cmarisa/frames.asm"
MarisaFrames: INCLUDE "gfx/tohomon/marisa/frames.asm"
AMarisaFrames:  INCLUDE "gfx/tohomon/amarisa/frames.asm"
CSakuyaFrames:   INCLUDE "gfx/tohomon/csakuya/frames.asm"
SakuyaFrames:  INCLUDE "gfx/tohomon/sakuya/frames.asm"
HSakuyaFrames:  INCLUDE "gfx/tohomon/hsakuya/frames.asm"
CGyokuFrames:   INCLUDE "gfx/tohomon/cgyoku/frames.asm"
MGyokuFrames:    INCLUDE "gfx/tohomon/mgyoku/frames.asm"
FGyokuFrames: INCLUDE "gfx/tohomon/fgyoku/frames.asm"
OGyokuFrames:     INCLUDE "gfx/tohomon/ogyoku/frames.asm"
CMaganFrames:     INCLUDE "gfx/tohomon/cmagan/frames.asm"
MaganFrames:   INCLUDE "gfx/tohomon/magan/frames.asm"
CMimaFrames:  INCLUDE "gfx/tohomon/cmima/frames.asm"
MimaFrames:    INCLUDE "gfx/tohomon/mima/frames.asm"
ElisFrames:    INCLUDE "gfx/tohomon/elis/frames.asm"
CKikuriFrames:      INCLUDE "gfx/tohomon/ckikuri/frames.asm"
CKongaraFrames:   INCLUDE "gfx/tohomon/ckongara/frames.asm"
KongaraFrames:   INCLUDE "gfx/tohomon/kongara/frames.asm"
CRikaFrames:   INCLUDE "gfx/tohomon/crika/frames.asm"
RikaFrames:   INCLUDE "gfx/tohomon/rika/frames.asm"
ARikaFrames:   INCLUDE "gfx/tohomon/arika/frames.asm"
CMeiraFrames:   INCLUDE "gfx/tohomon/cmeira/frames.asm"
MeiraFrames:   INCLUDE "gfx/tohomon/meira/frames.asm"
EllenFrames: INCLUDE "gfx/tohomon/ellen/frames.asm"
CKotohimeFrames:      INCLUDE "gfx/tohomon/ckotohime/frames.asm"
KotohimeFrames:     INCLUDE "gfx/tohomon/kotohime/frames.asm"
CKanaFrames:      INCLUDE "gfx/tohomon/ckana/frames.asm"
KanaFrames:  INCLUDE "gfx/tohomon/kana/frames.asm"
CRikakoFrames:   INCLUDE "gfx/tohomon/crikako/frames.asm"
RikakoFrames:    INCLUDE "gfx/tohomon/rikako/frames.asm"
YumemiFrames:    INCLUDE "gfx/tohomon/yumemi/frames.asm"
COrangeFrames:     INCLUDE "gfx/tohomon/corange/frames.asm"
OrangeFrames:   INCLUDE "gfx/tohomon/orange/frames.asm"
KurumiFrames:    INCLUDE "gfx/tohomon/kurumi/frames.asm"
CEllyFrames:  INCLUDE "gfx/tohomon/celly/frames.asm"
EllyFrames:       INCLUDE "gfx/tohomon/elly/frames.asm"
CYukaFrames:   INCLUDE "gfx/tohomon/cyuka/frames.asm"
YukaFrames:     INCLUDE "gfx/tohomon/yuka/frames.asm"
AYukaFrames:    INCLUDE "gfx/tohomon/ayuka/frames.asm"
CMugetsuFrames:    INCLUDE "gfx/tohomon/cmugetsu/frames.asm"
MugetsuFrames: INCLUDE "gfx/tohomon/mugetsu/frames.asm"
CGengetsuFrames: INCLUDE "gfx/tohomon/cgengetsu/frames.asm"
GengetsuFrames:  INCLUDE "gfx/tohomon/gengetsu/frames.asm"
AliceFrames:  INCLUDE "gfx/tohomon/alice/frames.asm"
AAliceFrames:   INCLUDE "gfx/tohomon/aalice/frames.asm"
MaiFrames:      INCLUDE "gfx/tohomon/mai/frames.asm"
CYukiFrames:       INCLUDE "gfx/tohomon/cyuki/frames.asm"
YukiFrames:    INCLUDE "gfx/tohomon/yuki/frames.asm"
YumekoFrames:   INCLUDE "gfx/tohomon/yumeko/frames.asm"
CShinkiFrames:     INCLUDE "gfx/tohomon/cshinki/frames.asm"
ShinkiFrames:    INCLUDE "gfx/tohomon/shinki/frames.asm"
CRumiaFrames:       INCLUDE "gfx/tohomon/crumia/frames.asm"
RumiaFrames:    INCLUDE "gfx/tohomon/rumia/frames.asm"
ARumiaFrames:      INCLUDE "gfx/tohomon/arumia/frames.asm"
CDaichanFrames:     INCLUDE "gfx/tohomon/cdaichan/frames.asm"
DaichanFrames:    INCLUDE "gfx/tohomon/daichan/frames.asm"
CirnoFrames:  INCLUDE "gfx/tohomon/cirno/frames.asm"
CMeilingFrames:     INCLUDE "gfx/tohomon/cmeiling/frames.asm"
AMeilingFrames:  INCLUDE "gfx/tohomon/ameiling/frames.asm"
CKoakumaFrames: INCLUDE "gfx/tohomon/ckoakuma/frames.asm"
KoakumaFrames:  INCLUDE "gfx/tohomon/koakuma/frames.asm"
HKoakumaFrames:    INCLUDE "gfx/tohomon/hkoakuma/frames.asm"
PatchouliFrames:    INCLUDE "gfx/tohomon/patchouli/frames.asm"
TPatchouliFrames:     INCLUDE "gfx/tohomon/tpatchouli/frames.asm"
CRemiliaFrames:    INCLUDE "gfx/tohomon/cremilia/frames.asm"
RemiliaFrames:    INCLUDE "gfx/tohomon/remilia/frames.asm"
SRemiliaFrames: INCLUDE "gfx/tohomon/sremilia/frames.asm"
CFlandreFrames:     INCLUDE "gfx/tohomon/cflandre/frames.asm"
FlandreFrames:     INCLUDE "gfx/tohomon/flandre/frames.asm"
AFlandreFrames:    INCLUDE "gfx/tohomon/aflandre/frames.asm"
CLettyFrames:    INCLUDE "gfx/tohomon/cletty/frames.asm"
LettyFrames:     INCLUDE "gfx/tohomon/letty/frames.asm"
DLettyFrames:    INCLUDE "gfx/tohomon/dletty/frames.asm"
ChenFrames:    INCLUDE "gfx/tohomon/chen/frames.asm"
HChenFrames:       INCLUDE "gfx/tohomon/hchen/frames.asm"
CLilyWhiteFrames: INCLUDE "gfx/tohomon/clilywhite/frames.asm"
LilyWhiteFrames:     INCLUDE "gfx/tohomon/lilywhite/frames.asm"
DLilyWhiteFrames:     INCLUDE "gfx/tohomon/dlilywhite/frames.asm"
CLyricaFrames:     INCLUDE "gfx/tohomon/clyrica/frames.asm"
LyricaFrames:      INCLUDE "gfx/tohomon/lyrica/frames.asm"
TLyricaFrames:      INCLUDE "gfx/tohomon/tlyrica/frames.asm"
CMerlinFrames:   INCLUDE "gfx/tohomon/cmerlin/frames.asm"
MerlinFrames:    INCLUDE "gfx/tohomon/merlin/frames.asm"
SMerlinFrames:    INCLUDE "gfx/tohomon/smerlin/frames.asm"
CLunasaFrames:    INCLUDE "gfx/tohomon/clunasa/frames.asm"
LunasaFrames:    INCLUDE "gfx/tohomon/lunasa/frames.asm"
ALunasaFrames:    INCLUDE "gfx/tohomon/alunasa/frames.asm"
CYuyukoFrames:     INCLUDE "gfx/tohomon/cyuyuko/frames.asm"
YuyukoFrames:   INCLUDE "gfx/tohomon/yuyuko/frames.asm"
AYuyukoFrames: INCLUDE "gfx/tohomon/ayuyuko/frames.asm"
CRanFrames:    INCLUDE "gfx/tohomon/cran/frames.asm"
YukariFrames:    INCLUDE "gfx/tohomon/yukari/frames.asm"
TYukariFrames:  INCLUDE "gfx/tohomon/tyukari/frames.asm"
CSuikaFrames:  INCLUDE "gfx/tohomon/csuika/frames.asm"
TSuikaFrames:        INCLUDE "gfx/tohomon/tsuika/frames.asm"

KikuriJohtoFrames:  INCLUDE "gfx/tohomon/kikuri_johto/frames.asm"
KikuriKantoFrames:  INCLUDE "gfx/tohomon/kikuri_kanto/frames.asm"
KikuriKogaFrames:   INCLUDE "gfx/tohomon/kikuri_koga/frames.asm"
KikuriAgathaFrames: INCLUDE "gfx/tohomon/kikuri_agatha/frames.asm"
KikuriArianaFrames: INCLUDE "gfx/tohomon/kikuri_ariana/frames.asm"

LilyBlackFrames:     INCLUDE "gfx/tohomon/lilyblack/frames.asm"
LilyBlackSkellyFrames:    INCLUDE "gfx/tohomon/lilyblack_skelly/frames.asm"
LilyBlackCalico1Frames:   INCLUDE "gfx/tohomon/lilyblack_calico1/frames.asm"
LilyBlackCalico2Frames:   INCLUDE "gfx/tohomon/lilyblack_calico2/frames.asm"
LilyBlackCalico3Frames:   INCLUDE "gfx/tohomon/lilyblack_calico3/frames.asm"
LilyBlackTwoToneFrames:   INCLUDE "gfx/tohomon/lilyblack_twotone/frames.asm"
LilyBlackOrcaFrames:      INCLUDE "gfx/tohomon/lilyblack_orca/frames.asm"
LilyBlackDapplesFrames:   INCLUDE "gfx/tohomon/lilyblack_dapples/frames.asm"
LilyBlackTigerFrames:     INCLUDE "gfx/tohomon/lilyblack_tiger/frames.asm"
LilyBlackZebraFrames:     INCLUDE "gfx/tohomon/lilyblack_zebra/frames.asm"
LilyBlackStripeFrames:    INCLUDE "gfx/tohomon/lilyblack_stripe/frames.asm"
LilyBlackBubblesFrames:   INCLUDE "gfx/tohomon/lilyblack_bubbles/frames.asm"
LilyBlackDiamondsFrames:  INCLUDE "gfx/tohomon/lilyblack_diamonds/frames.asm"
LilyBlackPatchesFrames:   INCLUDE "gfx/tohomon/lilyblack_patches/frames.asm"
LilyBlackForehead1Frames: INCLUDE "gfx/tohomon/lilyblack_forehead1/frames.asm"
LilyBlackMask1Frames:     INCLUDE "gfx/tohomon/lilyblack_mask1/frames.asm"
LilyBlackForehead2Frames: INCLUDE "gfx/tohomon/lilyblack_forehead2/frames.asm"
LilyBlackMask2Frames:     INCLUDE "gfx/tohomon/lilyblack_mask2/frames.asm"
LilyBlackSaucyFrames:     INCLUDE "gfx/tohomon/lilyblack_saucy/frames.asm"
LilyBlackRaindropFrames:  INCLUDE "gfx/tohomon/lilyblack_raindrop/frames.asm"

SLilyBlackFrames: INCLUDE "gfx/tohomon/slilyblack/frames.asm"
SLilyBlackRedFrames:   INCLUDE "gfx/tohomon/slilyblack_red/frames.asm"

SuikaFrames:   INCLUDE "gfx/tohomon/suika/frames.asm"
SuikaArmoredFrames: INCLUDE "gfx/tohomon/suika_armored/frames.asm"

CElisFrames:  INCLUDE "gfx/tohomon/celis/frames.asm"

CSarielFrames:  INCLUDE "gfx/tohomon/csariel/frames.asm"

SarielFrames:  INCLUDE "gfx/tohomon/sariel/frames.asm"

CEllenFrames:  INCLUDE "gfx/tohomon/cellen/frames.asm"

CChiyuriFrames:  INCLUDE "gfx/tohomon/cchiyuri/frames.asm"

ChiyuriFrames:  INCLUDE "gfx/tohomon/chiyuri/frames.asm"

CYumemiFrames:  INCLUDE "gfx/tohomon/cyumemi/frames.asm"

CSaraFrames:  INCLUDE "gfx/tohomon/csara/frames.asm"

SaraFrames:  INCLUDE "gfx/tohomon/sara/frames.asm"

CYumekoFrames:  INCLUDE "gfx/tohomon/cyumeko/frames.asm"

SCirnoFrames:  INCLUDE "gfx/tohomon/scirno/frames.asm"

MeilingFrames:  INCLUDE "gfx/tohomon/meiling/frames.asm"

CLuizeFrames:    INCLUDE "gfx/tohomon/cluize/frames.asm"

LuizeFrames:    INCLUDE "gfx/tohomon/luize/frames.asm"

DLuizeFrames:   INCLUDE "gfx/tohomon/dluize/frames.asm"

CAliceFrames:    INCLUDE "gfx/tohomon/calice/frames.asm"

CMaiFrames:    INCLUDE "gfx/tohomon/cmai/frames.asm"

CPatchouliFrames:    INCLUDE "gfx/tohomon/cpatchouli/frames.asm"

CChenFrames:    INCLUDE "gfx/tohomon/cchen/frames.asm"

RanFrames:    INCLUDE "gfx/tohomon/ran/frames.asm"

TRanFrames:    INCLUDE "gfx/tohomon/tran/frames.asm"

CYukariFrames:    INCLUDE "gfx/tohomon/cyukari/frames.asm"

CKurumiFrames:   INCLUDE "gfx/tohomon/ckurumi/frames.asm"

DDaichanFrames:   INCLUDE "gfx/tohomon/ddaichan/frames.asm"

CCirnoFrames:   INCLUDE "gfx/tohomon/ccirno/frames.asm"

CLilyBlackFrames:        INCLUDE "gfx/tohomon/clilyblack/frames.asm"