PicAnimations:
CReimuAnimation:  INCLUDE "gfx/pokemon/creimu/anim.asm"
ReimuAnimation:    INCLUDE "gfx/pokemon/reimu/anim.asm"
TReimuAnimation:   INCLUDE "gfx/pokemon/treimu/anim.asm"
CMarisaAnimation: INCLUDE "gfx/pokemon/cmarisa/anim.asm"
MarisaAnimation: INCLUDE "gfx/pokemon/marisa/anim.asm"
AMarisaAnimation:  INCLUDE "gfx/pokemon/amarisa/anim.asm"
CSakuyaAnimation:   INCLUDE "gfx/pokemon/csakuya/anim.asm"
SakuyaAnimation:  INCLUDE "gfx/pokemon/sakuya/anim.asm"
HSakuyaAnimation:  INCLUDE "gfx/pokemon/hsakuya/anim.asm"
CGyokuAnimation:   INCLUDE "gfx/pokemon/cgyoku/anim.asm"
MGyokuAnimation:    INCLUDE "gfx/pokemon/mgyoku/anim.asm"
FGyokuAnimation: INCLUDE "gfx/pokemon/fgyoku/anim.asm"
OGyokuAnimation:     INCLUDE "gfx/pokemon/ogyoku/anim.asm"
CMaganAnimation:     INCLUDE "gfx/pokemon/cmagan/anim.asm"
MaganAnimation:   INCLUDE "gfx/pokemon/magan/anim.asm"
CMimaAnimation:  INCLUDE "gfx/pokemon/cmima/anim.asm"
MimaAnimation:    INCLUDE "gfx/pokemon/mima/anim.asm"
ElisAnimation:    INCLUDE "gfx/pokemon/elis/anim.asm"
CKikuriAnimation:      INCLUDE "gfx/pokemon/ckikuri/anim.asm"
CKongaraAnimation:   INCLUDE "gfx/pokemon/ckongara/anim.asm"
KongaraAnimation:   INCLUDE "gfx/pokemon/kongara/anim.asm"
CRikaAnimation:   INCLUDE "gfx/pokemon/crika/anim.asm"
RikaAnimation:   INCLUDE "gfx/pokemon/rika/anim.asm"
ARikaAnimation:   INCLUDE "gfx/pokemon/arika/anim.asm"
CMeiraAnimation:   INCLUDE "gfx/pokemon/cmeira/anim.asm"
MeiraAnimation:   INCLUDE "gfx/pokemon/meira/anim.asm"
EllenAnimation: INCLUDE "gfx/pokemon/ellen/anim.asm"
CKotohimeAnimation:      INCLUDE "gfx/pokemon/ckotohime/anim.asm"
KotohimeAnimation:     INCLUDE "gfx/pokemon/kotohime/anim.asm"
CKanaAnimation:      INCLUDE "gfx/pokemon/ckana/anim.asm"
KanaAnimation:  INCLUDE "gfx/pokemon/kana/anim.asm"
CRikakoAnimation:   INCLUDE "gfx/pokemon/crikako/anim.asm"
RikakoAnimation:    INCLUDE "gfx/pokemon/rikako/anim.asm"
YumemiAnimation:    INCLUDE "gfx/pokemon/yumemi/anim.asm"
COrangeAnimation:     INCLUDE "gfx/pokemon/corange/anim.asm"
OrangeAnimation:   INCLUDE "gfx/pokemon/orange/anim.asm"
KurumiAnimation:    INCLUDE "gfx/pokemon/kurumi/anim.asm"
CEllyAnimation:  INCLUDE "gfx/pokemon/celly/anim.asm"
EllyAnimation:       INCLUDE "gfx/pokemon/elly/anim.asm"
CYukaAnimation:   INCLUDE "gfx/pokemon/cyuka/anim.asm"
YukaAnimation:     INCLUDE "gfx/pokemon/yuka/anim.asm"
AYukaAnimation:    INCLUDE "gfx/pokemon/ayuka/anim.asm"
CMugetsuAnimation:    INCLUDE "gfx/pokemon/cmugetsu/anim.asm"
MugetsuAnimation: INCLUDE "gfx/pokemon/mugetsu/anim.asm"
CGengetsuAnimation: INCLUDE "gfx/pokemon/cgengetsu/anim.asm"
GengetsuAnimation:  INCLUDE "gfx/pokemon/gengetsu/anim.asm"
AliceAnimation:  INCLUDE "gfx/pokemon/alice/anim.asm"
AAliceAnimation:   INCLUDE "gfx/pokemon/aalice/anim.asm"
MaiAnimation:      INCLUDE "gfx/pokemon/mai/anim.asm"
CYukiAnimation:       INCLUDE "gfx/pokemon/cyuki/anim.asm"
YukiAnimation:    INCLUDE "gfx/pokemon/yuki/anim.asm"
YumekoAnimation:   INCLUDE "gfx/pokemon/yumeko/anim.asm"
CShinkiAnimation:     INCLUDE "gfx/pokemon/cshinki/anim.asm"
ShinkiAnimation:    INCLUDE "gfx/pokemon/shinki/anim.asm"
CRumiaAnimation:       INCLUDE "gfx/pokemon/crumia/anim.asm"
RumiaAnimation:    INCLUDE "gfx/pokemon/rumia/anim.asm"
ARumiaAnimation:      INCLUDE "gfx/pokemon/arumia/anim.asm"
CDaichanAnimation:     INCLUDE "gfx/pokemon/cdaichan/anim.asm"
DaichanAnimation:    INCLUDE "gfx/pokemon/daichan/anim.asm"
CirnoAnimation:  INCLUDE "gfx/pokemon/cirno/anim.asm"
CMeilingAnimation:     INCLUDE "gfx/pokemon/cmeiling/anim.asm"
AMeilingAnimation:  INCLUDE "gfx/pokemon/ameiling/anim.asm"
CKoakumaAnimation: INCLUDE "gfx/pokemon/ckoakuma/anim.asm"
KoakumaAnimation:  INCLUDE "gfx/pokemon/koakuma/anim.asm"
HKoakumaAnimation:    INCLUDE "gfx/pokemon/hkoakuma/anim.asm"
PatchouliAnimation:    INCLUDE "gfx/pokemon/patchouli/anim.asm"
TPatchouliAnimation:     INCLUDE "gfx/pokemon/tpatchouli/anim.asm"
CRemiliaAnimation:    INCLUDE "gfx/pokemon/cremilia/anim.asm"
RemiliaAnimation:    INCLUDE "gfx/pokemon/remilia/anim.asm"
SRemiliaAnimation: INCLUDE "gfx/pokemon/sremilia/anim.asm"
CFlandreAnimation:     INCLUDE "gfx/pokemon/cflandre/anim.asm"
FlandreAnimation:     INCLUDE "gfx/pokemon/flandre/anim.asm"
AFlandreAnimation:    INCLUDE "gfx/pokemon/aflandre/anim.asm"
CLettyAnimation:    INCLUDE "gfx/pokemon/cletty/anim.asm"
LettyAnimation:     INCLUDE "gfx/pokemon/letty/anim.asm"
DLettyAnimation:    INCLUDE "gfx/pokemon/dletty/anim.asm"
ChenAnimation:    INCLUDE "gfx/pokemon/chen/anim.asm"
HChenAnimation:       INCLUDE "gfx/pokemon/hchen/anim.asm"
CLilyWhiteAnimation: INCLUDE "gfx/pokemon/clilywhite/anim.asm"
LilyWhiteAnimation:     INCLUDE "gfx/pokemon/lilywhite/anim.asm"
DLilyWhiteAnimation:     INCLUDE "gfx/pokemon/dlilywhite/anim.asm"
CLyricaAnimation:     INCLUDE "gfx/pokemon/clyrica/anim.asm"
LyricaAnimation:      INCLUDE "gfx/pokemon/lyrica/anim.asm"
TLyricaAnimation:      INCLUDE "gfx/pokemon/tlyrica/anim.asm"
CMerlinAnimation:   INCLUDE "gfx/pokemon/cmerlin/anim.asm"
MerlinAnimation:    INCLUDE "gfx/pokemon/merlin/anim.asm"
SMerlinAnimation:    INCLUDE "gfx/pokemon/smerlin/anim.asm"
CLunasaAnimation:    INCLUDE "gfx/pokemon/clunasa/anim.asm"
LunasaAnimation:    INCLUDE "gfx/pokemon/lunasa/anim.asm"
ALunasaAnimation:    INCLUDE "gfx/pokemon/alunasa/anim.asm"
CYuyukoAnimation:     INCLUDE "gfx/pokemon/cyuyuko/anim.asm"
YuyukoAnimation:   INCLUDE "gfx/pokemon/yuyuko/anim.asm"
AYuyukoAnimation: INCLUDE "gfx/pokemon/ayuyuko/anim.asm"
CRanAnimation:    INCLUDE "gfx/pokemon/cran/anim.asm"
YukariAnimation:    INCLUDE "gfx/pokemon/yukari/anim.asm"
TYukariAnimation:  INCLUDE "gfx/pokemon/tyukari/anim.asm"
CSuikaAnimation:  INCLUDE "gfx/pokemon/csuika/anim.asm"
TSuikaAnimation:        INCLUDE "gfx/pokemon/tsuika/anim.asm"
CYoumuAnimation:  INCLUDE "gfx/pokemon/cyoumu/anim.asm"
YoumuAnimation:    INCLUDE "gfx/pokemon/youmu/anim.asm"
SYoumuAnimation:   INCLUDE "gfx/pokemon/syoumu/anim.asm"
CReisenAnimation:  INCLUDE "gfx/pokemon/creisen/anim.asm"
ReisenAnimation:    INCLUDE "gfx/pokemon/reisen/anim.asm"
CSanaeAnimation:   INCLUDE "gfx/pokemon/csanae/anim.asm"
SanaeAnimation:   INCLUDE "gfx/pokemon/sanae/anim.asm"
DSanaeAnimation: INCLUDE "gfx/pokemon/dsanae/anim.asm"
SentretAnimation:    INCLUDE "gfx/pokemon/sentret/anim.asm"
FurretAnimation:     INCLUDE "gfx/pokemon/furret/anim.asm"
HoothootAnimation:   INCLUDE "gfx/pokemon/hoothoot/anim.asm"
NoctowlAnimation:    INCLUDE "gfx/pokemon/noctowl/anim.asm"
LedybaAnimation:     INCLUDE "gfx/pokemon/ledyba/anim.asm"
LedianAnimation:     INCLUDE "gfx/pokemon/ledian/anim.asm"
SpinarakAnimation:   INCLUDE "gfx/pokemon/spinarak/anim.asm"
AriadosAnimation:    INCLUDE "gfx/pokemon/ariados/anim.asm"
CrobatAnimation:     INCLUDE "gfx/pokemon/crobat/anim.asm"
ChinchouAnimation:   INCLUDE "gfx/pokemon/chinchou/anim.asm"
LanturnAnimation:    INCLUDE "gfx/pokemon/lanturn/anim.asm"
CleffaAnimation:     INCLUDE "gfx/pokemon/cleffa/anim.asm"
IgglybuffAnimation:  INCLUDE "gfx/pokemon/igglybuff/anim.asm"
TogepiAnimation:     INCLUDE "gfx/pokemon/togepi/anim.asm"
TogeticAnimation:    INCLUDE "gfx/pokemon/togetic/anim.asm"
NatuAnimation:       INCLUDE "gfx/pokemon/natu/anim.asm"
XatuAnimation:       INCLUDE "gfx/pokemon/xatu/anim.asm"
MareepAnimation:     INCLUDE "gfx/pokemon/mareep/anim.asm"
FlaaffyAnimation:    INCLUDE "gfx/pokemon/flaaffy/anim.asm"
AmpharosAnimation:   INCLUDE "gfx/pokemon/ampharos/anim.asm"
BellossomAnimation:  INCLUDE "gfx/pokemon/bellossom/anim.asm"
SudowoodoAnimation:  INCLUDE "gfx/pokemon/sudowoodo/anim.asm"
MarillAnimation:     INCLUDE "gfx/pokemon/marill/anim.asm"
AzumarillAnimation:  INCLUDE "gfx/pokemon/azumarill/anim.asm"
PolitoedAnimation:   INCLUDE "gfx/pokemon/politoed/anim.asm"
HoppipAnimation:     INCLUDE "gfx/pokemon/hoppip/anim.asm"
SkiploomAnimation:   INCLUDE "gfx/pokemon/skiploom/anim.asm"
JumpluffAnimation:   INCLUDE "gfx/pokemon/jumpluff/anim.asm"
AipomAnimation:      INCLUDE "gfx/pokemon/aipom/anim.asm"
SunkernAnimation:    INCLUDE "gfx/pokemon/sunkern/anim.asm"
SunfloraAnimation:   INCLUDE "gfx/pokemon/sunflora/anim.asm"
YanmaAnimation:      INCLUDE "gfx/pokemon/yanma/anim.asm"
QuagsireAnimation:   INCLUDE "gfx/pokemon/quagsire/anim.asm"
EspeonAnimation:     INCLUDE "gfx/pokemon/espeon/anim.asm"
UmbreonAnimation:    INCLUDE "gfx/pokemon/umbreon/anim.asm"
MurkrowAnimation:    INCLUDE "gfx/pokemon/murkrow/anim.asm"
MisdreavusAnimation: INCLUDE "gfx/pokemon/misdreavus/anim.asm"
WobbuffetAnimation:  INCLUDE "gfx/pokemon/wobbuffet/anim.asm"
GirafarigAnimation:  INCLUDE "gfx/pokemon/girafarig/anim.asm"
PinecoAnimation:     INCLUDE "gfx/pokemon/pineco/anim.asm"
ForretressAnimation: INCLUDE "gfx/pokemon/forretress/anim.asm"
DunsparceAnimation:  INCLUDE "gfx/pokemon/dunsparce/anim.asm"
GligarAnimation:     INCLUDE "gfx/pokemon/gligar/anim.asm"
SteelixAnimation:    INCLUDE "gfx/pokemon/steelix/anim.asm"
SnubbullAnimation:   INCLUDE "gfx/pokemon/snubbull/anim.asm"
GranbullAnimation:   INCLUDE "gfx/pokemon/granbull/anim.asm"
ScizorAnimation:     INCLUDE "gfx/pokemon/scizor/anim.asm"
ShuckleAnimation:    INCLUDE "gfx/pokemon/shuckle/anim.asm"
HeracrossAnimation:  INCLUDE "gfx/pokemon/heracross/anim.asm"
TeddiursaAnimation:  INCLUDE "gfx/pokemon/teddiursa/anim.asm"
UrsaringAnimation:   INCLUDE "gfx/pokemon/ursaring/anim.asm"
SlugmaAnimation:     INCLUDE "gfx/pokemon/slugma/anim.asm"
MagcargoAnimation:   INCLUDE "gfx/pokemon/magcargo/anim.asm"
SwinubAnimation:     INCLUDE "gfx/pokemon/swinub/anim.asm"
PiloswineAnimation:  INCLUDE "gfx/pokemon/piloswine/anim.asm"
RemoraidAnimation:   INCLUDE "gfx/pokemon/remoraid/anim.asm"
OctilleryAnimation:  INCLUDE "gfx/pokemon/octillery/anim.asm"
DelibirdAnimation:   INCLUDE "gfx/pokemon/delibird/anim.asm"
MantineAnimation:    INCLUDE "gfx/pokemon/mantine/anim.asm"
SkarmoryAnimation:   INCLUDE "gfx/pokemon/skarmory/anim.asm"
HoundourAnimation:   INCLUDE "gfx/pokemon/houndour/anim.asm"
HoundoomAnimation:   INCLUDE "gfx/pokemon/houndoom/anim.asm"
KingdraAnimation:    INCLUDE "gfx/pokemon/kingdra/anim.asm"
PhanpyAnimation:     INCLUDE "gfx/pokemon/phanpy/anim.asm"
DonphanAnimation:    INCLUDE "gfx/pokemon/donphan/anim.asm"
CLunasa2Animation:   INCLUDE "gfx/pokemon/clunasa2/anim.asm"
StantlerAnimation:   INCLUDE "gfx/pokemon/stantler/anim.asm"
SmeargleAnimation:   INCLUDE "gfx/pokemon/smeargle/anim.asm"
TyrogueAnimation:    INCLUDE "gfx/pokemon/tyrogue/anim.asm"
HitmontopAnimation:  INCLUDE "gfx/pokemon/hitmontop/anim.asm"
SmoochumAnimation:   INCLUDE "gfx/pokemon/smoochum/anim.asm"
ElekidAnimation:     INCLUDE "gfx/pokemon/elekid/anim.asm"
MagbyAnimation:      INCLUDE "gfx/pokemon/magby/anim.asm"
MiltankAnimation:    INCLUDE "gfx/pokemon/miltank/anim.asm"
BlisseyAnimation:    INCLUDE "gfx/pokemon/blissey/anim.asm"
RaikouAnimation:     INCLUDE "gfx/pokemon/raikou/anim.asm"
EnteiAnimation:      INCLUDE "gfx/pokemon/entei/anim.asm"
SuicuneAnimation:    INCLUDE "gfx/pokemon/suicune/anim.asm"
LarvitarAnimation:   INCLUDE "gfx/pokemon/larvitar/anim.asm"
PupitarAnimation:    INCLUDE "gfx/pokemon/pupitar/anim.asm"
TyranitarAnimation:  INCLUDE "gfx/pokemon/tyranitar/anim.asm"
LugiaAnimation:      INCLUDE "gfx/pokemon/lugia/anim.asm"
HoOhAnimation:       INCLUDE "gfx/pokemon/ho_oh/anim.asm"
CelebiAnimation:     INCLUDE "gfx/pokemon/celebi/anim.asm"
AzurillAnimation:    INCLUDE "gfx/pokemon/azurill/anim.asm"
WynautAnimation:     INCLUDE "gfx/pokemon/wynaut/anim.asm"
AmbipomAnimation:    INCLUDE "gfx/pokemon/ambipom/anim.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim.asm"
HonchkrowAnimation:  INCLUDE "gfx/pokemon/honchkrow/anim.asm"
BonslyAnimation:     INCLUDE "gfx/pokemon/bonsly/anim.asm"
MimeJrAnimation:     INCLUDE "gfx/pokemon/mime_jr_/anim.asm"
HappinyAnimation:    INCLUDE "gfx/pokemon/happiny/anim.asm"
MunchlaxAnimation:   INCLUDE "gfx/pokemon/munchlax/anim.asm"
MantykeAnimation:    INCLUDE "gfx/pokemon/mantyke/anim.asm"
WeavileAnimation:    INCLUDE "gfx/pokemon/weavile/anim.asm"
MagnezoneAnimation:  INCLUDE "gfx/pokemon/magnezone/anim.asm"
LickilickyAnimation: INCLUDE "gfx/pokemon/lickilicky/anim.asm"
RhyperiorAnimation:  INCLUDE "gfx/pokemon/rhyperior/anim.asm"
TangrowthAnimation:  INCLUDE "gfx/pokemon/tangrowth/anim.asm"
ElectivireAnimation: INCLUDE "gfx/pokemon/electivire/anim.asm"
MagmortarAnimation:  INCLUDE "gfx/pokemon/magmortar/anim.asm"
TogekissAnimation:   INCLUDE "gfx/pokemon/togekiss/anim.asm"
YanmegaAnimation:    INCLUDE "gfx/pokemon/yanmega/anim.asm"
LeafeonAnimation:    INCLUDE "gfx/pokemon/leafeon/anim.asm"
GlaceonAnimation:    INCLUDE "gfx/pokemon/glaceon/anim.asm"
GliscorAnimation:    INCLUDE "gfx/pokemon/gliscor/anim.asm"
MamoswineAnimation:  INCLUDE "gfx/pokemon/mamoswine/anim.asm"
CLunasaZAnimation:   INCLUDE "gfx/pokemon/clunasa_z/anim.asm"
SylveonAnimation:    INCLUDE "gfx/pokemon/sylveon/anim.asm"
PerrserkerAnimation: INCLUDE "gfx/pokemon/perrserker/anim.asm"
CursolaAnimation:    INCLUDE "gfx/pokemon/cursola/anim.asm"
SirfetchDAnimation:  INCLUDE "gfx/pokemon/sirfetch_d/anim.asm"
MrRimeAnimation:     INCLUDE "gfx/pokemon/mr__rime/anim.asm"
WyrdeerAnimation:    INCLUDE "gfx/pokemon/wyrdeer/anim.asm"
KleavorAnimation:    INCLUDE "gfx/pokemon/kleavor/anim.asm"
UrsalunaAnimation:   INCLUDE "gfx/pokemon/ursaluna/anim.asm"
SneaslerAnimation:   INCLUDE "gfx/pokemon/sneasler/anim.asm"
OverqwilAnimation:   INCLUDE "gfx/pokemon/overqwil/anim.asm"
FarigirafAnimation:  INCLUDE "gfx/pokemon/farigiraf/anim.asm"
ClodsireAnimation:   INCLUDE "gfx/pokemon/clodsire/anim.asm"
AnnihilapeAnimation: INCLUDE "gfx/pokemon/annihilape/anim.asm"

EggAnimation:        INCLUDE "gfx/pokemon/egg/anim.asm"

UnownAAnimation: INCLUDE "gfx/pokemon/unown_a/anim.asm"
UnownBAnimation: INCLUDE "gfx/pokemon/unown_b/anim.asm"
UnownCAnimation: INCLUDE "gfx/pokemon/unown_c/anim.asm"
UnownDAnimation: INCLUDE "gfx/pokemon/unown_d/anim.asm"
UnownEAnimation: INCLUDE "gfx/pokemon/unown_e/anim.asm"
UnownFAnimation: INCLUDE "gfx/pokemon/unown_f/anim.asm"
UnownGAnimation: INCLUDE "gfx/pokemon/unown_g/anim.asm"
UnownHAnimation: INCLUDE "gfx/pokemon/unown_h/anim.asm"
UnownIAnimation: INCLUDE "gfx/pokemon/unown_i/anim.asm"
UnownJAnimation: INCLUDE "gfx/pokemon/unown_j/anim.asm"
UnownKAnimation: INCLUDE "gfx/pokemon/unown_k/anim.asm"
UnownLAnimation: INCLUDE "gfx/pokemon/unown_l/anim.asm"
UnownMAnimation: INCLUDE "gfx/pokemon/unown_m/anim.asm"
UnownNAnimation: INCLUDE "gfx/pokemon/unown_n/anim.asm"
UnownOAnimation: INCLUDE "gfx/pokemon/unown_o/anim.asm"
UnownPAnimation: INCLUDE "gfx/pokemon/unown_p/anim.asm"
UnownQAnimation: INCLUDE "gfx/pokemon/unown_q/anim.asm"
UnownRAnimation: INCLUDE "gfx/pokemon/unown_r/anim.asm"
UnownSAnimation: INCLUDE "gfx/pokemon/unown_s/anim.asm"
UnownTAnimation: INCLUDE "gfx/pokemon/unown_t/anim.asm"
UnownUAnimation: INCLUDE "gfx/pokemon/unown_u/anim.asm"
UnownVAnimation: INCLUDE "gfx/pokemon/unown_v/anim.asm"
UnownWAnimation: INCLUDE "gfx/pokemon/unown_w/anim.asm"
UnownXAnimation: INCLUDE "gfx/pokemon/unown_x/anim.asm"
UnownYAnimation: INCLUDE "gfx/pokemon/unown_y/anim.asm"
UnownZAnimation: INCLUDE "gfx/pokemon/unown_z/anim.asm"
UnownExclamationAnimation: INCLUDE "gfx/pokemon/unown_exclamation/anim.asm"
UnownQuestionAnimation:    INCLUDE "gfx/pokemon/unown_question/anim.asm"

PichuAnimation: INCLUDE "gfx/pokemon/pichu/anim.asm"
PichuSpikyAnimation: INCLUDE "gfx/pokemon/pichu_spiky/anim.asm"

KikuriJohtoAnimation:  INCLUDE "gfx/pokemon/kikuri_johto/anim.asm"
KikuriKantoAnimation:  INCLUDE "gfx/pokemon/kikuri_kanto/anim.asm"
KikuriKogaAnimation:   INCLUDE "gfx/pokemon/kikuri_koga/anim.asm"
KikuriAgathaAnimation: INCLUDE "gfx/pokemon/kikuri_agatha/anim.asm"
KikuriArianaAnimation: INCLUDE "gfx/pokemon/kikuri_ariana/anim.asm"

LilyBlackAnimation:
LilyBlackSkellyAnimation:
LilyBlackCalico1Animation:
LilyBlackCalico2Animation:
LilyBlackCalico3Animation:
LilyBlackTwoToneAnimation:
LilyBlackOrcaAnimation:
LilyBlackDapplesAnimation:
LilyBlackTigerAnimation:
LilyBlackZebraAnimation:
LilyBlackStripeAnimation:
LilyBlackBubblesAnimation:
LilyBlackDiamondsAnimation:
LilyBlackPatchesAnimation:
LilyBlackForehead1Animation:
LilyBlackMask1Animation:
LilyBlackForehead2Animation:
LilyBlackMask2Animation:
LilyBlackSaucyAnimation:
LilyBlackRaindropAnimation: INCLUDE "gfx/pokemon/lilyblack/anim.asm"

DudunsparceTwoSegmentAnimation:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim.asm"
DudunsparceThreeSegmentAnimation: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim.asm"

SLilyBlackAnimation: INCLUDE "gfx/pokemon/slilyblack/anim.asm"
SLilyBlackRedAnimation:   INCLUDE "gfx/pokemon/slilyblack_red/anim.asm"

SuikaAnimation:   INCLUDE "gfx/pokemon/suika/anim.asm"
SuikaArmoredAnimation: INCLUDE "gfx/pokemon/suika_armored/anim.asm"

CElisAnimation:  INCLUDE "gfx/pokemon/celis/anim.asm"

CSarielAnimation:  INCLUDE "gfx/pokemon/csariel/anim.asm"

SarielAnimation:  INCLUDE "gfx/pokemon/sariel/anim.asm"

CEllenAnimation:  INCLUDE "gfx/pokemon/cellen/anim.asm"

CChiyuriAnimation:  INCLUDE "gfx/pokemon/cchiyuri/anim.asm"

ChiyuriAnimation:  INCLUDE "gfx/pokemon/chiyuri/anim.asm"

CYumemiAnimation:  INCLUDE "gfx/pokemon/cyumemi/anim.asm"

CSaraAnimation:  INCLUDE "gfx/pokemon/csara/anim.asm"

SaraAnimation:  INCLUDE "gfx/pokemon/sara/anim.asm"

CYumekoAnimation:  INCLUDE "gfx/pokemon/cyumeko/anim.asm"

SCirnoAnimation:  INCLUDE "gfx/pokemon/scirno/anim.asm"

MeilingAnimation:  INCLUDE "gfx/pokemon/meiling/anim.asm"

CLuizeAnimation:    INCLUDE "gfx/pokemon/cluize/anim.asm"

LuizeAnimation:    INCLUDE "gfx/pokemon/luize/anim.asm"

DLuizeAnimation:    INCLUDE "gfx/pokemon/dluize/anim.asm"

CAliceAnimation:    INCLUDE "gfx/pokemon/calice/anim.asm"

CMaiAnimation:    INCLUDE "gfx/pokemon/cmai/anim.asm"

CPatchouliAnimation:    INCLUDE "gfx/pokemon/cpatchouli/anim.asm"

CChenAnimation:    INCLUDE "gfx/pokemon/cchen/anim.asm"

RanAnimation:    INCLUDE "gfx/pokemon/ran/anim.asm"

TRanAnimation:    INCLUDE "gfx/pokemon/tran/anim.asm"

CYukariAnimation:    INCLUDE "gfx/pokemon/cyukari/anim.asm"

SlowkingAnimation:    INCLUDE "gfx/pokemon/slowking/anim.asm"

CorsolaAnimation:    INCLUDE "gfx/pokemon/corsola/anim.asm"

CKurumiAnimation:   INCLUDE "gfx/pokemon/ckurumi/anim.asm"

DDaichanAnimation:   INCLUDE "gfx/pokemon/ddaichan/anim.asm"

CCirnoAnimation:   INCLUDE "gfx/pokemon/ccirno/anim.asm"

TReisenAnimation:   INCLUDE "gfx/pokemon/treisen/anim.asm"

QwilfishAnimation:   INCLUDE "gfx/pokemon/qwilfish/anim.asm"

SneaselAnimation:   INCLUDE "gfx/pokemon/sneasel/anim.asm"

WooperAnimation:   INCLUDE "gfx/pokemon/wooper/anim.asm"

CLilyBlackAnimation:        INCLUDE "gfx/pokemon/clilyblack/anim.asm"
