PicAnimations:
CReimuAnimation:  INCLUDE "gfx/pokemon/creimu/anim.asm"
ReimuAnimation:    INCLUDE "gfx/pokemon/reimu/anim.asm"
EReimuAnimation:   INCLUDE "gfx/pokemon/ereimu/anim.asm"
CMarisaAnimation: INCLUDE "gfx/pokemon/cmarisa/anim.asm"
MarisaAnimation: INCLUDE "gfx/pokemon/marisa/anim.asm"
EMarisaAnimation:  INCLUDE "gfx/pokemon/emarisa/anim.asm"
CSakuyaAnimation:   INCLUDE "gfx/pokemon/csakuya/anim.asm"
SakuyaAnimation:  INCLUDE "gfx/pokemon/sakuya/anim.asm"
ESakuyaAnimation:  INCLUDE "gfx/pokemon/esakuya/anim.asm"
CGyokuAnimation:   INCLUDE "gfx/pokemon/cgyoku/anim.asm"
MGyokuAnimation:    INCLUDE "gfx/pokemon/mgyoku/anim.asm"
FGyokuAnimation: INCLUDE "gfx/pokemon/fgyoku/anim.asm"
OGyokuAnimation:     INCLUDE "gfx/pokemon/ogyoku/anim.asm"
CMaganAnimation:     INCLUDE "gfx/pokemon/cmagan/anim.asm"
MaganAnimation:   INCLUDE "gfx/pokemon/magan/anim.asm"
EMaganAnimation:     INCLUDE "gfx/pokemon/emagan/anim.asm"
CMimaAnimation:  INCLUDE "gfx/pokemon/cmima/anim.asm"
MimaAnimation:    INCLUDE "gfx/pokemon/mima/anim.asm"
ElisAnimation:    INCLUDE "gfx/pokemon/elis/anim.asm"
EElisAnimation:     INCLUDE "gfx/pokemon/eelis/anim.asm"
CKikuriAnimation:      INCLUDE "gfx/pokemon/ckikuri/anim.asm"
CKongaraAnimation:   INCLUDE "gfx/pokemon/ckongara/anim.asm"
KongaraAnimation:   INCLUDE "gfx/pokemon/kongara/anim.asm"
EKongaraAnimation:  INCLUDE "gfx/pokemon/ekongara/anim.asm"
CRikaAnimation:   INCLUDE "gfx/pokemon/crika/anim.asm"
RikaAnimation:   INCLUDE "gfx/pokemon/rika/anim.asm"
ERikaAnimation:   INCLUDE "gfx/pokemon/erika/anim.asm"
CMeiraAnimation:   INCLUDE "gfx/pokemon/cmeira/anim.asm"
MeiraAnimation:   INCLUDE "gfx/pokemon/meira/anim.asm"
EllenAnimation: INCLUDE "gfx/pokemon/ellen/anim.asm"
EEllenAnimation: INCLUDE "gfx/pokemon/eellen/anim.asm"
CKotohimeAnimation:      INCLUDE "gfx/pokemon/ckotohime/anim.asm"
KotohimeAnimation:     INCLUDE "gfx/pokemon/kotohime/anim.asm"
EKotohimeAnimation:     INCLUDE "gfx/pokemon/ekotohime/anim.asm"
CKanaAnimation:      INCLUDE "gfx/pokemon/ckana/anim.asm"
KanaAnimation:  INCLUDE "gfx/pokemon/kana/anim.asm"
EKanaAnimation:      INCLUDE "gfx/pokemon/ekana/anim.asm"
CRikakoAnimation:   INCLUDE "gfx/pokemon/crikako/anim.asm"
RikakoAnimation:    INCLUDE "gfx/pokemon/rikako/anim.asm"
ERikakoAnimation:   INCLUDE "gfx/pokemon/erikako/anim.asm"
YumemiAnimation:    INCLUDE "gfx/pokemon/yumemi/anim.asm"
EYumemiAnimation:    INCLUDE "gfx/pokemon/eyumemi/anim.asm"
COrangeAnimation:     INCLUDE "gfx/pokemon/corange/anim.asm"
OrangeAnimation:   INCLUDE "gfx/pokemon/orange/anim.asm"
KurumiAnimation:    INCLUDE "gfx/pokemon/kurumi/anim.asm"
EKurumiAnimation:  INCLUDE "gfx/pokemon/ekurumi/anim.asm"
CEllyAnimation:  INCLUDE "gfx/pokemon/celly/anim.asm"
EllyAnimation:       INCLUDE "gfx/pokemon/elly/anim.asm"
EEllyAnimation:    INCLUDE "gfx/pokemon/eelly/anim.asm"
CYukaAnimation:   INCLUDE "gfx/pokemon/cyuka/anim.asm"
YukaAnimation:     INCLUDE "gfx/pokemon/yuka/anim.asm"
EYukaAnimation:    INCLUDE "gfx/pokemon/eyuka/anim.asm"
CMugetsuAnimation:    INCLUDE "gfx/pokemon/cmugetsu/anim.asm"
MugetsuAnimation: INCLUDE "gfx/pokemon/mugetsu/anim.asm"
EMugetsuAnimation: INCLUDE "gfx/pokemon/emugetsu/anim.asm"
CGengetsuAnimation: INCLUDE "gfx/pokemon/cgengetsu/anim.asm"
GengetsuAnimation:  INCLUDE "gfx/pokemon/gengetsu/anim.asm"
EGengetsuAnimation: INCLUDE "gfx/pokemon/egengetsu/anim.asm"
AliceAnimation:  INCLUDE "gfx/pokemon/alice/anim.asm"
EAliceAnimation:   INCLUDE "gfx/pokemon/ealice/anim.asm"
MaiAnimation:      INCLUDE "gfx/pokemon/mai/anim.asm"
EMaiAnimation:     INCLUDE "gfx/pokemon/emai/anim.asm"
CYukiAnimation:       INCLUDE "gfx/pokemon/cyuki/anim.asm"
YukiAnimation:    INCLUDE "gfx/pokemon/yuki/anim.asm"
YumekoAnimation:   INCLUDE "gfx/pokemon/yumeko/anim.asm"
EYumekoAnimation:   INCLUDE "gfx/pokemon/eyumeko/anim.asm"
CShinkiAnimation:     INCLUDE "gfx/pokemon/cshinki/anim.asm"
ShinkiAnimation:    INCLUDE "gfx/pokemon/shinki/anim.asm"
EShinkiAnimation:     INCLUDE "gfx/pokemon/eshinki/anim.asm"
CRumiaAnimation:       INCLUDE "gfx/pokemon/crumia/anim.asm"
RumiaAnimation:    INCLUDE "gfx/pokemon/rumia/anim.asm"
ERumiaAnimation:      INCLUDE "gfx/pokemon/erumia/anim.asm"
CDaichanAnimation:     INCLUDE "gfx/pokemon/cdaichan/anim.asm"
DaichanAnimation:    INCLUDE "gfx/pokemon/daichan/anim.asm"
CirnoAnimation:  INCLUDE "gfx/pokemon/cirno/anim.asm"
CMeilingAnimation:     INCLUDE "gfx/pokemon/cmeiling/anim.asm"
EMeilingAnimation:  INCLUDE "gfx/pokemon/emeiling/anim.asm"
CKoakumaAnimation: INCLUDE "gfx/pokemon/ckoakuma/anim.asm"
KoakumaAnimation:  INCLUDE "gfx/pokemon/koakuma/anim.asm"
EKoakumaAnimation:    INCLUDE "gfx/pokemon/ekoakuma/anim.asm"
PatchouliAnimation:    INCLUDE "gfx/pokemon/patchouli/anim.asm"
EPatchouliAnimation:     INCLUDE "gfx/pokemon/epatchouli/anim.asm"
CRemiliaAnimation:    INCLUDE "gfx/pokemon/cremilia/anim.asm"
RemiliaAnimation:    INCLUDE "gfx/pokemon/remilia/anim.asm"
ERemiliaAnimation: INCLUDE "gfx/pokemon/eremilia/anim.asm"
CFlandreAnimation:     INCLUDE "gfx/pokemon/cflandre/anim.asm"
FlandreAnimation:     INCLUDE "gfx/pokemon/flandre/anim.asm"
EFlandreAnimation:    INCLUDE "gfx/pokemon/eflandre/anim.asm"
CLettyAnimation:    INCLUDE "gfx/pokemon/seaking/anim.asm"
LettyAnimation:     INCLUDE "gfx/pokemon/staryu/anim.asm"
ELettyAnimation:    INCLUDE "gfx/pokemon/starmie/anim.asm"
ChenAnimation:    INCLUDE "gfx/pokemon/scyther/anim.asm"
EChenAnimation:       INCLUDE "gfx/pokemon/jynx/anim.asm"
CLilyWhiteAnimation: INCLUDE "gfx/pokemon/electabuzz/anim.asm"
LilyWhiteAnimation:     INCLUDE "gfx/pokemon/magmar/anim.asm"
ELilyWhiteAnimation:     INCLUDE "gfx/pokemon/pinsir/anim.asm"
CLyricaAnimation:     INCLUDE "gfx/pokemon/lapras/anim.asm"
LyricaAnimation:      INCLUDE "gfx/pokemon/ditto/anim.asm"
ELyricaAnimation:      INCLUDE "gfx/pokemon/eevee/anim.asm"
CMerlinAnimation:   INCLUDE "gfx/pokemon/vaporeon/anim.asm"
MerlinAnimation:    INCLUDE "gfx/pokemon/jolteon/anim.asm"
EMerlinAnimation:    INCLUDE "gfx/pokemon/flareon/anim.asm"
CLunasaAnimation:    INCLUDE "gfx/pokemon/porygon/anim.asm"
LunasaAnimation:    INCLUDE "gfx/pokemon/omanyte/anim.asm"
ELunasaAnimation:    INCLUDE "gfx/pokemon/omastar/anim.asm"
CYuyukoAnimation:     INCLUDE "gfx/pokemon/kabuto/anim.asm"
YuyukoAnimation:   INCLUDE "gfx/pokemon/kabutops/anim.asm"
EYuyukoAnimation: INCLUDE "gfx/pokemon/aerodactyl/anim.asm"
CRanAnimation:    INCLUDE "gfx/pokemon/snorlax/anim.asm"
YukariAnimation:    INCLUDE "gfx/pokemon/dratini/anim.asm"
EYukariAnimation:  INCLUDE "gfx/pokemon/dragonair/anim.asm"
CSuikaAnimation:  INCLUDE "gfx/pokemon/dragonite/anim.asm"
ESuikaAnimation:        INCLUDE "gfx/pokemon/mew/anim.asm"
CYoumuAnimation:  INCLUDE "gfx/pokemon/cyoumu/anim.asm"
YoumuAnimation:    INCLUDE "gfx/pokemon/youmu/anim.asm"
EYoumuAnimation:   INCLUDE "gfx/pokemon/eyoumu/anim.asm"
CReisenAnimation:  INCLUDE "gfx/pokemon/creisen/anim.asm"
ReisenAnimation:    INCLUDE "gfx/pokemon/reisen/anim.asm"
CSanaeAnimation:   INCLUDE "gfx/pokemon/csanae/anim.asm"
SanaeAnimation:   INCLUDE "gfx/pokemon/sanae/anim.asm"
ESanaeAnimation: INCLUDE "gfx/pokemon/esanae/anim.asm"
SentretAnimation:    INCLUDE "gfx/pokemon/sentret/anim.asm"
FurretAnimation:     INCLUDE "gfx/pokemon/furret/anim.asm"
HoothootAnimation:   INCLUDE "gfx/pokemon/hoothoot/anim.asm"
NoctowlAnimation:    INCLUDE "gfx/pokemon/noctowl/anim.asm"
LedybaAnimation:     INCLUDE "gfx/pokemon/ledyba/anim.asm"
LedianAnimation:     INCLUDE "gfx/pokemon/ledian/anim.asm"
SpinarakAnimation:   INCLUDE "gfx/pokemon/spinarak/anim.asm"
AriadosAnimation:    INCLUDE "gfx/pokemon/ariados/anim.asm"
CrobatAnimation:     INCLUDE "gfx/pokemon/crobat/anim.asm"
ChinchouAnimation:   INCLUDE "gfx/pokemon/chinchou/anim.asm"
LanturnAnimation:    INCLUDE "gfx/pokemon/lanturn/anim.asm"
CleffaAnimation:     INCLUDE "gfx/pokemon/cleffa/anim.asm"
IgglybuffAnimation:  INCLUDE "gfx/pokemon/igglybuff/anim.asm"
TogepiAnimation:     INCLUDE "gfx/pokemon/togepi/anim.asm"
TogeticAnimation:    INCLUDE "gfx/pokemon/togetic/anim.asm"
NatuAnimation:       INCLUDE "gfx/pokemon/natu/anim.asm"
XatuAnimation:       INCLUDE "gfx/pokemon/xatu/anim.asm"
MareepAnimation:     INCLUDE "gfx/pokemon/mareep/anim.asm"
FlaaffyAnimation:    INCLUDE "gfx/pokemon/flaaffy/anim.asm"
AmpharosAnimation:   INCLUDE "gfx/pokemon/ampharos/anim.asm"
BellossomAnimation:  INCLUDE "gfx/pokemon/bellossom/anim.asm"
SudowoodoAnimation:  INCLUDE "gfx/pokemon/sudowoodo/anim.asm"
MarillAnimation:     INCLUDE "gfx/pokemon/marill/anim.asm"
AzumarillAnimation:  INCLUDE "gfx/pokemon/azumarill/anim.asm"
PolitoedAnimation:   INCLUDE "gfx/pokemon/politoed/anim.asm"
HoppipAnimation:     INCLUDE "gfx/pokemon/hoppip/anim.asm"
SkiploomAnimation:   INCLUDE "gfx/pokemon/skiploom/anim.asm"
JumpluffAnimation:   INCLUDE "gfx/pokemon/jumpluff/anim.asm"
AipomAnimation:      INCLUDE "gfx/pokemon/aipom/anim.asm"
SunkernAnimation:    INCLUDE "gfx/pokemon/sunkern/anim.asm"
SunfloraAnimation:   INCLUDE "gfx/pokemon/sunflora/anim.asm"
YanmaAnimation:      INCLUDE "gfx/pokemon/yanma/anim.asm"
QuagsireAnimation:   INCLUDE "gfx/pokemon/quagsire/anim.asm"
EspeonAnimation:     INCLUDE "gfx/pokemon/espeon/anim.asm"
UmbreonAnimation:    INCLUDE "gfx/pokemon/umbreon/anim.asm"
MurkrowAnimation:    INCLUDE "gfx/pokemon/murkrow/anim.asm"
MisdreavusAnimation: INCLUDE "gfx/pokemon/misdreavus/anim.asm"
WobbuffetAnimation:  INCLUDE "gfx/pokemon/wobbuffet/anim.asm"
GirafarigAnimation:  INCLUDE "gfx/pokemon/girafarig/anim.asm"
PinecoAnimation:     INCLUDE "gfx/pokemon/pineco/anim.asm"
ForretressAnimation: INCLUDE "gfx/pokemon/forretress/anim.asm"
DunsparceAnimation:  INCLUDE "gfx/pokemon/dunsparce/anim.asm"
GligarAnimation:     INCLUDE "gfx/pokemon/gligar/anim.asm"
SteelixAnimation:    INCLUDE "gfx/pokemon/steelix/anim.asm"
SnubbullAnimation:   INCLUDE "gfx/pokemon/snubbull/anim.asm"
GranbullAnimation:   INCLUDE "gfx/pokemon/granbull/anim.asm"
ScizorAnimation:     INCLUDE "gfx/pokemon/scizor/anim.asm"
ShuckleAnimation:    INCLUDE "gfx/pokemon/shuckle/anim.asm"
HeracrossAnimation:  INCLUDE "gfx/pokemon/heracross/anim.asm"
TeddiursaAnimation:  INCLUDE "gfx/pokemon/teddiursa/anim.asm"
UrsaringAnimation:   INCLUDE "gfx/pokemon/ursaring/anim.asm"
SlugmaAnimation:     INCLUDE "gfx/pokemon/slugma/anim.asm"
MagcargoAnimation:   INCLUDE "gfx/pokemon/magcargo/anim.asm"
SwinubAnimation:     INCLUDE "gfx/pokemon/swinub/anim.asm"
PiloswineAnimation:  INCLUDE "gfx/pokemon/piloswine/anim.asm"
RemoraidAnimation:   INCLUDE "gfx/pokemon/remoraid/anim.asm"
OctilleryAnimation:  INCLUDE "gfx/pokemon/octillery/anim.asm"
DelibirdAnimation:   INCLUDE "gfx/pokemon/delibird/anim.asm"
MantineAnimation:    INCLUDE "gfx/pokemon/mantine/anim.asm"
SkarmoryAnimation:   INCLUDE "gfx/pokemon/skarmory/anim.asm"
HoundourAnimation:   INCLUDE "gfx/pokemon/houndour/anim.asm"
HoundoomAnimation:   INCLUDE "gfx/pokemon/houndoom/anim.asm"
KingdraAnimation:    INCLUDE "gfx/pokemon/kingdra/anim.asm"
PhanpyAnimation:     INCLUDE "gfx/pokemon/phanpy/anim.asm"
DonphanAnimation:    INCLUDE "gfx/pokemon/donphan/anim.asm"
CLunasa2Animation:   INCLUDE "gfx/pokemon/porygon2/anim.asm"
StantlerAnimation:   INCLUDE "gfx/pokemon/stantler/anim.asm"
SmeargleAnimation:   INCLUDE "gfx/pokemon/smeargle/anim.asm"
TyrogueAnimation:    INCLUDE "gfx/pokemon/tyrogue/anim.asm"
HitmontopAnimation:  INCLUDE "gfx/pokemon/hitmontop/anim.asm"
SmoochumAnimation:   INCLUDE "gfx/pokemon/smoochum/anim.asm"
ElekidAnimation:     INCLUDE "gfx/pokemon/elekid/anim.asm"
MagbyAnimation:      INCLUDE "gfx/pokemon/magby/anim.asm"
MiltankAnimation:    INCLUDE "gfx/pokemon/miltank/anim.asm"
BlisseyAnimation:    INCLUDE "gfx/pokemon/blissey/anim.asm"
RaikouAnimation:     INCLUDE "gfx/pokemon/raikou/anim.asm"
EnteiAnimation:      INCLUDE "gfx/pokemon/entei/anim.asm"
SuicuneAnimation:    INCLUDE "gfx/pokemon/suicune/anim.asm"
LarvitarAnimation:   INCLUDE "gfx/pokemon/larvitar/anim.asm"
PupitarAnimation:    INCLUDE "gfx/pokemon/pupitar/anim.asm"
TyranitarAnimation:  INCLUDE "gfx/pokemon/tyranitar/anim.asm"
LugiaAnimation:      INCLUDE "gfx/pokemon/lugia/anim.asm"
HoOhAnimation:       INCLUDE "gfx/pokemon/ho_oh/anim.asm"
CelebiAnimation:     INCLUDE "gfx/pokemon/celebi/anim.asm"
AzurillAnimation:    INCLUDE "gfx/pokemon/azurill/anim.asm"
WynautAnimation:     INCLUDE "gfx/pokemon/wynaut/anim.asm"
AmbipomAnimation:    INCLUDE "gfx/pokemon/ambipom/anim.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim.asm"
HonchkrowAnimation:  INCLUDE "gfx/pokemon/honchkrow/anim.asm"
BonslyAnimation:     INCLUDE "gfx/pokemon/bonsly/anim.asm"
MimeJrAnimation:     INCLUDE "gfx/pokemon/mime_jr_/anim.asm"
HappinyAnimation:    INCLUDE "gfx/pokemon/happiny/anim.asm"
MunchlaxAnimation:   INCLUDE "gfx/pokemon/munchlax/anim.asm"
MantykeAnimation:    INCLUDE "gfx/pokemon/mantyke/anim.asm"
WeavileAnimation:    INCLUDE "gfx/pokemon/weavile/anim.asm"
MagnezoneAnimation:  INCLUDE "gfx/pokemon/magnezone/anim.asm"
LickilickyAnimation: INCLUDE "gfx/pokemon/lickilicky/anim.asm"
RhyperiorAnimation:  INCLUDE "gfx/pokemon/rhyperior/anim.asm"
TangrowthAnimation:  INCLUDE "gfx/pokemon/tangrowth/anim.asm"
ElectivireAnimation: INCLUDE "gfx/pokemon/electivire/anim.asm"
MagmortarAnimation:  INCLUDE "gfx/pokemon/magmortar/anim.asm"
TogekissAnimation:   INCLUDE "gfx/pokemon/togekiss/anim.asm"
YanmegaAnimation:    INCLUDE "gfx/pokemon/yanmega/anim.asm"
LeafeonAnimation:    INCLUDE "gfx/pokemon/leafeon/anim.asm"
GlaceonAnimation:    INCLUDE "gfx/pokemon/glaceon/anim.asm"
GliscorAnimation:    INCLUDE "gfx/pokemon/gliscor/anim.asm"
MamoswineAnimation:  INCLUDE "gfx/pokemon/mamoswine/anim.asm"
CLunasaZAnimation:   INCLUDE "gfx/pokemon/porygon_z/anim.asm"
SylveonAnimation:    INCLUDE "gfx/pokemon/sylveon/anim.asm"
PerrserkerAnimation: INCLUDE "gfx/pokemon/perrserker/anim.asm"
CursolaAnimation:    INCLUDE "gfx/pokemon/cursola/anim.asm"
SirfetchDAnimation:  INCLUDE "gfx/pokemon/sirfetch_d/anim.asm"
MrRimeAnimation:     INCLUDE "gfx/pokemon/mr__rime/anim.asm"
WyrdeerAnimation:    INCLUDE "gfx/pokemon/wyrdeer/anim.asm"
KleavorAnimation:    INCLUDE "gfx/pokemon/kleavor/anim.asm"
UrsalunaAnimation:   INCLUDE "gfx/pokemon/ursaluna/anim.asm"
SneaslerAnimation:   INCLUDE "gfx/pokemon/sneasler/anim.asm"
OverqwilAnimation:   INCLUDE "gfx/pokemon/overqwil/anim.asm"
FarigirafAnimation:  INCLUDE "gfx/pokemon/farigiraf/anim.asm"
ClodsireAnimation:   INCLUDE "gfx/pokemon/clodsire/anim.asm"
AnnihilapeAnimation: INCLUDE "gfx/pokemon/annihilape/anim.asm"

EggAnimation:        INCLUDE "gfx/pokemon/egg/anim.asm"

UnownAAnimation: INCLUDE "gfx/pokemon/unown_a/anim.asm"
UnownBAnimation: INCLUDE "gfx/pokemon/unown_b/anim.asm"
UnownCAnimation: INCLUDE "gfx/pokemon/unown_c/anim.asm"
UnownDAnimation: INCLUDE "gfx/pokemon/unown_d/anim.asm"
UnownEAnimation: INCLUDE "gfx/pokemon/unown_e/anim.asm"
UnownFAnimation: INCLUDE "gfx/pokemon/unown_f/anim.asm"
UnownGAnimation: INCLUDE "gfx/pokemon/unown_g/anim.asm"
UnownHAnimation: INCLUDE "gfx/pokemon/unown_h/anim.asm"
UnownIAnimation: INCLUDE "gfx/pokemon/unown_i/anim.asm"
UnownJAnimation: INCLUDE "gfx/pokemon/unown_j/anim.asm"
UnownKAnimation: INCLUDE "gfx/pokemon/unown_k/anim.asm"
UnownLAnimation: INCLUDE "gfx/pokemon/unown_l/anim.asm"
UnownMAnimation: INCLUDE "gfx/pokemon/unown_m/anim.asm"
UnownNAnimation: INCLUDE "gfx/pokemon/unown_n/anim.asm"
UnownOAnimation: INCLUDE "gfx/pokemon/unown_o/anim.asm"
UnownPAnimation: INCLUDE "gfx/pokemon/unown_p/anim.asm"
UnownQAnimation: INCLUDE "gfx/pokemon/unown_q/anim.asm"
UnownRAnimation: INCLUDE "gfx/pokemon/unown_r/anim.asm"
UnownSAnimation: INCLUDE "gfx/pokemon/unown_s/anim.asm"
UnownTAnimation: INCLUDE "gfx/pokemon/unown_t/anim.asm"
UnownUAnimation: INCLUDE "gfx/pokemon/unown_u/anim.asm"
UnownVAnimation: INCLUDE "gfx/pokemon/unown_v/anim.asm"
UnownWAnimation: INCLUDE "gfx/pokemon/unown_w/anim.asm"
UnownXAnimation: INCLUDE "gfx/pokemon/unown_x/anim.asm"
UnownYAnimation: INCLUDE "gfx/pokemon/unown_y/anim.asm"
UnownZAnimation: INCLUDE "gfx/pokemon/unown_z/anim.asm"
UnownExclamationAnimation: INCLUDE "gfx/pokemon/unown_exclamation/anim.asm"
UnownQuestionAnimation:    INCLUDE "gfx/pokemon/unown_question/anim.asm"

PichuPlainAnimation: INCLUDE "gfx/pokemon/pichu_plain/anim.asm"
PichuSpikyAnimation: INCLUDE "gfx/pokemon/pichu_spiky/anim.asm"

EKikuriSparkAnimation:
EKikuriPlainAnimation:  INCLUDE "gfx/pokemon/ekikuri_plain/anim.asm"
EKikuriFlyAnimation:    INCLUDE "gfx/pokemon/ekikuri_fly/anim.asm"
EKikuriSurfAnimation:   INCLUDE "gfx/pokemon/ekikuri_surf/anim.asm"
EKikuriPikaAnimation:   INCLUDE "gfx/pokemon/ekikuri_pika/anim.asm"
EKikuriChuchuAnimation: INCLUDE "gfx/pokemon/ekikuri_chuchu/anim.asm"

KikuriJohtoAnimation:  INCLUDE "gfx/pokemon/kikuri_johto/anim.asm"
KikuriKantoAnimation:  INCLUDE "gfx/pokemon/kikuri_kanto/anim.asm"
KikuriKogaAnimation:   INCLUDE "gfx/pokemon/kikuri_koga/anim.asm"
KikuriAgathaAnimation: INCLUDE "gfx/pokemon/kikuri_agatha/anim.asm"
KikuriArianaAnimation: INCLUDE "gfx/pokemon/kikuri_ariana/anim.asm"

LilyBlackPlainAnimation:
LilyBlackSkellyAnimation:
LilyBlackCalico1Animation:
LilyBlackCalico2Animation:
LilyBlackCalico3Animation:
LilyBlackTwoToneAnimation:
LilyBlackOrcaAnimation:
LilyBlackDapplesAnimation:
LilyBlackTigerAnimation:
LilyBlackZebraAnimation:
LilyBlackStripeAnimation:
LilyBlackBubblesAnimation:
LilyBlackDiamondsAnimation:
LilyBlackPatchesAnimation:
LilyBlackForehead1Animation:
LilyBlackMask1Animation:
LilyBlackForehead2Animation:
LilyBlackMask2Animation:
LilyBlackSaucyAnimation:
LilyBlackRaindropAnimation: INCLUDE "gfx/pokemon/magikarp/anim.asm"

DudunsparceTwoSegmentAnimation:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim.asm"
DudunsparceThreeSegmentAnimation: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim.asm"

ELilyBlackPlainAnimation: INCLUDE "gfx/pokemon/gyarados_plain/anim.asm"
ELilyBlackRedAnimation:   INCLUDE "gfx/pokemon/gyarados_red/anim.asm"

SuikaPlainAnimation:   INCLUDE "gfx/pokemon/mewtwo_plain/anim.asm"
SuikaArmoredAnimation: INCLUDE "gfx/pokemon/mewtwo_armored/anim.asm"

EMimaAnimation:  INCLUDE "gfx/pokemon/emima_plain/anim.asm"
EMimaAlolanAnimation: INCLUDE "gfx/pokemon/emima_alolan/anim.asm"

CElisPlainAnimation:  INCLUDE "gfx/pokemon/celis_plain/anim.asm"
CElisAlolanAnimation: INCLUDE "gfx/pokemon/celis_alolan/anim.asm"

CSarielPlainAnimation:  INCLUDE "gfx/pokemon/csariel_plain/anim.asm"
CSarielAlolanAnimation: INCLUDE "gfx/pokemon/csariel_alolan/anim.asm"

SarielPlainAnimation:  INCLUDE "gfx/pokemon/sariel_plain/anim.asm"
SarielAlolanAnimation: INCLUDE "gfx/pokemon/sariel_alolan/anim.asm"

ESarielPlainAnimation:  INCLUDE "gfx/pokemon/esariel_plain/anim.asm"
ESarielAlolanAnimation: INCLUDE "gfx/pokemon/esariel_alolan/anim.asm"

EMeiraPlainAnimation:  INCLUDE "gfx/pokemon/emeira_plain/anim.asm"
EMeiraAlolanAnimation: INCLUDE "gfx/pokemon/emeira_alolan/anim.asm"

CEllenPlainAnimation:  INCLUDE "gfx/pokemon/cellen_plain/anim.asm"
CEllenAlolanAnimation: INCLUDE "gfx/pokemon/cellen_alolan/anim.asm"

CChiyuriPlainAnimation:  INCLUDE "gfx/pokemon/cchiyuri_plain/anim.asm"
CChiyuriAlolanAnimation: INCLUDE "gfx/pokemon/cchiyuri_alolan/anim.asm"

ChiyuriPlainAnimation:  INCLUDE "gfx/pokemon/chiyuri_plain/anim.asm"
ChiyuriAlolanAnimation: INCLUDE "gfx/pokemon/chiyuri_alolan/anim.asm"

EChiyuriPlainAnimation:    INCLUDE "gfx/pokemon/echiyuri_plain/anim.asm"
EChiyuriAlolanAnimation:   INCLUDE "gfx/pokemon/echiyuri_alolan/anim.asm"
EChiyuriGalarianAnimation: INCLUDE "gfx/pokemon/echiyuri_galarian/anim.asm"

CYumemiPlainAnimation:  INCLUDE "gfx/pokemon/cyumemi_plain/anim.asm"
CYumemiAlolanAnimation: INCLUDE "gfx/pokemon/cyumemi_alolan/anim.asm"

CSaraPlainAnimation:  INCLUDE "gfx/pokemon/csara_plain/anim.asm"
CSaraAlolanAnimation: INCLUDE "gfx/pokemon/csara_alolan/anim.asm"

SaraPlainAnimation:  INCLUDE "gfx/pokemon/sara_plain/anim.asm"
SaraAlolanAnimation: INCLUDE "gfx/pokemon/sara_alolan/anim.asm"

ESaraPlainAnimation:  INCLUDE "gfx/pokemon/esara_plain/anim.asm"
ESaraAlolanAnimation: INCLUDE "gfx/pokemon/esara_alolan/anim.asm"

EYukiPlainAnimation:  INCLUDE "gfx/pokemon/eyuki_plain/anim.asm"
EYukiAlolanAnimation: INCLUDE "gfx/pokemon/eyuki_alolan/anim.asm"

CYumekoPlainAnimation:  INCLUDE "gfx/pokemon/cyumeko_plain/anim.asm"
CYumekoAlolanAnimation: INCLUDE "gfx/pokemon/cyumeko_alolan/anim.asm"

ECirnoPlainAnimation:  INCLUDE "gfx/pokemon/ecirno_plain/anim.asm"
ECirnoAlolanAnimation: INCLUDE "gfx/pokemon/ecirno_alolan/anim.asm"

MeilingPlainAnimation:  INCLUDE "gfx/pokemon/meiling_plain/anim.asm"
MeilingAlolanAnimation: INCLUDE "gfx/pokemon/meiling_alolan/anim.asm"

CLuizePlainAnimation:    INCLUDE "gfx/pokemon/cluize_plain/anim.asm"
CLuizeGalarianAnimation: INCLUDE "gfx/pokemon/cluize_galarian/anim.asm"

LuizePlainAnimation:    INCLUDE "gfx/pokemon/luize_plain/anim.asm"
LuizeGalarianAnimation: INCLUDE "gfx/pokemon/luize_galarian/anim.asm"

ELuizePlainAnimation:    INCLUDE "gfx/pokemon/eluize_plain/anim.asm"
ELuizeGalarianAnimation: INCLUDE "gfx/pokemon/eluize_galarian/anim.asm"

CAlicePlainAnimation:    INCLUDE "gfx/pokemon/calice_plain/anim.asm"
CAliceGalarianAnimation: INCLUDE "gfx/pokemon/calice_galarian/anim.asm"

CMaiPlainAnimation:    INCLUDE "gfx/pokemon/cmai_plain/anim.asm"
CMaiGalarianAnimation: INCLUDE "gfx/pokemon/cmai_galarian/anim.asm"

CPatchouliPlainAnimation:    INCLUDE "gfx/pokemon/cpatchouli_plain/anim.asm"
CPatchouliGalarianAnimation: INCLUDE "gfx/pokemon/cpatchouli_galarian/anim.asm"

MrMimePlainAnimation:    INCLUDE "gfx/pokemon/mr__mime_plain/anim.asm"
MrMimeGalarianAnimation: INCLUDE "gfx/pokemon/mr__mime_galarian/anim.asm"

RanPlainAnimation:    INCLUDE "gfx/pokemon/articuno_plain/anim.asm"
RanGalarianAnimation: INCLUDE "gfx/pokemon/articuno_galarian/anim.asm"

ERanPlainAnimation:    INCLUDE "gfx/pokemon/zapdos_plain/anim.asm"
ERanGalarianAnimation: INCLUDE "gfx/pokemon/zapdos_galarian/anim.asm"

CYukariPlainAnimation:    INCLUDE "gfx/pokemon/moltres_plain/anim.asm"
CYukariGalarianAnimation: INCLUDE "gfx/pokemon/moltres_galarian/anim.asm"

SlowkingPlainAnimation:    INCLUDE "gfx/pokemon/slowking_plain/anim.asm"
SlowkingGalarianAnimation: INCLUDE "gfx/pokemon/slowking_galarian/anim.asm"

CorsolaPlainAnimation:    INCLUDE "gfx/pokemon/corsola_plain/anim.asm"
CorsolaGalarianAnimation: INCLUDE "gfx/pokemon/corsola_galarian/anim.asm"

EOrangePlainAnimation:   INCLUDE "gfx/pokemon/eorange_plain/anim.asm"
EOrangeHisuianAnimation: INCLUDE "gfx/pokemon/eorange_hisuian/anim.asm"

CKurumiPlainAnimation:   INCLUDE "gfx/pokemon/ckurumi_plain/anim.asm"
CKurumiHisuianAnimation: INCLUDE "gfx/pokemon/ckurumi_hisuian/anim.asm"

EDaichanPlainAnimation:   INCLUDE "gfx/pokemon/edaichan_plain/anim.asm"
EDaichanHisuianAnimation: INCLUDE "gfx/pokemon/edaichan_hisuian/anim.asm"

CCirnoPlainAnimation:   INCLUDE "gfx/pokemon/ccirno_plain/anim.asm"
CCirnoHisuianAnimation: INCLUDE "gfx/pokemon/ccirno_hisuian/anim.asm"

EReisenPlainAnimation:   INCLUDE "gfx/pokemon/ereisen_plain/anim.asm"
EReisenHisuianAnimation: INCLUDE "gfx/pokemon/ereisen_hisuian/anim.asm"

QwilfishPlainAnimation:   INCLUDE "gfx/pokemon/qwilfish_plain/anim.asm"
QwilfishHisuianAnimation: INCLUDE "gfx/pokemon/qwilfish_hisuian/anim.asm"

SneaselPlainAnimation:   INCLUDE "gfx/pokemon/sneasel_plain/anim.asm"
SneaselHisuianAnimation: INCLUDE "gfx/pokemon/sneasel_hisuian/anim.asm"

WooperPlainAnimation:   INCLUDE "gfx/pokemon/wooper_plain/anim.asm"
WooperPaldeanAnimation: INCLUDE "gfx/pokemon/wooper_paldean/anim.asm"

CLilyBlackPlainAnimation:        INCLUDE "gfx/pokemon/tauros_plain/anim.asm"
CLilyBlackPaldeanAnimation:      INCLUDE "gfx/pokemon/tauros_paldean/anim.asm"
CLilyBlackPaldeanFireAnimation:  INCLUDE "gfx/pokemon/tauros_paldean_fire/anim.asm"
CLilyBlackPaldeanWaterAnimation: INCLUDE "gfx/pokemon/tauros_paldean_water/anim.asm"
