AnimationPointers:
	table_width 2, AnimationPointers
	dw CReimuAnimation
	dw ReimuAnimation
	dw EReimuAnimation
	dw CMarisaAnimation
	dw MarisaAnimation
	dw EMarisaAnimation
	dw CSakuyaAnimation
	dw SakuyaAnimation
	dw ESakuyaAnimation
	dw CGyokuAnimation
	dw MGyokuAnimation
	dw FGyokuAnimation
	dw OGyokuAnimation
	dw CMaganAnimation
	dw MaganAnimation
	dw EMaganAnimation
	dw CMimaAnimation
	dw MimaAnimation
	dw EMimaAnimation
	dw CElisPlainAnimation
	dw ElisAnimation
	dw EElisAnimation
	dw CKikuriAnimation
	dw KikuriJohtoAnimation
	dw EKikuriPlainAnimation
	dw CSarielPlainAnimation
	dw SarielPlainAnimation
	dw ESarielPlainAnimation
	dw CKongaraAnimation
	dw KongaraAnimation
	dw EKongaraAnimation
	dw CRikaAnimation
	dw RikaAnimation
	dw ERikaAnimation
	dw CMeiraAnimation
	dw MeiraAnimation
	dw EMeiraPlainAnimation
	dw CEllenPlainAnimation
	dw EllenAnimation
	dw EEllenAnimation
	dw CKotohimeAnimation
	dw KotohimeAnimation
	dw EKotohimeAnimation
	dw CKanaAnimation
	dw KanaAnimation
	dw EKanaAnimation
	dw CRikakoAnimation
	dw RikakoAnimation
	dw ERikakoAnimation
	dw CChiyuriPlainAnimation
	dw ChiyuriPlainAnimation
	dw EChiyuriPlainAnimation
	dw CYumemiPlainAnimation
	dw YumemiAnimation
	dw EYumemiAnimation
	dw COrangeAnimation
	dw OrangeAnimation
	dw EOrangePlainAnimation
	dw CKurumiPlainAnimation
	dw KurumiAnimation
	dw EKurumiAnimation
	dw CEllyAnimation
	dw EllyAnimation
	dw EEllyAnimation
	dw CYukaAnimation
	dw YukaAnimation
	dw EYukaAnimation
	dw CMugetsuAnimation
	dw MugetsuAnimation
	dw EMugetsuAnimation
	dw CGengetsuAnimation
	dw GengetsuAnimation
	dw EGengetsuAnimation
	dw CSaraPlainAnimation
	dw SaraPlainAnimation
	dw ESaraPlainAnimation
	dw CLuizePlainAnimation
	dw LuizePlainAnimation
	dw ELuizePlainAnimation
	dw CAlicePlainAnimation
	dw AliceAnimation
	dw EAliceAnimation
	dw CMaiPlainAnimation
	dw MaiAnimation
	dw EMaiAnimation
	dw CYukiAnimation
	dw YukiAnimation
	dw EYukiPlainAnimation
	dw CYumekoPlainAnimation
	dw YumekoAnimation
	dw EYumekoAnimation
	dw CShinkiAnimation
	dw ShinkiAnimation
	dw EShinkiAnimation
	dw CRumiaAnimation
	dw RumiaAnimation
	dw ERumiaAnimation
	dw CDaichanAnimation
	dw DaichanAnimation
	dw EDaichanPlainAnimation
	dw CCirnoPlainAnimation
	dw CirnoAnimation
	dw ECirnoPlainAnimation
	dw CMeilingAnimation
	dw MeilingPlainAnimation
	dw EMeilingAnimation
	dw CKoakumaAnimation
	dw KoakumaAnimation
	dw EKoakumaAnimation
	dw CPatchouliPlainAnimation
	dw PatchouliAnimation
	dw EPatchouliAnimation
	dw CRemiliaAnimation
	dw RemiliaAnimation
	dw ERemiliaAnimation
	dw CFlandreAnimation
	dw FlandreAnimation
	dw EFlandreAnimation
	dw CLettyAnimation
	dw LettyAnimation
	dw ELettyAnimation
	dw MrMimePlainAnimation
	dw ChenAnimation
	dw EChenAnimation
	dw CLilyWhiteAnimation
	dw LilyWhiteAnimation
	dw ELilyWhiteAnimation
	dw CLilyBlackPlainAnimation
	dw LilyBlackPlainAnimation
	dw ELilyBlackPlainAnimation
	dw CLyricaAnimation
	dw LyricaAnimation
	dw ELyricaAnimation
	dw CMerlinAnimation
	dw MerlinAnimation
	dw EMerlinAnimation
	dw CLunasaAnimation
	dw LunasaAnimation
	dw ELunasaAnimation
	dw CYuyukoAnimation
	dw YuyukoAnimation
	dw EYuyukoAnimation
	dw CRanAnimation
	dw RanPlainAnimation
	dw ERanPlainAnimation
	dw CYukariPlainAnimation
	dw YukariAnimation
	dw EYukariAnimation
	dw CSuikaAnimation
	dw SuikaPlainAnimation
	dw ESuikaAnimation
	dw CYoumuAnimation
	dw YoumuAnimation
	dw EYoumuAnimation
	dw CReisenAnimation
	dw ReisenAnimation
	dw EReisenPlainAnimation
	dw CSanaeAnimation
	dw SanaeAnimation
	dw ESanaeAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuPlainAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperPlainAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingPlainAnimation
	dw MisdreavusAnimation
	dw UnownAAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishPlainAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselPlainAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaPlainAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw CLunasa2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw AzurillAnimation
	dw WynautAnimation
	dw AmbipomAnimation
	dw EggAnimation
	dw EggAnimation
	dw MismagiusAnimation
	dw HonchkrowAnimation
	dw BonslyAnimation
	dw MimeJrAnimation
	dw HappinyAnimation
	dw MunchlaxAnimation
	dw MantykeAnimation
	dw WeavileAnimation
	dw MagnezoneAnimation
	dw LickilickyAnimation
	dw RhyperiorAnimation
	dw TangrowthAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw TogekissAnimation
	dw YanmegaAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw GliscorAnimation
	dw MamoswineAnimation
	dw CLunasaZAnimation
	dw SylveonAnimation
	dw PerrserkerAnimation
	dw CursolaAnimation
	dw SirfetchDAnimation
	dw MrRimeAnimation
	dw WyrdeerAnimation
	dw KleavorAnimation
	dw UrsalunaAnimation
	dw SneaslerAnimation
	dw OverqwilAnimation
	dw DudunsparceTwoSegmentAnimation
	dw FarigirafAnimation
	dw ClodsireAnimation
	dw AnnihilapeAnimation
	assert_table_length NUM_SPECIES

	dw UnownBAnimation
	dw UnownCAnimation
	dw UnownDAnimation
	dw UnownEAnimation
	dw UnownFAnimation
	dw UnownGAnimation
	dw UnownHAnimation
	dw UnownIAnimation
	dw UnownJAnimation
	dw UnownKAnimation
	dw UnownLAnimation
	dw UnownMAnimation
	dw UnownNAnimation
	dw UnownOAnimation
	dw UnownPAnimation
	dw UnownQAnimation
	dw UnownRAnimation
	dw UnownSAnimation
	dw UnownTAnimation
	dw UnownUAnimation
	dw UnownVAnimation
	dw UnownWAnimation
	dw UnownXAnimation
	dw UnownYAnimation
	dw UnownZAnimation
	dw UnownExclamationAnimation
	dw UnownQuestionAnimation

	dw KikuriKantoAnimation
	dw KikuriKogaAnimation
	dw KikuriAgathaAnimation
	dw KikuriArianaAnimation

	dw EKikuriFlyAnimation
	dw EKikuriSurfAnimation
	dw EKikuriPikaAnimation
	dw EKikuriChuchuAnimation
	dw EKikuriSparkAnimation

	dw PichuSpikyAnimation

	dw LilyBlackSkellyAnimation
	dw LilyBlackCalico1Animation
	dw LilyBlackCalico2Animation
	dw LilyBlackCalico3Animation
	dw LilyBlackTwoToneAnimation
	dw LilyBlackOrcaAnimation
	dw LilyBlackDapplesAnimation
	dw LilyBlackTigerAnimation
	dw LilyBlackZebraAnimation
	dw LilyBlackStripeAnimation
	dw LilyBlackBubblesAnimation
	dw LilyBlackDiamondsAnimation
	dw LilyBlackPatchesAnimation
	dw LilyBlackForehead1Animation
	dw LilyBlackMask1Animation
	dw LilyBlackForehead2Animation
	dw LilyBlackMask2Animation
	dw LilyBlackSaucyAnimation
	dw LilyBlackRaindropAnimation

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw ELilyBlackRedAnimation

	dw SuikaArmoredAnimation

	dw DudunsparceThreeSegmentAnimation

	dw EMimaAlolanAnimation
	dw CElisAlolanAnimation
	dw CSarielAlolanAnimation
	dw SarielAlolanAnimation
	dw ESarielAlolanAnimation
	dw EMeiraAlolanAnimation
	dw CEllenAlolanAnimation
	dw CChiyuriAlolanAnimation
	dw ChiyuriAlolanAnimation
	dw EChiyuriAlolanAnimation
	dw CYumemiAlolanAnimation
	dw CSaraAlolanAnimation
	dw SaraAlolanAnimation
	dw ESaraAlolanAnimation
	dw EYukiAlolanAnimation
	dw CYumekoAlolanAnimation
	dw ECirnoAlolanAnimation
	dw MeilingAlolanAnimation

	dw EChiyuriGalarianAnimation
	dw CLuizeGalarianAnimation
	dw LuizeGalarianAnimation
	dw ELuizeGalarianAnimation
	dw CAliceGalarianAnimation
	dw CMaiGalarianAnimation
	dw CPatchouliGalarianAnimation
	dw MrMimeGalarianAnimation
	dw RanGalarianAnimation
	dw ERanGalarianAnimation
	dw CYukariGalarianAnimation
	dw SlowkingGalarianAnimation
	dw CorsolaGalarianAnimation

	dw EOrangeHisuianAnimation
	dw CKurumiHisuianAnimation
	dw EDaichanHisuianAnimation
	dw CCirnoHisuianAnimation
	dw EReisenHisuianAnimation
	dw QwilfishHisuianAnimation
	dw SneaselHisuianAnimation

	dw WooperPaldeanAnimation
	dw CLilyBlackPaldeanAnimation
	dw CLilyBlackPaldeanFireAnimation
	dw CLilyBlackPaldeanWaterAnimation

	assert_table_length NUM_UNIQUE_POKEMON
