AnimationPointers:
	table_width 2, AnimationPointers
	dw CReimuAnimation
	dw ReimuAnimation
	dw TReimuAnimation
	dw CMarisaAnimation
	dw MarisaAnimation
	dw AMarisaAnimation
	dw CSakuyaAnimation
	dw SakuyaAnimation
	dw HSakuyaAnimation
	dw CGyokuAnimation
	dw MGyokuAnimation
	dw FGyokuAnimation
	dw OGyokuAnimation
	dw CMaganAnimation
	dw MaganAnimation
	dw CMimaAnimation
	dw MimaAnimation
	dw CElistion
	dw ElisAnimation
	dw CKikuriAnimation
	dw KikuriJohtoAnimation
	dw CSarieltion
	dw Sarieltion
	dw CKongaraAnimation
	dw KongaraAnimation
	dw CRikaAnimation
	dw RikaAnimation
	dw ARikaAnimation
	dw CMeiraAnimation
	dw MeiraAnimation
	dw CEllention
	dw EllenAnimation
	dw CKotohimeAnimation
	dw KotohimeAnimation
	dw CKanaAnimation
	dw KanaAnimation
	dw CRikakoAnimation
	dw RikakoAnimation
	dw CChiyurition
	dw Chiyurition
	dw CYumemition
	dw YumemiAnimation
	dw COrangeAnimation
	dw OrangeAnimation
	dw CKurumition
	dw KurumiAnimation
	dw CEllyAnimation
	dw EllyAnimation
	dw CYukaAnimation
	dw YukaAnimation
	dw AYukaAnimation
	dw CMugetsuAnimation
	dw MugetsuAnimation
	dw CGengetsuAnimation
	dw GengetsuAnimation
	dw CSaration
	dw Saration
	dw CLuizetion
	dw Luizetion
	dw DLuizetion
	dw CAlicetion
	dw AliceAnimation
	dw AAliceAnimation
	dw CMaition
	dw MaiAnimation
	dw CYukiAnimation
	dw YukiAnimation
	dw CYumekotion
	dw YumekoAnimation
	dw CShinkiAnimation
	dw ShinkiAnimation
	dw CRumiaAnimation
	dw RumiaAnimation
	dw ARumiaAnimation
	dw CDaichanAnimation
	dw DaichanAnimation
	dw DDaichantion
	dw CCirnotion
	dw CirnoAnimation
	dw SCirnotion
	dw CMeilingAnimation
	dw Meilingtion
	dw AMeilingAnimation
	dw CKoakumaAnimation
	dw KoakumaAnimation
	dw HKoakumaAnimation
	dw CPatchoulition
	dw PatchouliAnimation
	dw TPatchouliAnimation
	dw CRemiliaAnimation
	dw RemiliaAnimation
	dw SRemiliaAnimation
	dw CFlandreAnimation
	dw FlandreAnimation
	dw AFlandreAnimation
	dw CLettyAnimation
	dw LettyAnimation
	dw DLettyAnimation
	dw MrMimetion
	dw ChenAnimation
	dw HChenAnimation
	dw CLilyWhiteAnimation
	dw LilyWhiteAnimation
	dw ELilyWhiteAnimation
	dw CLilyBlacktion
	dw LilyBlacktion
	dw ELilyBlacktion
	dw CLyricaAnimation
	dw LyricaAnimation
	dw TLyricaAnimation
	dw CMerlinAnimation
	dw MerlinAnimation
	dw SMerlinAnimation
	dw CLunasaAnimation
	dw LunasaAnimation
	dw ALunasaAnimation
	dw CYuyukoAnimation
	dw YuyukoAnimation
	dw AYuyukoAnimation
	dw CRanAnimation
	dw Rantion
	dw TRantion
	dw CYukarition
	dw YukariAnimation
	dw TYukariAnimation
	dw CSuikaAnimation
	dw Suikation
	dw TSuikaAnimation
	dw CYoumuAnimation
	dw YoumuAnimation
	dw SYoumuAnimation
	dw CReisenAnimation
	dw ReisenAnimation
	dw TReisention
	dw CSanaeAnimation
	dw SanaeAnimation
	dw DSanaeAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw Pichution
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw Woopertion
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw Slowkingtion
	dw MisdreavusAnimation
	dw UnownAAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw Qwilfishtion
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw Sneaseltion
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw Corsolation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw CLunasa2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw AzurillAnimation
	dw WynautAnimation
	dw AmbipomAnimation
	dw EggAnimation
	dw EggAnimation
	dw MismagiusAnimation
	dw HonchkrowAnimation
	dw BonslyAnimation
	dw MimeJrAnimation
	dw HappinyAnimation
	dw MunchlaxAnimation
	dw MantykeAnimation
	dw WeavileAnimation
	dw MagnezoneAnimation
	dw LickilickyAnimation
	dw RhyperiorAnimation
	dw TangrowthAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw TogekissAnimation
	dw YanmegaAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw GliscorAnimation
	dw MamoswineAnimation
	dw CLunasaZAnimation
	dw SylveonAnimation
	dw PerrserkerAnimation
	dw CursolaAnimation
	dw SirfetchDAnimation
	dw MrRimeAnimation
	dw WyrdeerAnimation
	dw KleavorAnimation
	dw UrsalunaAnimation
	dw SneaslerAnimation
	dw OverqwilAnimation
	dw DudunsparceTwoSegmentAnimation
	dw FarigirafAnimation
	dw ClodsireAnimation
	dw AnnihilapeAnimation
	assert_table_length NUM_SPECIES

	dw UnownBAnimation
	dw UnownCAnimation
	dw UnownDAnimation
	dw UnownEAnimation
	dw UnownFAnimation
	dw UnownGAnimation
	dw UnownHAnimation
	dw UnownIAnimation
	dw UnownJAnimation
	dw UnownKAnimation
	dw UnownLAnimation
	dw UnownMAnimation
	dw UnownNAnimation
	dw UnownOAnimation
	dw UnownPAnimation
	dw UnownQAnimation
	dw UnownRAnimation
	dw UnownSAnimation
	dw UnownTAnimation
	dw UnownUAnimation
	dw UnownVAnimation
	dw UnownWAnimation
	dw UnownXAnimation
	dw UnownYAnimation
	dw UnownZAnimation
	dw UnownExclamationAnimation
	dw UnownQuestionAnimation

	dw KikuriKantoAnimation
	dw KikuriKogaAnimation
	dw KikuriAgathaAnimation
	dw KikuriArianaAnimation

	dw PichuSpikyAnimation

	dw LilyBlackSkellyAnimation
	dw LilyBlackCalico1Animation
	dw LilyBlackCalico2Animation
	dw LilyBlackCalico3Animation
	dw LilyBlackTwoToneAnimation
	dw LilyBlackOrcaAnimation
	dw LilyBlackDapplesAnimation
	dw LilyBlackTigerAnimation
	dw LilyBlackZebraAnimation
	dw LilyBlackStripeAnimation
	dw LilyBlackBubblesAnimation
	dw LilyBlackDiamondsAnimation
	dw LilyBlackPatchesAnimation
	dw LilyBlackForehead1Animation
	dw LilyBlackMask1Animation
	dw LilyBlackForehead2Animation
	dw LilyBlackMask2Animation
	dw LilyBlackSaucyAnimation
	dw LilyBlackRaindropAnimation

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw ELilyBlackRedAnimation

	dw SuikaArmoredAnimation

	dw DudunsparceThreeSegmentAnimation

	assert_table_length NUM_UNIQUE_POKEMON
