BitmasksPointers:
	table_width 2, BitmasksPointers
	dw CReimuBitmasks
	dw ReimuBitmasks
	dw EReimuBitmasks
	dw CMarisaBitmasks
	dw MarisaBitmasks
	dw EMarisaBitmasks
	dw CSakuyaBitmasks
	dw SakuyaBitmasks
	dw ESakuyaBitmasks
	dw CGyokuBitmasks
	dw MGyokuBitmasks
	dw FGyokuBitmasks
	dw OGyokuBitmasks
	dw CMaganBitmasks
	dw MaganBitmasks
	dw EMaganBitmasks
	dw CMimaBitmasks
	dw MimaBitmasks
	dw EMimaBitmasks
	dw CElisPlainBitmasks
	dw ElisBitmasks
	dw EElisBitmasks
	dw CKikuriBitmasks
	dw KikuriJohtoBitmasks
	dw EKikuriPlainBitmasks
	dw CSarielPlainBitmasks
	dw SarielPlainBitmasks
	dw ESarielPlainBitmasks
	dw CKongaraBitmasks
	dw KongaraBitmasks
	dw EKongaraBitmasks
	dw CRikaBitmasks
	dw RikaBitmasks
	dw ERikaBitmasks
	dw CMeiraBitmasks
	dw MeiraBitmasks
	dw EMeiraPlainBitmasks
	dw CEllenPlainBitmasks
	dw EllenBitmasks
	dw EEllenBitmasks
	dw CKotohimeBitmasks
	dw KotohimeBitmasks
	dw EKotohimeBitmasks
	dw CKanaBitmasks
	dw KanaBitmasks
	dw EKanaBitmasks
	dw CRikakoBitmasks
	dw RikakoBitmasks
	dw ERikakoBitmasks
	dw CChiyuriPlainBitmasks
	dw ChiyuriPlainBitmasks
	dw EChiyuriPlainBitmasks
	dw CYumemiPlainBitmasks
	dw YumemiBitmasks
	dw EYumemiBitmasks
	dw COrangeBitmasks
	dw OrangeBitmasks
	dw EOrangePlainBitmasks
	dw CKurumiPlainBitmasks
	dw KurumiBitmasks
	dw EKurumiBitmasks
	dw CEllyBitmasks
	dw EllyBitmasks
	dw EEllyBitmasks
	dw CYukaBitmasks
	dw YukaBitmasks
	dw EYukaBitmasks
	dw CMugetsuBitmasks
	dw MugetsuBitmasks
	dw EMugetsuBitmasks
	dw CGengetsuBitmasks
	dw GengetsuBitmasks
	dw EGengetsuBitmasks
	dw CSaraPlainBitmasks
	dw SaraPlainBitmasks
	dw ESaraPlainBitmasks
	dw CLuizePlainBitmasks
	dw LuizePlainBitmasks
	dw ELuizePlainBitmasks
	dw CAlicePlainBitmasks
	dw AliceBitmasks
	dw EAliceBitmasks
	dw CMaiPlainBitmasks
	dw MaiBitmasks
	dw EMaiBitmasks
	dw CYukiBitmasks
	dw YukiBitmasks
	dw EYukiPlainBitmasks
	dw CYumekoPlainBitmasks
	dw YumekoBitmasks
	dw EYumekoBitmasks
	dw CShinkiBitmasks
	dw ShinkiBitmasks
	dw EShinkiBitmasks
	dw CRumiaBitmasks
	dw RumiaBitmasks
	dw ERumiaBitmasks
	dw CDaichanBitmasks
	dw DaichanBitmasks
	dw EDaichanPlainBitmasks
	dw CCirnoPlainBitmasks
	dw CirnoBitmasks
	dw ExeggutorPlainBitmasks
	dw CuboneBitmasks
	dw MarowakPlainBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingPlainBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimePlainBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosPlainBitmasks
	dw MagikarpPlainBitmasks
	dw GyaradosPlainBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoPlainBitmasks
	dw ZapdosPlainBitmasks
	dw MoltresPlainBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoPlainBitmasks
	dw MewBitmasks
	dw CYoumuBitmasks
	dw YoumuBitmasks
	dw EYoumuBitmasks
	dw CReisenBitmasks
	dw ReisenBitmasks
	dw EReisenPlainBitmasks
	dw CSanaeBitmasks
	dw SanaeBitmasks
	dw ESanaeBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuPlainBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperPlainBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingPlainBitmasks
	dw MisdreavusBitmasks
	dw UnownABitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishPlainBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselPlainBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaPlainBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw AzurillBitmasks
	dw WynautBitmasks
	dw AmbipomBitmasks
	dw EggBitmasks
	dw EggBitmasks ; $100
	dw MismagiusBitmasks
	dw HonchkrowBitmasks
	dw BonslyBitmasks
	dw MimeJrBitmasks
	dw HappinyBitmasks
	dw MunchlaxBitmasks
	dw MantykeBitmasks
	dw WeavileBitmasks
	dw MagnezoneBitmasks
	dw LickilickyBitmasks
	dw RhyperiorBitmasks
	dw TangrowthBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw TogekissBitmasks
	dw YanmegaBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw GliscorBitmasks
	dw MamoswineBitmasks
	dw PorygonZBitmasks
	dw SylveonBitmasks
	dw PerrserkerBitmasks
	dw CursolaBitmasks
	dw SirfetchDBitmasks
	dw MrRimeBitmasks
	dw WyrdeerBitmasks
	dw KleavorBitmasks
	dw UrsalunaBitmasks
	dw SneaslerBitmasks
	dw OverqwilBitmasks
	dw DudunsparceTwoSegmentBitmasks
	dw FarigirafBitmasks
	dw ClodsireBitmasks
	dw AnnihilapeBitmasks
	assert_table_length NUM_SPECIES

	dw UnownBBitmasks
	dw UnownCBitmasks
	dw UnownDBitmasks
	dw UnownEBitmasks
	dw UnownFBitmasks
	dw UnownGBitmasks
	dw UnownHBitmasks
	dw UnownIBitmasks
	dw UnownJBitmasks
	dw UnownKBitmasks
	dw UnownLBitmasks
	dw UnownMBitmasks
	dw UnownNBitmasks
	dw UnownOBitmasks
	dw UnownPBitmasks
	dw UnownQBitmasks
	dw UnownRBitmasks
	dw UnownSBitmasks
	dw UnownTBitmasks
	dw UnownUBitmasks
	dw UnownVBitmasks
	dw UnownWBitmasks
	dw UnownXBitmasks
	dw UnownYBitmasks
	dw UnownZBitmasks
	dw UnownExclamationBitmasks
	dw UnownQuestionBitmasks

	dw KikuriKantoBitmasks
	dw KikuriKogaBitmasks
	dw KikuriAgathaBitmasks
	dw KikuriArianaBitmasks

	dw EKikuriFlyBitmasks
	dw EKikuriSurfBitmasks
	dw EKikuriPikaBitmasks
	dw EKikuriChuchuBitmasks
	dw EKikuriSparkBitmasks

	dw PichuSpikyBitmasks

	dw MagikarpSkellyBitmasks
	dw MagikarpCalico1Bitmasks
	dw MagikarpCalico2Bitmasks
	dw MagikarpCalico3Bitmasks
	dw MagikarpTwoToneBitmasks
	dw MagikarpOrcaBitmasks
	dw MagikarpDapplesBitmasks
	dw MagikarpTigerBitmasks
	dw MagikarpZebraBitmasks
	dw MagikarpStripeBitmasks
	dw MagikarpBubblesBitmasks
	dw MagikarpDiamondsBitmasks
	dw MagikarpPatchesBitmasks
	dw MagikarpForehead1Bitmasks
	dw MagikarpMask1Bitmasks
	dw MagikarpForehead2Bitmasks
	dw MagikarpMask2Bitmasks
	dw MagikarpSaucyBitmasks
	dw MagikarpRaindropBitmasks

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw GyaradosRedBitmasks

	dw MewtwoArmoredBitmasks

	dw DudunsparceThreeSegmentBitmasks

	dw EMimaAlolanBitmasks
	dw CElisAlolanBitmasks
	dw CSarielAlolanBitmasks
	dw SarielAlolanBitmasks
	dw ESarielAlolanBitmasks
	dw EMeiraAlolanBitmasks
	dw CEllenAlolanBitmasks
	dw CChiyuriAlolanBitmasks
	dw ChiyuriAlolanBitmasks
	dw EChiyuriAlolanBitmasks
	dw CYumemiAlolanBitmasks
	dw CSaraAlolanBitmasks
	dw SaraAlolanBitmasks
	dw ESaraAlolanBitmasks
	dw EYukiAlolanBitmasks
	dw CYumekoAlolanBitmasks
	dw ExeggutorAlolanBitmasks
	dw MarowakAlolanBitmasks

	dw EChiyuriGalarianBitmasks
	dw CLuizeGalarianBitmasks
	dw LuizeGalarianBitmasks
	dw ELuizeGalarianBitmasks
	dw CAliceGalarianBitmasks
	dw CMaiGalarianBitmasks
	dw WeezingGalarianBitmasks
	dw MrMimeGalarianBitmasks
	dw ArticunoGalarianBitmasks
	dw ZapdosGalarianBitmasks
	dw MoltresGalarianBitmasks
	dw SlowkingGalarianBitmasks
	dw CorsolaGalarianBitmasks

	dw EOrangeHisuianBitmasks
	dw CKurumiHisuianBitmasks
	dw EDaichanHisuianBitmasks
	dw CCirnoHisuianBitmasks
	dw EReisenHisuianBitmasks
	dw QwilfishHisuianBitmasks
	dw SneaselHisuianBitmasks

	dw WooperPaldeanBitmasks
	dw TaurosPaldeanBitmasks
	dw TaurosPaldeanFireBitmasks
	dw TaurosPaldeanWaterBitmasks

	assert_table_length NUM_UNIQUE_POKEMON
