CReimuBitmasks:  INCLUDE "gfx/pokemon/creimu/bitmask.asm"
ReimuBitmasks:    INCLUDE "gfx/pokemon/reimu/bitmask.asm"
TReimuBitmasks:   INCLUDE "gfx/pokemon/treimu/bitmask.asm"
CMarisaBitmasks: INCLUDE "gfx/pokemon/cmarisa/bitmask.asm"
MarisaBitmasks: INCLUDE "gfx/pokemon/marisa/bitmask.asm"
AMarisaBitmasks:  INCLUDE "gfx/pokemon/amarisa/bitmask.asm"
CSakuyaBitmasks:   INCLUDE "gfx/pokemon/csakuya/bitmask.asm"
SakuyaBitmasks:  INCLUDE "gfx/pokemon/sakuya/bitmask.asm"
HSakuyaBitmasks:  INCLUDE "gfx/pokemon/hsakuya/bitmask.asm"
CGyokuBitmasks:   INCLUDE "gfx/pokemon/cgyoku/bitmask.asm"
MGyokuBitmasks:    INCLUDE "gfx/pokemon/mgyoku/bitmask.asm"
FGyokuBitmasks: INCLUDE "gfx/pokemon/fgyoku/bitmask.asm"
OGyokuBitmasks:     INCLUDE "gfx/pokemon/ogyoku/bitmask.asm"
CMaganBitmasks:     INCLUDE "gfx/pokemon/cmagan/bitmask.asm"
MaganBitmasks:   INCLUDE "gfx/pokemon/magan/bitmask.asm"
CMimaBitmasks:  INCLUDE "gfx/pokemon/cmima/bitmask.asm"
MimaBitmasks:    INCLUDE "gfx/pokemon/mima/bitmask.asm"
ElisBitmasks:    INCLUDE "gfx/pokemon/elis/bitmask.asm"
CKikuriBitmasks:      INCLUDE "gfx/pokemon/ckikuri/bitmask.asm"
CKongaraBitmasks:   INCLUDE "gfx/pokemon/ckongara/bitmask.asm"
KongaraBitmasks:   INCLUDE "gfx/pokemon/kongara/bitmask.asm"
CRikaBitmasks:   INCLUDE "gfx/pokemon/crika/bitmask.asm"
RikaBitmasks:   INCLUDE "gfx/pokemon/rika/bitmask.asm"
ARikaBitmasks:   INCLUDE "gfx/pokemon/arika/bitmask.asm"
CMeiraBitmasks:   INCLUDE "gfx/pokemon/cmeira/bitmask.asm"
MeiraBitmasks:   INCLUDE "gfx/pokemon/meira/bitmask.asm"
EllenBitmasks: INCLUDE "gfx/pokemon/ellen/bitmask.asm"
CKotohimeBitmasks:      INCLUDE "gfx/pokemon/ckotohime/bitmask.asm"
KotohimeBitmasks:     INCLUDE "gfx/pokemon/kotohime/bitmask.asm"
CKanaBitmasks:      INCLUDE "gfx/pokemon/ckana/bitmask.asm"
KanaBitmasks:  INCLUDE "gfx/pokemon/kana/bitmask.asm"
CRikakoBitmasks:   INCLUDE "gfx/pokemon/crikako/bitmask.asm"
RikakoBitmasks:    INCLUDE "gfx/pokemon/rikako/bitmask.asm"
YumemiBitmasks:    INCLUDE "gfx/pokemon/yumemi/bitmask.asm"
COrangeBitmasks:     INCLUDE "gfx/pokemon/corange/bitmask.asm"
OrangeBitmasks:   INCLUDE "gfx/pokemon/orange/bitmask.asm"
KurumiBitmasks:    INCLUDE "gfx/pokemon/kurumi/bitmask.asm"
CEllyBitmasks:  INCLUDE "gfx/pokemon/celly/bitmask.asm"
EllyBitmasks:       INCLUDE "gfx/pokemon/elly/bitmask.asm"
CYukaBitmasks:   INCLUDE "gfx/pokemon/cyuka/bitmask.asm"
YukaBitmasks:     INCLUDE "gfx/pokemon/yuka/bitmask.asm"
AYukaBitmasks:    INCLUDE "gfx/pokemon/ayuka/bitmask.asm"
CMugetsuBitmasks:    INCLUDE "gfx/pokemon/cmugetsu/bitmask.asm"
MugetsuBitmasks: INCLUDE "gfx/pokemon/mugetsu/bitmask.asm"
CGengetsuBitmasks: INCLUDE "gfx/pokemon/cgengetsu/bitmask.asm"
GengetsuBitmasks:  INCLUDE "gfx/pokemon/gengetsu/bitmask.asm"
AliceBitmasks:  INCLUDE "gfx/pokemon/alice/bitmask.asm"
AAliceBitmasks:   INCLUDE "gfx/pokemon/aalice/bitmask.asm"
MaiBitmasks:      INCLUDE "gfx/pokemon/mai/bitmask.asm"
CYukiBitmasks:       INCLUDE "gfx/pokemon/cyuki/bitmask.asm"
YukiBitmasks:    INCLUDE "gfx/pokemon/yuki/bitmask.asm"
YumekoBitmasks:   INCLUDE "gfx/pokemon/yumeko/bitmask.asm"
CShinkiBitmasks:     INCLUDE "gfx/pokemon/cshinki/bitmask.asm"
ShinkiBitmasks:    INCLUDE "gfx/pokemon/shinki/bitmask.asm"
CRumiaBitmasks:       INCLUDE "gfx/pokemon/crumia/bitmask.asm"
RumiaBitmasks:    INCLUDE "gfx/pokemon/rumia/bitmask.asm"
ARumiaBitmasks:      INCLUDE "gfx/pokemon/arumia/bitmask.asm"
CDaichanBitmasks:     INCLUDE "gfx/pokemon/cdaichan/bitmask.asm"
DaichanBitmasks:    INCLUDE "gfx/pokemon/daichan/bitmask.asm"
CirnoBitmasks:  INCLUDE "gfx/pokemon/cirno/bitmask.asm"
CMeilingBitmasks:     INCLUDE "gfx/pokemon/cmeiling/bitmask.asm"
AMeilingBitmasks:  INCLUDE "gfx/pokemon/ameiling/bitmask.asm"
CKoakumaBitmasks: INCLUDE "gfx/pokemon/ckoakuma/bitmask.asm"
KoakumaBitmasks:  INCLUDE "gfx/pokemon/koakuma/bitmask.asm"
HKoakumaBitmasks:    INCLUDE "gfx/pokemon/hkoakuma/bitmask.asm"
PatchouliBitmasks:    INCLUDE "gfx/pokemon/patchouli/bitmask.asm"
TPatchouliBitmasks:     INCLUDE "gfx/pokemon/tpatchouli/bitmask.asm"
CRemiliaBitmasks:    INCLUDE "gfx/pokemon/cremilia/bitmask.asm"
RemiliaBitmasks:    INCLUDE "gfx/pokemon/remilia/bitmask.asm"
SRemiliaBitmasks: INCLUDE "gfx/pokemon/sremilia/bitmask.asm"
CFlandreBitmasks:     INCLUDE "gfx/pokemon/cflandre/bitmask.asm"
FlandreBitmasks:     INCLUDE "gfx/pokemon/flandre/bitmask.asm"
AFlandreBitmasks:    INCLUDE "gfx/pokemon/aflandre/bitmask.asm"
CLettyBitmasks:    INCLUDE "gfx/pokemon/seaking/bitmask.asm"
LettyBitmasks:     INCLUDE "gfx/pokemon/staryu/bitmask.asm"
DLettyBitmasks:    INCLUDE "gfx/pokemon/starmie/bitmask.asm"
ChenBitmasks:    INCLUDE "gfx/pokemon/scyther/bitmask.asm"
HChenBitmasks:       INCLUDE "gfx/pokemon/jynx/bitmask.asm"
CLilyWhiteBitmasks: INCLUDE "gfx/pokemon/electabuzz/bitmask.asm"
LilyWhiteBitmasks:     INCLUDE "gfx/pokemon/magmar/bitmask.asm"
ELilyWhiteBitmasks:     INCLUDE "gfx/pokemon/pinsir/bitmask.asm"
CLyricaBitmasks:     INCLUDE "gfx/pokemon/lapras/bitmask.asm"
LyricaBitmasks:      INCLUDE "gfx/pokemon/ditto/bitmask.asm"
TLyricaBitmasks:      INCLUDE "gfx/pokemon/eevee/bitmask.asm"
CMerlinBitmasks:   INCLUDE "gfx/pokemon/vaporeon/bitmask.asm"
MerlinBitmasks:    INCLUDE "gfx/pokemon/jolteon/bitmask.asm"
SMerlinBitmasks:    INCLUDE "gfx/pokemon/flareon/bitmask.asm"
CLunasaBitmasks:    INCLUDE "gfx/pokemon/porygon/bitmask.asm"
LunasaBitmasks:    INCLUDE "gfx/pokemon/omanyte/bitmask.asm"
ALunasaBitmasks:    INCLUDE "gfx/pokemon/omastar/bitmask.asm"
CYuyukoBitmasks:     INCLUDE "gfx/pokemon/kabuto/bitmask.asm"
YuyukoBitmasks:   INCLUDE "gfx/pokemon/kabutops/bitmask.asm"
AYuyukoBitmasks: INCLUDE "gfx/pokemon/aerodactyl/bitmask.asm"
CRanBitmasks:    INCLUDE "gfx/pokemon/snorlax/bitmask.asm"
YukariBitmasks:    INCLUDE "gfx/pokemon/dratini/bitmask.asm"
TYukariBitmasks:  INCLUDE "gfx/pokemon/dragonair/bitmask.asm"
CSuikaBitmasks:  INCLUDE "gfx/pokemon/dragonite/bitmask.asm"
TSuikaBitmasks:        INCLUDE "gfx/pokemon/mew/bitmask.asm"
CYoumuBitmasks:  INCLUDE "gfx/pokemon/cyoumu/bitmask.asm"
YoumuBitmasks:    INCLUDE "gfx/pokemon/youmu/bitmask.asm"
SYoumuBitmasks:   INCLUDE "gfx/pokemon/syoumu/bitmask.asm"
CReisenBitmasks:  INCLUDE "gfx/pokemon/creisen/bitmask.asm"
ReisenBitmasks:    INCLUDE "gfx/pokemon/reisen/bitmask.asm"
CSanaeBitmasks:   INCLUDE "gfx/pokemon/csanae/bitmask.asm"
SanaeBitmasks:   INCLUDE "gfx/pokemon/sanae/bitmask.asm"
DSanaeBitmasks: INCLUDE "gfx/pokemon/dsanae/bitmask.asm"
SentretBitmasks:    INCLUDE "gfx/pokemon/sentret/bitmask.asm"
FurretBitmasks:     INCLUDE "gfx/pokemon/furret/bitmask.asm"
HoothootBitmasks:   INCLUDE "gfx/pokemon/hoothoot/bitmask.asm"
NoctowlBitmasks:    INCLUDE "gfx/pokemon/noctowl/bitmask.asm"
LedybaBitmasks:     INCLUDE "gfx/pokemon/ledyba/bitmask.asm"
LedianBitmasks:     INCLUDE "gfx/pokemon/ledian/bitmask.asm"
SpinarakBitmasks:   INCLUDE "gfx/pokemon/spinarak/bitmask.asm"
AriadosBitmasks:    INCLUDE "gfx/pokemon/ariados/bitmask.asm"
CrobatBitmasks:     INCLUDE "gfx/pokemon/crobat/bitmask.asm"
ChinchouBitmasks:   INCLUDE "gfx/pokemon/chinchou/bitmask.asm"
LanturnBitmasks:    INCLUDE "gfx/pokemon/lanturn/bitmask.asm"
CleffaBitmasks:     INCLUDE "gfx/pokemon/cleffa/bitmask.asm"
IgglybuffBitmasks:  INCLUDE "gfx/pokemon/igglybuff/bitmask.asm"
TogepiBitmasks:     INCLUDE "gfx/pokemon/togepi/bitmask.asm"
TogeticBitmasks:    INCLUDE "gfx/pokemon/togetic/bitmask.asm"
NatuBitmasks:       INCLUDE "gfx/pokemon/natu/bitmask.asm"
XatuBitmasks:       INCLUDE "gfx/pokemon/xatu/bitmask.asm"
MareepBitmasks:     INCLUDE "gfx/pokemon/mareep/bitmask.asm"
FlaaffyBitmasks:    INCLUDE "gfx/pokemon/flaaffy/bitmask.asm"
AmpharosBitmasks:   INCLUDE "gfx/pokemon/ampharos/bitmask.asm"
BellossomBitmasks:  INCLUDE "gfx/pokemon/bellossom/bitmask.asm"
SudowoodoBitmasks:  INCLUDE "gfx/pokemon/sudowoodo/bitmask.asm"
MarillBitmasks:     INCLUDE "gfx/pokemon/marill/bitmask.asm"
AzumarillBitmasks:  INCLUDE "gfx/pokemon/azumarill/bitmask.asm"
PolitoedBitmasks:   INCLUDE "gfx/pokemon/politoed/bitmask.asm"
HoppipBitmasks:     INCLUDE "gfx/pokemon/hoppip/bitmask.asm"
SkiploomBitmasks:   INCLUDE "gfx/pokemon/skiploom/bitmask.asm"
JumpluffBitmasks:   INCLUDE "gfx/pokemon/jumpluff/bitmask.asm"
AipomBitmasks:      INCLUDE "gfx/pokemon/aipom/bitmask.asm"
SunkernBitmasks:    INCLUDE "gfx/pokemon/sunkern/bitmask.asm"
SunfloraBitmasks:   INCLUDE "gfx/pokemon/sunflora/bitmask.asm"
YanmaBitmasks:      INCLUDE "gfx/pokemon/yanma/bitmask.asm"
QuagsireBitmasks:   INCLUDE "gfx/pokemon/quagsire/bitmask.asm"
EspeonBitmasks:     INCLUDE "gfx/pokemon/espeon/bitmask.asm"
UmbreonBitmasks:    INCLUDE "gfx/pokemon/umbreon/bitmask.asm"
MurkrowBitmasks:    INCLUDE "gfx/pokemon/murkrow/bitmask.asm"
MisdreavusBitmasks: INCLUDE "gfx/pokemon/misdreavus/bitmask.asm"
WobbuffetBitmasks:  INCLUDE "gfx/pokemon/wobbuffet/bitmask.asm"
GirafarigBitmasks:  INCLUDE "gfx/pokemon/girafarig/bitmask.asm"
PinecoBitmasks:     INCLUDE "gfx/pokemon/pineco/bitmask.asm"
ForretressBitmasks: INCLUDE "gfx/pokemon/forretress/bitmask.asm"
DunsparceBitmasks:  INCLUDE "gfx/pokemon/dunsparce/bitmask.asm"
GligarBitmasks:     INCLUDE "gfx/pokemon/gligar/bitmask.asm"
SteelixBitmasks:    INCLUDE "gfx/pokemon/steelix/bitmask.asm"
SnubbullBitmasks:   INCLUDE "gfx/pokemon/snubbull/bitmask.asm"
GranbullBitmasks:   INCLUDE "gfx/pokemon/granbull/bitmask.asm"
ScizorBitmasks:     INCLUDE "gfx/pokemon/scizor/bitmask.asm"
ShuckleBitmasks:    INCLUDE "gfx/pokemon/shuckle/bitmask.asm"
HeracrossBitmasks:  INCLUDE "gfx/pokemon/heracross/bitmask.asm"
TeddiursaBitmasks:  INCLUDE "gfx/pokemon/teddiursa/bitmask.asm"
UrsaringBitmasks:   INCLUDE "gfx/pokemon/ursaring/bitmask.asm"
SlugmaBitmasks:     INCLUDE "gfx/pokemon/slugma/bitmask.asm"
MagcargoBitmasks:   INCLUDE "gfx/pokemon/magcargo/bitmask.asm"
SwinubBitmasks:     INCLUDE "gfx/pokemon/swinub/bitmask.asm"
PiloswineBitmasks:  INCLUDE "gfx/pokemon/piloswine/bitmask.asm"
RemoraidBitmasks:   INCLUDE "gfx/pokemon/remoraid/bitmask.asm"
OctilleryBitmasks:  INCLUDE "gfx/pokemon/octillery/bitmask.asm"
DelibirdBitmasks:   INCLUDE "gfx/pokemon/delibird/bitmask.asm"
MantineBitmasks:    INCLUDE "gfx/pokemon/mantine/bitmask.asm"
SkarmoryBitmasks:   INCLUDE "gfx/pokemon/skarmory/bitmask.asm"
HoundourBitmasks:   INCLUDE "gfx/pokemon/houndour/bitmask.asm"
HoundoomBitmasks:   INCLUDE "gfx/pokemon/houndoom/bitmask.asm"
KingdraBitmasks:    INCLUDE "gfx/pokemon/kingdra/bitmask.asm"
PhanpyBitmasks:     INCLUDE "gfx/pokemon/phanpy/bitmask.asm"
DonphanBitmasks:    INCLUDE "gfx/pokemon/donphan/bitmask.asm"
CLunasa2Bitmasks:   INCLUDE "gfx/pokemon/porygon2/bitmask.asm"
StantlerBitmasks:   INCLUDE "gfx/pokemon/stantler/bitmask.asm"
SmeargleBitmasks:   INCLUDE "gfx/pokemon/smeargle/bitmask.asm"
TyrogueBitmasks:    INCLUDE "gfx/pokemon/tyrogue/bitmask.asm"
HitmontopBitmasks:  INCLUDE "gfx/pokemon/hitmontop/bitmask.asm"
SmoochumBitmasks:   INCLUDE "gfx/pokemon/smoochum/bitmask.asm"
ElekidBitmasks:     INCLUDE "gfx/pokemon/elekid/bitmask.asm"
MagbyBitmasks:      INCLUDE "gfx/pokemon/magby/bitmask.asm"
MiltankBitmasks:    INCLUDE "gfx/pokemon/miltank/bitmask.asm"
BlisseyBitmasks:    INCLUDE "gfx/pokemon/blissey/bitmask.asm"
RaikouBitmasks:     INCLUDE "gfx/pokemon/raikou/bitmask.asm"
EnteiBitmasks:      INCLUDE "gfx/pokemon/entei/bitmask.asm"
SuicuneBitmasks:    INCLUDE "gfx/pokemon/suicune/bitmask.asm"
LarvitarBitmasks:   INCLUDE "gfx/pokemon/larvitar/bitmask.asm"
PupitarBitmasks:    INCLUDE "gfx/pokemon/pupitar/bitmask.asm"
TyranitarBitmasks:  INCLUDE "gfx/pokemon/tyranitar/bitmask.asm"
LugiaBitmasks:      INCLUDE "gfx/pokemon/lugia/bitmask.asm"
HoOhBitmasks:       INCLUDE "gfx/pokemon/ho_oh/bitmask.asm"
CelebiBitmasks:     INCLUDE "gfx/pokemon/celebi/bitmask.asm"
AzurillBitmasks:    INCLUDE "gfx/pokemon/azurill/bitmask.asm"
WynautBitmasks:     INCLUDE "gfx/pokemon/wynaut/bitmask.asm"
AmbipomBitmasks:    INCLUDE "gfx/pokemon/ambipom/bitmask.asm"
MismagiusBitmasks:  INCLUDE "gfx/pokemon/mismagius/bitmask.asm"
HonchkrowBitmasks:  INCLUDE "gfx/pokemon/honchkrow/bitmask.asm"
BonslyBitmasks:     INCLUDE "gfx/pokemon/bonsly/bitmask.asm"
MimeJrBitmasks:     INCLUDE "gfx/pokemon/mime_jr_/bitmask.asm"
HappinyBitmasks:    INCLUDE "gfx/pokemon/happiny/bitmask.asm"
MunchlaxBitmasks:   INCLUDE "gfx/pokemon/munchlax/bitmask.asm"
MantykeBitmasks:    INCLUDE "gfx/pokemon/mantyke/bitmask.asm"
WeavileBitmasks:    INCLUDE "gfx/pokemon/weavile/bitmask.asm"
MagnezoneBitmasks:  INCLUDE "gfx/pokemon/magnezone/bitmask.asm"
LickilickyBitmasks: INCLUDE "gfx/pokemon/lickilicky/bitmask.asm"
RhyperiorBitmasks:  INCLUDE "gfx/pokemon/rhyperior/bitmask.asm"
TangrowthBitmasks:  INCLUDE "gfx/pokemon/tangrowth/bitmask.asm"
ElectivireBitmasks: INCLUDE "gfx/pokemon/electivire/bitmask.asm"
MagmortarBitmasks:  INCLUDE "gfx/pokemon/magmortar/bitmask.asm"
TogekissBitmasks:   INCLUDE "gfx/pokemon/togekiss/bitmask.asm"
YanmegaBitmasks:    INCLUDE "gfx/pokemon/yanmega/bitmask.asm"
LeafeonBitmasks:    INCLUDE "gfx/pokemon/leafeon/bitmask.asm"
GlaceonBitmasks:    INCLUDE "gfx/pokemon/glaceon/bitmask.asm"
GliscorBitmasks:    INCLUDE "gfx/pokemon/gliscor/bitmask.asm"
MamoswineBitmasks:  INCLUDE "gfx/pokemon/mamoswine/bitmask.asm"
CLunasaZBitmasks:   INCLUDE "gfx/pokemon/porygon_z/bitmask.asm"
SylveonBitmasks:    INCLUDE "gfx/pokemon/sylveon/bitmask.asm"
PerrserkerBitmasks: INCLUDE "gfx/pokemon/perrserker/bitmask.asm"
CursolaBitmasks:    INCLUDE "gfx/pokemon/cursola/bitmask.asm"
SirfetchDBitmasks:  INCLUDE "gfx/pokemon/sirfetch_d/bitmask.asm"
MrRimeBitmasks:     INCLUDE "gfx/pokemon/mr__rime/bitmask.asm"
WyrdeerBitmasks:    INCLUDE "gfx/pokemon/wyrdeer/bitmask.asm"
KleavorBitmasks:    INCLUDE "gfx/pokemon/kleavor/bitmask.asm"
UrsalunaBitmasks:   INCLUDE "gfx/pokemon/ursaluna/bitmask.asm"
SneaslerBitmasks:   INCLUDE "gfx/pokemon/sneasler/bitmask.asm"
OverqwilBitmasks:   INCLUDE "gfx/pokemon/overqwil/bitmask.asm"
FarigirafBitmasks:  INCLUDE "gfx/pokemon/farigiraf/bitmask.asm"
ClodsireBitmasks:   INCLUDE "gfx/pokemon/clodsire/bitmask.asm"
AnnihilapeBitmasks: INCLUDE "gfx/pokemon/annihilape/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/pokemon/egg/bitmask.asm"

UnownABitmasks: INCLUDE "gfx/pokemon/unown_a/bitmask.asm"
UnownBBitmasks: INCLUDE "gfx/pokemon/unown_b/bitmask.asm"
UnownCBitmasks: INCLUDE "gfx/pokemon/unown_c/bitmask.asm"
UnownDBitmasks: INCLUDE "gfx/pokemon/unown_d/bitmask.asm"
UnownEBitmasks: INCLUDE "gfx/pokemon/unown_e/bitmask.asm"
UnownFBitmasks: INCLUDE "gfx/pokemon/unown_f/bitmask.asm"
UnownGBitmasks: INCLUDE "gfx/pokemon/unown_g/bitmask.asm"
UnownHBitmasks: INCLUDE "gfx/pokemon/unown_h/bitmask.asm"
UnownIBitmasks: INCLUDE "gfx/pokemon/unown_i/bitmask.asm"
UnownJBitmasks: INCLUDE "gfx/pokemon/unown_j/bitmask.asm"
UnownKBitmasks: INCLUDE "gfx/pokemon/unown_k/bitmask.asm"
UnownLBitmasks: INCLUDE "gfx/pokemon/unown_l/bitmask.asm"
UnownMBitmasks: INCLUDE "gfx/pokemon/unown_m/bitmask.asm"
UnownNBitmasks: INCLUDE "gfx/pokemon/unown_n/bitmask.asm"
UnownOBitmasks: INCLUDE "gfx/pokemon/unown_o/bitmask.asm"
UnownPBitmasks: INCLUDE "gfx/pokemon/unown_p/bitmask.asm"
UnownQBitmasks: INCLUDE "gfx/pokemon/unown_q/bitmask.asm"
UnownRBitmasks: INCLUDE "gfx/pokemon/unown_r/bitmask.asm"
UnownSBitmasks: INCLUDE "gfx/pokemon/unown_s/bitmask.asm"
UnownTBitmasks: INCLUDE "gfx/pokemon/unown_t/bitmask.asm"
UnownUBitmasks: INCLUDE "gfx/pokemon/unown_u/bitmask.asm"
UnownVBitmasks: INCLUDE "gfx/pokemon/unown_v/bitmask.asm"
UnownWBitmasks: INCLUDE "gfx/pokemon/unown_w/bitmask.asm"
UnownXBitmasks: INCLUDE "gfx/pokemon/unown_x/bitmask.asm"
UnownYBitmasks: INCLUDE "gfx/pokemon/unown_y/bitmask.asm"
UnownZBitmasks: INCLUDE "gfx/pokemon/unown_z/bitmask.asm"
UnownExclamationBitmasks: INCLUDE "gfx/pokemon/unown_exclamation/bitmask.asm"
UnownQuestionBitmasks:    INCLUDE "gfx/pokemon/unown_question/bitmask.asm"

PichuBitmasks: INCLUDE "gfx/pokemon/pichu/bitmask.asm"
PichuSpikyBitmasks: INCLUDE "gfx/pokemon/pichu_spiky/bitmask.asm"

KikuriJohtoBitmasks:  INCLUDE "gfx/pokemon/kikuri_johto/bitmask.asm"
KikuriKantoBitmasks:  INCLUDE "gfx/pokemon/kikuri_kanto/bitmask.asm"
KikuriKogaBitmasks:   INCLUDE "gfx/pokemon/kikuri_koga/bitmask.asm"
KikuriAgathaBitmasks: INCLUDE "gfx/pokemon/kikuri_agatha/bitmask.asm"
KikuriArianaBitmasks: INCLUDE "gfx/pokemon/kikuri_ariana/bitmask.asm"

LilyBlackBitmasks:     INCLUDE "gfx/pokemon/magikarp/bitmask.asm"
LilyBlackSkellyBitmasks:    INCLUDE "gfx/pokemon/magikarp_skelly/bitmask.asm"
LilyBlackCalico1Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico1/bitmask.asm"
LilyBlackCalico2Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico2/bitmask.asm"
LilyBlackCalico3Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico3/bitmask.asm"
LilyBlackTwoToneBitmasks:   INCLUDE "gfx/pokemon/magikarp_twotone/bitmask.asm"
LilyBlackOrcaBitmasks:      INCLUDE "gfx/pokemon/magikarp_orca/bitmask.asm"
LilyBlackDapplesBitmasks:   INCLUDE "gfx/pokemon/magikarp_dapples/bitmask.asm"
LilyBlackTigerBitmasks:     INCLUDE "gfx/pokemon/magikarp_tiger/bitmask.asm"
LilyBlackZebraBitmasks:     INCLUDE "gfx/pokemon/magikarp_zebra/bitmask.asm"
LilyBlackStripeBitmasks:    INCLUDE "gfx/pokemon/magikarp_stripe/bitmask.asm"
LilyBlackBubblesBitmasks:   INCLUDE "gfx/pokemon/magikarp_bubbles/bitmask.asm"
LilyBlackDiamondsBitmasks:  INCLUDE "gfx/pokemon/magikarp_diamonds/bitmask.asm"
LilyBlackPatchesBitmasks:   INCLUDE "gfx/pokemon/magikarp_patches/bitmask.asm"
LilyBlackForehead1Bitmasks: INCLUDE "gfx/pokemon/magikarp_forehead1/bitmask.asm"
LilyBlackMask1Bitmasks:     INCLUDE "gfx/pokemon/magikarp_mask1/bitmask.asm"
LilyBlackForehead2Bitmasks: INCLUDE "gfx/pokemon/magikarp_forehead2/bitmask.asm"
LilyBlackMask2Bitmasks:     INCLUDE "gfx/pokemon/magikarp_mask2/bitmask.asm"
LilyBlackSaucyBitmasks:     INCLUDE "gfx/pokemon/magikarp_saucy/bitmask.asm"
LilyBlackRaindropBitmasks:  INCLUDE "gfx/pokemon/magikarp_raindrop/bitmask.asm"

DudunsparceTwoSegmentBitmasks:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/bitmask.asm"
DudunsparceThreeSegmentBitmasks: INCLUDE "gfx/pokemon/dudunsparce_three_segment/bitmask.asm"

ELilyBlackBitmasks: INCLUDE "gfx/pokemon/gyarados/bitmask.asm"
ELilyBlackRedBitmasks:   INCLUDE "gfx/pokemon/gyarados_red/bitmask.asm"

SuikaBitmasks:   INCLUDE "gfx/pokemon/mewtwo/bitmask.asm"
SuikaArmoredBitmasks: INCLUDE "gfx/pokemon/mewtwo_armored/bitmask.asm"

CElisBitmasks:  INCLUDE "gfx/pokemon/celis/bitmask.asm"

CSarielBitmasks:  INCLUDE "gfx/pokemon/csariel/bitmask.asm"

SarielBitmasks:  INCLUDE "gfx/pokemon/sariel/bitmask.asm"

CEllenBitmasks:  INCLUDE "gfx/pokemon/cellen/bitmask.asm"

CChiyuriBitmasks:  INCLUDE "gfx/pokemon/cchiyuri/bitmask.asm"

ChiyuriBitmasks:  INCLUDE "gfx/pokemon/chiyuri/bitmask.asm"

CYumemiBitmasks:  INCLUDE "gfx/pokemon/cyumemi/bitmask.asm"

CSaraBitmasks:  INCLUDE "gfx/pokemon/csara/bitmask.asm"

SaraBitmasks:  INCLUDE "gfx/pokemon/sara/bitmask.asm"

EYukiBitmasks:  INCLUDE "gfx/pokemon/eyuki/bitmask.asm"

CYumekoBitmasks:  INCLUDE "gfx/pokemon/cyumeko/bitmask.asm"

SCirnoBitmasks:  INCLUDE "gfx/pokemon/scirno/bitmask.asm"

MeilingBitmasks:  INCLUDE "gfx/pokemon/meiling/bitmask.asm"

CLuizeBitmasks:    INCLUDE "gfx/pokemon/cluize/bitmask.asm"

LuizeBitmasks:    INCLUDE "gfx/pokemon/luize/bitmask.asm"

DLuizeBitmasks:   INCLUDE "gfx/pokemon/dluize/bitmask.asm"

CAliceBitmasks:    INCLUDE "gfx/pokemon/calice/bitmask.asm"

CMaiBitmasks:     INCLUDE "gfx/pokemon/cmai/bitmask.asm"

CPatchouliBitmasks:    INCLUDE "gfx/pokemon/cpatchouli/bitmask.asm"

MrMimeBitmasks:    INCLUDE "gfx/pokemon/mr__mime/bitmask.asm"

RanBitmasks:    INCLUDE "gfx/pokemon/articuno/bitmask.asm"

TRanBitmasks:    INCLUDE "gfx/pokemon/zapdos/bitmask.asm"

CYukariBitmasks:    INCLUDE "gfx/pokemon/moltres/bitmask.asm"

SlowkingBitmasks:    INCLUDE "gfx/pokemon/slowking/bitmask.asm"

CorsolaBitmasks:    INCLUDE "gfx/pokemon/corsola/bitmask.asm"

CKurumiBitmasks:   INCLUDE "gfx/pokemon/ckurumi/bitmask.asm"

DDaichanBitmasks:   INCLUDE "gfx/pokemon/ddaichan/bitmask.asm"

CCirnoBitmasks:   INCLUDE "gfx/pokemon/ccirno/bitmask.asm"

TReisenBitmasks:   INCLUDE "gfx/pokemon/treisen/bitmask.asm"

QwilfishBitmasks:   INCLUDE "gfx/pokemon/qwilfish/bitmask.asm"

SneaselBitmasks:   INCLUDE "gfx/pokemon/sneasel/bitmask.asm"

WooperBitmasks:    INCLUDE "gfx/pokemon/wooper/bitmask.asm"
CLilyBlackBitmasks:        INCLUDE "gfx/pokemon/tauros/bitmask.asm"
