CReimuBitmasks:  INCLUDE "gfx/pokemon/creimu/bitmask.asm"
ReimuBitmasks:    INCLUDE "gfx/pokemon/reimu/bitmask.asm"
TReimuBitmasks:   INCLUDE "gfx/pokemon/treimu/bitmask.asm"
CMarisaBitmasks: INCLUDE "gfx/pokemon/cmarisa/bitmask.asm"
MarisaBitmasks: INCLUDE "gfx/pokemon/marisa/bitmask.asm"
AMarisaBitmasks:  INCLUDE "gfx/pokemon/amarisa/bitmask.asm"
CSakuyaBitmasks:   INCLUDE "gfx/pokemon/csakuya/bitmask.asm"
SakuyaBitmasks:  INCLUDE "gfx/pokemon/sakuya/bitmask.asm"
HSakuyaBitmasks:  INCLUDE "gfx/pokemon/hsakuya/bitmask.asm"
CGyokuBitmasks:   INCLUDE "gfx/pokemon/cgyoku/bitmask.asm"
MGyokuBitmasks:    INCLUDE "gfx/pokemon/mgyoku/bitmask.asm"
FGyokuBitmasks: INCLUDE "gfx/pokemon/fgyoku/bitmask.asm"
OGyokuBitmasks:     INCLUDE "gfx/pokemon/ogyoku/bitmask.asm"
CMaganBitmasks:     INCLUDE "gfx/pokemon/cmagan/bitmask.asm"
MaganBitmasks:   INCLUDE "gfx/pokemon/magan/bitmask.asm"
CMimaBitmasks:  INCLUDE "gfx/pokemon/cmima/bitmask.asm"
MimaBitmasks:    INCLUDE "gfx/pokemon/mima/bitmask.asm"
ElisBitmasks:    INCLUDE "gfx/pokemon/elis/bitmask.asm"
CKikuriBitmasks:      INCLUDE "gfx/pokemon/ckikuri/bitmask.asm"
CKongaraBitmasks:   INCLUDE "gfx/pokemon/ckongara/bitmask.asm"
KongaraBitmasks:   INCLUDE "gfx/pokemon/kongara/bitmask.asm"
CRikaBitmasks:   INCLUDE "gfx/pokemon/crika/bitmask.asm"
RikaBitmasks:   INCLUDE "gfx/pokemon/rika/bitmask.asm"
ARikaBitmasks:   INCLUDE "gfx/pokemon/arika/bitmask.asm"
CMeiraBitmasks:   INCLUDE "gfx/pokemon/cmeira/bitmask.asm"
MeiraBitmasks:   INCLUDE "gfx/pokemon/meira/bitmask.asm"
EllenBitmasks: INCLUDE "gfx/pokemon/ellen/bitmask.asm"
CKotohimeBitmasks:      INCLUDE "gfx/pokemon/ckotohime/bitmask.asm"
KotohimeBitmasks:     INCLUDE "gfx/pokemon/kotohime/bitmask.asm"
CKanaBitmasks:      INCLUDE "gfx/pokemon/ckana/bitmask.asm"
KanaBitmasks:  INCLUDE "gfx/pokemon/kana/bitmask.asm"
CRikakoBitmasks:   INCLUDE "gfx/pokemon/crikako/bitmask.asm"
RikakoBitmasks:    INCLUDE "gfx/pokemon/rikako/bitmask.asm"
YumemiBitmasks:    INCLUDE "gfx/pokemon/yumemi/bitmask.asm"
COrangeBitmasks:     INCLUDE "gfx/pokemon/corange/bitmask.asm"
OrangeBitmasks:   INCLUDE "gfx/pokemon/orange/bitmask.asm"
KurumiBitmasks:    INCLUDE "gfx/pokemon/kurumi/bitmask.asm"
CEllyBitmasks:  INCLUDE "gfx/pokemon/celly/bitmask.asm"
EllyBitmasks:       INCLUDE "gfx/pokemon/elly/bitmask.asm"
CYukaBitmasks:   INCLUDE "gfx/pokemon/cyuka/bitmask.asm"
YukaBitmasks:     INCLUDE "gfx/pokemon/yuka/bitmask.asm"
AYukaBitmasks:    INCLUDE "gfx/pokemon/ayuka/bitmask.asm"
CMugetsuBitmasks:    INCLUDE "gfx/pokemon/cmugetsu/bitmask.asm"
MugetsuBitmasks: INCLUDE "gfx/pokemon/mugetsu/bitmask.asm"
CGengetsuBitmasks: INCLUDE "gfx/pokemon/cgengetsu/bitmask.asm"
GengetsuBitmasks:  INCLUDE "gfx/pokemon/gengetsu/bitmask.asm"
AliceBitmasks:  INCLUDE "gfx/pokemon/alice/bitmask.asm"
AAliceBitmasks:   INCLUDE "gfx/pokemon/aalice/bitmask.asm"
MaiBitmasks:      INCLUDE "gfx/pokemon/mai/bitmask.asm"
CYukiBitmasks:       INCLUDE "gfx/pokemon/cyuki/bitmask.asm"
YukiBitmasks:    INCLUDE "gfx/pokemon/yuki/bitmask.asm"
YumekoBitmasks:   INCLUDE "gfx/pokemon/yumeko/bitmask.asm"
CShinkiBitmasks:     INCLUDE "gfx/pokemon/cshinki/bitmask.asm"
ShinkiBitmasks:    INCLUDE "gfx/pokemon/shinki/bitmask.asm"
CRumiaBitmasks:       INCLUDE "gfx/pokemon/crumia/bitmask.asm"
RumiaBitmasks:    INCLUDE "gfx/pokemon/rumia/bitmask.asm"
ARumiaBitmasks:      INCLUDE "gfx/pokemon/arumia/bitmask.asm"
CDaichanBitmasks:     INCLUDE "gfx/pokemon/cdaichan/bitmask.asm"
DaichanBitmasks:    INCLUDE "gfx/pokemon/daichan/bitmask.asm"
CirnoBitmasks:  INCLUDE "gfx/pokemon/cirno/bitmask.asm"
CMeilingBitmasks:     INCLUDE "gfx/pokemon/cmeiling/bitmask.asm"
AMeilingBitmasks:  INCLUDE "gfx/pokemon/ameiling/bitmask.asm"
CKoakumaBitmasks: INCLUDE "gfx/pokemon/ckoakuma/bitmask.asm"
KoakumaBitmasks:  INCLUDE "gfx/pokemon/koakuma/bitmask.asm"
HKoakumaBitmasks:    INCLUDE "gfx/pokemon/hkoakuma/bitmask.asm"
PatchouliBitmasks:    INCLUDE "gfx/pokemon/patchouli/bitmask.asm"
TPatchouliBitmasks:     INCLUDE "gfx/pokemon/tpatchouli/bitmask.asm"
CRemiliaBitmasks:    INCLUDE "gfx/pokemon/cremilia/bitmask.asm"
RemiliaBitmasks:    INCLUDE "gfx/pokemon/remilia/bitmask.asm"
SRemiliaBitmasks: INCLUDE "gfx/pokemon/sremilia/bitmask.asm"
CFlandreBitmasks:     INCLUDE "gfx/pokemon/cflandre/bitmask.asm"
FlandreBitmasks:     INCLUDE "gfx/pokemon/flandre/bitmask.asm"
AFlandreBitmasks:    INCLUDE "gfx/pokemon/aflandre/bitmask.asm"
CLettyBitmasks:    INCLUDE "gfx/pokemon/cletty/bitmask.asm"
LettyBitmasks:     INCLUDE "gfx/pokemon/letty/bitmask.asm"
DLettyBitmasks:    INCLUDE "gfx/pokemon/dletty/bitmask.asm"
ChenBitmasks:    INCLUDE "gfx/pokemon/chen/bitmask.asm"
HChenBitmasks:       INCLUDE "gfx/pokemon/hchen/bitmask.asm"
CLilyWhiteBitmasks: INCLUDE "gfx/pokemon/clilywhite/bitmask.asm"
LilyWhiteBitmasks:     INCLUDE "gfx/pokemon/lilywhite/bitmask.asm"
DLilyWhiteBitmasks:     INCLUDE "gfx/pokemon/dlilywhite/bitmask.asm"
CLyricaBitmasks:     INCLUDE "gfx/pokemon/clyrica/bitmask.asm"
LyricaBitmasks:      INCLUDE "gfx/pokemon/lyrica/bitmask.asm"
TLyricaBitmasks:      INCLUDE "gfx/pokemon/tlyrica/bitmask.asm"
CMerlinBitmasks:   INCLUDE "gfx/pokemon/cmerlin/bitmask.asm"
MerlinBitmasks:    INCLUDE "gfx/pokemon/merlin/bitmask.asm"
SMerlinBitmasks:    INCLUDE "gfx/pokemon/smerlin/bitmask.asm"
CLunasaBitmasks:    INCLUDE "gfx/pokemon/clunasa/bitmask.asm"
LunasaBitmasks:    INCLUDE "gfx/pokemon/lunasa/bitmask.asm"
ALunasaBitmasks:    INCLUDE "gfx/pokemon/alunasa/bitmask.asm"
CYuyukoBitmasks:     INCLUDE "gfx/pokemon/cyuyuko/bitmask.asm"
YuyukoBitmasks:   INCLUDE "gfx/pokemon/yuyuko/bitmask.asm"
AYuyukoBitmasks: INCLUDE "gfx/pokemon/ayuyuko/bitmask.asm"
CRanBitmasks:    INCLUDE "gfx/pokemon/cran/bitmask.asm"
YukariBitmasks:    INCLUDE "gfx/pokemon/yukari/bitmask.asm"
TYukariBitmasks:  INCLUDE "gfx/pokemon/tyukari/bitmask.asm"
CSuikaBitmasks:  INCLUDE "gfx/pokemon/csuika/bitmask.asm"
TSuikaBitmasks:        INCLUDE "gfx/pokemon/tsuika/bitmask.asm"
CYoumuBitmasks:  INCLUDE "gfx/pokemon/cyoumu/bitmask.asm"
YoumuBitmasks:    INCLUDE "gfx/pokemon/youmu/bitmask.asm"
SYoumuBitmasks:   INCLUDE "gfx/pokemon/syoumu/bitmask.asm"
CReisenBitmasks:  INCLUDE "gfx/pokemon/creisen/bitmask.asm"
ReisenBitmasks:    INCLUDE "gfx/pokemon/reisen/bitmask.asm"
CSanaeBitmasks:   INCLUDE "gfx/pokemon/csanae/bitmask.asm"
SanaeBitmasks:   INCLUDE "gfx/pokemon/sanae/bitmask.asm"
DSanaeBitmasks: INCLUDE "gfx/pokemon/dsanae/bitmask.asm"
CWriggleBitmasks:    INCLUDE "gfx/pokemon/cwriggle/bitmask.asm"
WriggleBitmasks:     INCLUDE "gfx/pokemon/wriggle/bitmask.asm"
SWriggleBitmasks:   INCLUDE "gfx/pokemon/swriggle/bitmask.asm"
CMystiaBitmasks:    INCLUDE "gfx/pokemon/cmystia/bitmask.asm"
MystiaBitmasks:     INCLUDE "gfx/pokemon/mystia/bitmask.asm"
TMystiaBitmasks:     INCLUDE "gfx/pokemon/tmystia/bitmask.asm"
CKeineBitmasks:   INCLUDE "gfx/pokemon/ckeine/bitmask.asm"
KeineBitmasks:    INCLUDE "gfx/pokemon/keine/bitmask.asm"
AKeineBitmasks:     INCLUDE "gfx/pokemon/akeine/bitmask.asm"
CTeiBitmasks:   INCLUDE "gfx/pokemon/ctei/bitmask.asm"
TeiBitmasks:    INCLUDE "gfx/pokemon/tei/bitmask.asm"
CEirinBitmasks:     INCLUDE "gfx/pokemon/ceirin/bitmask.asm"
EirinBitmasks:  INCLUDE "gfx/pokemon/eirin/bitmask.asm"
TEirinBitmasks:     INCLUDE "gfx/pokemon/teirin/bitmask.asm"
CKaguyaBitmasks:    INCLUDE "gfx/pokemon/ckaguya/bitmask.asm"
KaguyaBitmasks:       INCLUDE "gfx/pokemon/kaguya/bitmask.asm"
TKaguyaBitmasks:       INCLUDE "gfx/pokemon/tkaguya/bitmask.asm"
CMokouBitmasks:     INCLUDE "gfx/pokemon/cmokou/bitmask.asm"
MokouBitmasks:    INCLUDE "gfx/pokemon/mokou/bitmask.asm"
AMokouBitmasks:   INCLUDE "gfx/pokemon/amokou/bitmask.asm"
CAyaBitmasks:  INCLUDE "gfx/pokemon/caya/bitmask.asm"
CMedicineBitmasks:  INCLUDE "gfx/pokemon/cmedicine/bitmask.asm"
AyaBitmasks:     INCLUDE "gfx/pokemon/aya/bitmask.asm"
SAyaBitmasks:  INCLUDE "gfx/pokemon/saya/bitmask.asm"
MedicineBitmasks:   INCLUDE "gfx/pokemon/medicine/bitmask.asm"
AMedicineBitmasks:     INCLUDE "gfx/pokemon/amedicine/bitmask.asm"
CKomachiBitmasks:   INCLUDE "gfx/pokemon/ckomachi/bitmask.asm"
KomachiBitmasks:   INCLUDE "gfx/pokemon/komachi/bitmask.asm"
AKomachiBitmasks:      INCLUDE "gfx/pokemon/akomachi/bitmask.asm"
CEikiBitmasks:    INCLUDE "gfx/pokemon/ceiki/bitmask.asm"
EikiBitmasks:   INCLUDE "gfx/pokemon/eiki/bitmask.asm"
AEikiBitmasks:      INCLUDE "gfx/pokemon/aeiki/bitmask.asm"
ShizuhaBitmasks:   INCLUDE "gfx/pokemon/shizuha/bitmask.asm"
SShizuhaBitmasks:     INCLUDE "gfx/pokemon/sshizuha/bitmask.asm"
CMinorikoBitmasks:    INCLUDE "gfx/pokemon/cminoriko/bitmask.asm"
MinorikoBitmasks:    INCLUDE "gfx/pokemon/minoriko/bitmask.asm"
CHinaBitmasks: INCLUDE "gfx/pokemon/china/bitmask.asm"
AHinaBitmasks:  INCLUDE "gfx/pokemon/ahina/bitmask.asm"
CNitoriBitmasks:  INCLUDE "gfx/pokemon/cnitori/bitmask.asm"
NitoriBitmasks:     INCLUDE "gfx/pokemon/nitori/bitmask.asm"
ANitoriBitmasks: INCLUDE "gfx/pokemon/anitori/bitmask.asm"
CMomijiBitmasks:  INCLUDE "gfx/pokemon/cmomiji/bitmask.asm"
MomijiBitmasks:     INCLUDE "gfx/pokemon/momiji/bitmask.asm"
CKanakoBitmasks:    INCLUDE "gfx/pokemon/ckanako/bitmask.asm"
KanakoBitmasks:   INCLUDE "gfx/pokemon/kanako/bitmask.asm"
AKanakoBitmasks:   INCLUDE "gfx/pokemon/akanako/bitmask.asm"
SuwakoBitmasks:     INCLUDE "gfx/pokemon/suwako/bitmask.asm"
DSuwakoBitmasks:    INCLUDE "gfx/pokemon/dsuwako/bitmask.asm"
CIkuBitmasks:  INCLUDE "gfx/pokemon/ciku/bitmask.asm"
AIkuBitmasks:  INCLUDE "gfx/pokemon/aiku/bitmask.asm"
CTenshiBitmasks:   INCLUDE "gfx/pokemon/ctenshi/bitmask.asm"
TenshiBitmasks:     INCLUDE "gfx/pokemon/tenshi/bitmask.asm"
STenshiBitmasks:   INCLUDE "gfx/pokemon/stenshi/bitmask.asm"
SwinubBitmasks:     INCLUDE "gfx/pokemon/swinub/bitmask.asm"
PiloswineBitmasks:  INCLUDE "gfx/pokemon/piloswine/bitmask.asm"
RemoraidBitmasks:   INCLUDE "gfx/pokemon/remoraid/bitmask.asm"
OctilleryBitmasks:  INCLUDE "gfx/pokemon/octillery/bitmask.asm"
DelibirdBitmasks:   INCLUDE "gfx/pokemon/delibird/bitmask.asm"
MantineBitmasks:    INCLUDE "gfx/pokemon/mantine/bitmask.asm"
SkarmoryBitmasks:   INCLUDE "gfx/pokemon/skarmory/bitmask.asm"
HoundourBitmasks:   INCLUDE "gfx/pokemon/houndour/bitmask.asm"
HoundoomBitmasks:   INCLUDE "gfx/pokemon/houndoom/bitmask.asm"
KingdraBitmasks:    INCLUDE "gfx/pokemon/kingdra/bitmask.asm"
PhanpyBitmasks:     INCLUDE "gfx/pokemon/phanpy/bitmask.asm"
DonphanBitmasks:    INCLUDE "gfx/pokemon/donphan/bitmask.asm"
CLunasa2Bitmasks:   INCLUDE "gfx/pokemon/clunasa2/bitmask.asm"
StantlerBitmasks:   INCLUDE "gfx/pokemon/stantler/bitmask.asm"
SmeargleBitmasks:   INCLUDE "gfx/pokemon/smeargle/bitmask.asm"
TyrogueBitmasks:    INCLUDE "gfx/pokemon/tyrogue/bitmask.asm"
HitmontopBitmasks:  INCLUDE "gfx/pokemon/hitmontop/bitmask.asm"
SmoochumBitmasks:   INCLUDE "gfx/pokemon/smoochum/bitmask.asm"
ElekidBitmasks:     INCLUDE "gfx/pokemon/elekid/bitmask.asm"
MagbyBitmasks:      INCLUDE "gfx/pokemon/magby/bitmask.asm"
MiltankBitmasks:    INCLUDE "gfx/pokemon/miltank/bitmask.asm"
BlisseyBitmasks:    INCLUDE "gfx/pokemon/blissey/bitmask.asm"
RaikouBitmasks:     INCLUDE "gfx/pokemon/raikou/bitmask.asm"
EnteiBitmasks:      INCLUDE "gfx/pokemon/entei/bitmask.asm"
SuicuneBitmasks:    INCLUDE "gfx/pokemon/suicune/bitmask.asm"
LarvitarBitmasks:   INCLUDE "gfx/pokemon/larvitar/bitmask.asm"
PupitarBitmasks:    INCLUDE "gfx/pokemon/pupitar/bitmask.asm"
TyranitarBitmasks:  INCLUDE "gfx/pokemon/tyranitar/bitmask.asm"
LugiaBitmasks:      INCLUDE "gfx/pokemon/lugia/bitmask.asm"
HoOhBitmasks:       INCLUDE "gfx/pokemon/ho_oh/bitmask.asm"
CelebiBitmasks:     INCLUDE "gfx/pokemon/celebi/bitmask.asm"
AzurillBitmasks:    INCLUDE "gfx/pokemon/azurill/bitmask.asm"
WynautBitmasks:     INCLUDE "gfx/pokemon/wynaut/bitmask.asm"
AmbipomBitmasks:    INCLUDE "gfx/pokemon/ambipom/bitmask.asm"
MismagiusBitmasks:  INCLUDE "gfx/pokemon/mismagius/bitmask.asm"
HonchkrowBitmasks:  INCLUDE "gfx/pokemon/honchkrow/bitmask.asm"
BonslyBitmasks:     INCLUDE "gfx/pokemon/bonsly/bitmask.asm"
MimeJrBitmasks:     INCLUDE "gfx/pokemon/mime_jr_/bitmask.asm"
HappinyBitmasks:    INCLUDE "gfx/pokemon/happiny/bitmask.asm"
MunchlaxBitmasks:   INCLUDE "gfx/pokemon/munchlax/bitmask.asm"
MantykeBitmasks:    INCLUDE "gfx/pokemon/mantyke/bitmask.asm"
WeavileBitmasks:    INCLUDE "gfx/pokemon/weavile/bitmask.asm"
MagnezoneBitmasks:  INCLUDE "gfx/pokemon/magnezone/bitmask.asm"
LickilickyBitmasks: INCLUDE "gfx/pokemon/lickilicky/bitmask.asm"
RhyperiorBitmasks:  INCLUDE "gfx/pokemon/rhyperior/bitmask.asm"
TangrowthBitmasks:  INCLUDE "gfx/pokemon/tangrowth/bitmask.asm"
ElectivireBitmasks: INCLUDE "gfx/pokemon/electivire/bitmask.asm"
MagmortarBitmasks:  INCLUDE "gfx/pokemon/magmortar/bitmask.asm"
TogekissBitmasks:   INCLUDE "gfx/pokemon/togekiss/bitmask.asm"
YanmegaBitmasks:    INCLUDE "gfx/pokemon/yanmega/bitmask.asm"
LeafeonBitmasks:    INCLUDE "gfx/pokemon/leafeon/bitmask.asm"
GlaceonBitmasks:    INCLUDE "gfx/pokemon/glaceon/bitmask.asm"
AMomijiBitmasks:    INCLUDE "gfx/pokemon/amomiji/bitmask.asm"
MamoswineBitmasks:  INCLUDE "gfx/pokemon/mamoswine/bitmask.asm"
CLunasaZBitmasks:   INCLUDE "gfx/pokemon/clunasa_z/bitmask.asm"
SylveonBitmasks:    INCLUDE "gfx/pokemon/sylveon/bitmask.asm"
PerrserkerBitmasks: INCLUDE "gfx/pokemon/perrserker/bitmask.asm"
CursolaBitmasks:    INCLUDE "gfx/pokemon/cursola/bitmask.asm"
SirfetchDBitmasks:  INCLUDE "gfx/pokemon/sirfetch_d/bitmask.asm"
MrRimeBitmasks:     INCLUDE "gfx/pokemon/mr__rime/bitmask.asm"
WyrdeerBitmasks:    INCLUDE "gfx/pokemon/wyrdeer/bitmask.asm"
KleavorBitmasks:    INCLUDE "gfx/pokemon/kleavor/bitmask.asm"
UrsalunaBitmasks:   INCLUDE "gfx/pokemon/ursaluna/bitmask.asm"
SneaslerBitmasks:   INCLUDE "gfx/pokemon/sneasler/bitmask.asm"
OverqwilBitmasks:   INCLUDE "gfx/pokemon/overqwil/bitmask.asm"
FarigirafBitmasks:  INCLUDE "gfx/pokemon/farigiraf/bitmask.asm"
ClodsireBitmasks:   INCLUDE "gfx/pokemon/clodsire/bitmask.asm"
AnnihilapeBitmasks: INCLUDE "gfx/pokemon/annihilape/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/pokemon/egg/bitmask.asm"

HinaABitmasks: INCLUDE "gfx/pokemon/hina_a/bitmask.asm"
HinaBBitmasks: INCLUDE "gfx/pokemon/hina_b/bitmask.asm"
HinaCBitmasks: INCLUDE "gfx/pokemon/hina_c/bitmask.asm"
HinaDBitmasks: INCLUDE "gfx/pokemon/hina_d/bitmask.asm"
HinaEBitmasks: INCLUDE "gfx/pokemon/hina_e/bitmask.asm"
HinaFBitmasks: INCLUDE "gfx/pokemon/hina_f/bitmask.asm"
HinaGBitmasks: INCLUDE "gfx/pokemon/hina_g/bitmask.asm"
HinaHBitmasks: INCLUDE "gfx/pokemon/hina_h/bitmask.asm"
HinaIBitmasks: INCLUDE "gfx/pokemon/hina_i/bitmask.asm"
HinaJBitmasks: INCLUDE "gfx/pokemon/hina_j/bitmask.asm"
HinaKBitmasks: INCLUDE "gfx/pokemon/hina_k/bitmask.asm"
HinaLBitmasks: INCLUDE "gfx/pokemon/hina_l/bitmask.asm"
HinaMBitmasks: INCLUDE "gfx/pokemon/hina_m/bitmask.asm"
HinaNBitmasks: INCLUDE "gfx/pokemon/hina_n/bitmask.asm"
HinaOBitmasks: INCLUDE "gfx/pokemon/hina_o/bitmask.asm"
HinaPBitmasks: INCLUDE "gfx/pokemon/hina_p/bitmask.asm"
HinaQBitmasks: INCLUDE "gfx/pokemon/hina_q/bitmask.asm"
HinaRBitmasks: INCLUDE "gfx/pokemon/hina_r/bitmask.asm"
HinaSBitmasks: INCLUDE "gfx/pokemon/hina_s/bitmask.asm"
HinaTBitmasks: INCLUDE "gfx/pokemon/hina_t/bitmask.asm"
HinaUBitmasks: INCLUDE "gfx/pokemon/hina_u/bitmask.asm"
HinaVBitmasks: INCLUDE "gfx/pokemon/hina_v/bitmask.asm"
HinaWBitmasks: INCLUDE "gfx/pokemon/hina_w/bitmask.asm"
HinaXBitmasks: INCLUDE "gfx/pokemon/hina_x/bitmask.asm"
HinaYBitmasks: INCLUDE "gfx/pokemon/hina_y/bitmask.asm"
HinaZBitmasks: INCLUDE "gfx/pokemon/hina_z/bitmask.asm"
HinaExclamationBitmasks: INCLUDE "gfx/pokemon/hina_exclamation/bitmask.asm"
HinaQuestionBitmasks:    INCLUDE "gfx/pokemon/hina_question/bitmask.asm"

TTeiBitmasks: INCLUDE "gfx/pokemon/ttei/bitmask.asm"
TTeiSpikyBitmasks: INCLUDE "gfx/pokemon/ttei_spiky/bitmask.asm"

KikuriJohtoBitmasks:  INCLUDE "gfx/pokemon/kikuri_johto/bitmask.asm"
KikuriKantoBitmasks:  INCLUDE "gfx/pokemon/kikuri_kanto/bitmask.asm"
KikuriKogaBitmasks:   INCLUDE "gfx/pokemon/kikuri_koga/bitmask.asm"
KikuriAgathaBitmasks: INCLUDE "gfx/pokemon/kikuri_agatha/bitmask.asm"
KikuriArianaBitmasks: INCLUDE "gfx/pokemon/kikuri_ariana/bitmask.asm"

LilyBlackBitmasks:     INCLUDE "gfx/pokemon/lilyblack/bitmask.asm"
LilyBlackSkellyBitmasks:    INCLUDE "gfx/pokemon/lilyblack_skelly/bitmask.asm"
LilyBlackCalico1Bitmasks:   INCLUDE "gfx/pokemon/lilyblack_calico1/bitmask.asm"
LilyBlackCalico2Bitmasks:   INCLUDE "gfx/pokemon/lilyblack_calico2/bitmask.asm"
LilyBlackCalico3Bitmasks:   INCLUDE "gfx/pokemon/lilyblack_calico3/bitmask.asm"
LilyBlackTwoToneBitmasks:   INCLUDE "gfx/pokemon/lilyblack_twotone/bitmask.asm"
LilyBlackOrcaBitmasks:      INCLUDE "gfx/pokemon/lilyblack_orca/bitmask.asm"
LilyBlackDapplesBitmasks:   INCLUDE "gfx/pokemon/lilyblack_dapples/bitmask.asm"
LilyBlackTigerBitmasks:     INCLUDE "gfx/pokemon/lilyblack_tiger/bitmask.asm"
LilyBlackZebraBitmasks:     INCLUDE "gfx/pokemon/lilyblack_zebra/bitmask.asm"
LilyBlackStripeBitmasks:    INCLUDE "gfx/pokemon/lilyblack_stripe/bitmask.asm"
LilyBlackBubblesBitmasks:   INCLUDE "gfx/pokemon/lilyblack_bubbles/bitmask.asm"
LilyBlackDiamondsBitmasks:  INCLUDE "gfx/pokemon/lilyblack_diamonds/bitmask.asm"
LilyBlackPatchesBitmasks:   INCLUDE "gfx/pokemon/lilyblack_patches/bitmask.asm"
LilyBlackForehead1Bitmasks: INCLUDE "gfx/pokemon/lilyblack_forehead1/bitmask.asm"
LilyBlackMask1Bitmasks:     INCLUDE "gfx/pokemon/lilyblack_mask1/bitmask.asm"
LilyBlackForehead2Bitmasks: INCLUDE "gfx/pokemon/lilyblack_forehead2/bitmask.asm"
LilyBlackMask2Bitmasks:     INCLUDE "gfx/pokemon/lilyblack_mask2/bitmask.asm"
LilyBlackSaucyBitmasks:     INCLUDE "gfx/pokemon/lilyblack_saucy/bitmask.asm"
LilyBlackRaindropBitmasks:  INCLUDE "gfx/pokemon/lilyblack_raindrop/bitmask.asm"

DucmomijiTwoSegmentBitmasks:   INCLUDE "gfx/pokemon/placethm_two_segment/bitmask.asm"
DucmomijiThreeSegmentBitmasks: INCLUDE "gfx/pokemon/placethm_three_segment/bitmask.asm"

SLilyBlackBitmasks: INCLUDE "gfx/pokemon/slilyblack/bitmask.asm"
SLilyBlackRedBitmasks:   INCLUDE "gfx/pokemon/slilyblack_red/bitmask.asm"

SuikaBitmasks:   INCLUDE "gfx/pokemon/suika/bitmask.asm"
SuikaArmoredBitmasks: INCLUDE "gfx/pokemon/suika_armored/bitmask.asm"

CElisBitmasks:  INCLUDE "gfx/pokemon/celis/bitmask.asm"

CSarielBitmasks:  INCLUDE "gfx/pokemon/csariel/bitmask.asm"

SarielBitmasks:  INCLUDE "gfx/pokemon/sariel/bitmask.asm"

CEllenBitmasks:  INCLUDE "gfx/pokemon/cellen/bitmask.asm"

CChiyuriBitmasks:  INCLUDE "gfx/pokemon/cchiyuri/bitmask.asm"

ChiyuriBitmasks:  INCLUDE "gfx/pokemon/chiyuri/bitmask.asm"

CYumemiBitmasks:  INCLUDE "gfx/pokemon/cyumemi/bitmask.asm"

CSaraBitmasks:  INCLUDE "gfx/pokemon/csara/bitmask.asm"

SaraBitmasks:  INCLUDE "gfx/pokemon/sara/bitmask.asm"


CYumekoBitmasks:  INCLUDE "gfx/pokemon/cyumeko/bitmask.asm"

SCirnoBitmasks:  INCLUDE "gfx/pokemon/scirno/bitmask.asm"

MeilingBitmasks:  INCLUDE "gfx/pokemon/meiling/bitmask.asm"

CLuizeBitmasks:    INCLUDE "gfx/pokemon/cluize/bitmask.asm"

LuizeBitmasks:    INCLUDE "gfx/pokemon/luize/bitmask.asm"

DLuizeBitmasks:   INCLUDE "gfx/pokemon/dluize/bitmask.asm"

CAliceBitmasks:    INCLUDE "gfx/pokemon/calice/bitmask.asm"

CMaiBitmasks:     INCLUDE "gfx/pokemon/cmai/bitmask.asm"

CPatchouliBitmasks:    INCLUDE "gfx/pokemon/cpatchouli/bitmask.asm"

CChenBitmasks:    INCLUDE "gfx/pokemon/cchen/bitmask.asm"

RanBitmasks:    INCLUDE "gfx/pokemon/ran/bitmask.asm"

TRanBitmasks:    INCLUDE "gfx/pokemon/tran/bitmask.asm"

CYukariBitmasks:    INCLUDE "gfx/pokemon/cyukari/bitmask.asm"

HMinorikoBitmasks:    INCLUDE "gfx/pokemon/hminoriko/bitmask.asm"

CorsolaBitmasks:    INCLUDE "gfx/pokemon/corsola/bitmask.asm"

CKurumiBitmasks:   INCLUDE "gfx/pokemon/ckurumi/bitmask.asm"

DDaichanBitmasks:   INCLUDE "gfx/pokemon/ddaichan/bitmask.asm"

CCirnoBitmasks:   INCLUDE "gfx/pokemon/ccirno/bitmask.asm"

TReisenBitmasks:   INCLUDE "gfx/pokemon/treisen/bitmask.asm"

CSuwakoBitmasks:   INCLUDE "gfx/pokemon/csuwako/bitmask.asm"

IkuBitmasks:   INCLUDE "gfx/pokemon/iku/bitmask.asm"

CShizuhaBitmasks:    INCLUDE "gfx/pokemon/cshizuha/bitmask.asm"
CLilyBlackBitmasks:        INCLUDE "gfx/pokemon/clilyblack/bitmask.asm"
