CReimuBitmasks:  INCLUDE "gfx/pokemon/creimu/bitmask.asm"
ReimuBitmasks:    INCLUDE "gfx/pokemon/reimu/bitmask.asm"
EReimuBitmasks:   INCLUDE "gfx/pokemon/ereimu/bitmask.asm"
CMarisaBitmasks: INCLUDE "gfx/pokemon/cmarisa/bitmask.asm"
MarisaBitmasks: INCLUDE "gfx/pokemon/marisa/bitmask.asm"
EMarisaBitmasks:  INCLUDE "gfx/pokemon/emarisa/bitmask.asm"
CSakuyaBitmasks:   INCLUDE "gfx/pokemon/csakuya/bitmask.asm"
SakuyaBitmasks:  INCLUDE "gfx/pokemon/sakuya/bitmask.asm"
ESakuyaBitmasks:  INCLUDE "gfx/pokemon/esakuya/bitmask.asm"
CGyokuBitmasks:   INCLUDE "gfx/pokemon/cgyoku/bitmask.asm"
MGyokuBitmasks:    INCLUDE "gfx/pokemon/mgyoku/bitmask.asm"
FGyokuBitmasks: INCLUDE "gfx/pokemon/fgyoku/bitmask.asm"
OGyokuBitmasks:     INCLUDE "gfx/pokemon/ogyoku/bitmask.asm"
CMaganBitmasks:     INCLUDE "gfx/pokemon/cmagan/bitmask.asm"
MaganBitmasks:   INCLUDE "gfx/pokemon/magan/bitmask.asm"
EMaganBitmasks:     INCLUDE "gfx/pokemon/emagan/bitmask.asm"
CMimaBitmasks:  INCLUDE "gfx/pokemon/cmima/bitmask.asm"
MimaBitmasks:    INCLUDE "gfx/pokemon/mima/bitmask.asm"
ElisBitmasks:    INCLUDE "gfx/pokemon/elis/bitmask.asm"
EElisBitmasks:     INCLUDE "gfx/pokemon/eelis/bitmask.asm"
CKikuriBitmasks:      INCLUDE "gfx/pokemon/ckikuri/bitmask.asm"
CKongaraBitmasks:   INCLUDE "gfx/pokemon/ckongara/bitmask.asm"
KongaraBitmasks:   INCLUDE "gfx/pokemon/kongara/bitmask.asm"
EKongaraBitmasks:  INCLUDE "gfx/pokemon/ekongara/bitmask.asm"
CRikaBitmasks:   INCLUDE "gfx/pokemon/crika/bitmask.asm"
RikaBitmasks:   INCLUDE "gfx/pokemon/rika/bitmask.asm"
ERikaBitmasks:   INCLUDE "gfx/pokemon/erika/bitmask.asm"
CMeiraBitmasks:   INCLUDE "gfx/pokemon/cmeira/bitmask.asm"
MeiraBitmasks:   INCLUDE "gfx/pokemon/meira/bitmask.asm"
EllenBitmasks: INCLUDE "gfx/pokemon/ellen/bitmask.asm"
EEllenBitmasks: INCLUDE "gfx/pokemon/eellen/bitmask.asm"
CKotohimeBitmasks:      INCLUDE "gfx/pokemon/ckotohime/bitmask.asm"
KotohimeBitmasks:     INCLUDE "gfx/pokemon/kotohime/bitmask.asm"
EKotohimeBitmasks:     INCLUDE "gfx/pokemon/ekotohime/bitmask.asm"
CKanaBitmasks:      INCLUDE "gfx/pokemon/ckana/bitmask.asm"
KanaBitmasks:  INCLUDE "gfx/pokemon/kana/bitmask.asm"
EKanaBitmasks:      INCLUDE "gfx/pokemon/ekana/bitmask.asm"
CRikakoBitmasks:   INCLUDE "gfx/pokemon/crikako/bitmask.asm"
RikakoBitmasks:    INCLUDE "gfx/pokemon/rikako/bitmask.asm"
ERikakoBitmasks:   INCLUDE "gfx/pokemon/erikako/bitmask.asm"
YumemiBitmasks:    INCLUDE "gfx/pokemon/yumemi/bitmask.asm"
EYumemiBitmasks:    INCLUDE "gfx/pokemon/eyumemi/bitmask.asm"
COrangeBitmasks:     INCLUDE "gfx/pokemon/corange/bitmask.asm"
OrangeBitmasks:   INCLUDE "gfx/pokemon/orange/bitmask.asm"
KurumiBitmasks:    INCLUDE "gfx/pokemon/kurumi/bitmask.asm"
EKurumiBitmasks:  INCLUDE "gfx/pokemon/ekurumi/bitmask.asm"
CEllyBitmasks:  INCLUDE "gfx/pokemon/celly/bitmask.asm"
EllyBitmasks:       INCLUDE "gfx/pokemon/elly/bitmask.asm"
EEllyBitmasks:    INCLUDE "gfx/pokemon/eelly/bitmask.asm"
CYukaBitmasks:   INCLUDE "gfx/pokemon/cyuka/bitmask.asm"
YukaBitmasks:     INCLUDE "gfx/pokemon/yuka/bitmask.asm"
EYukaBitmasks:    INCLUDE "gfx/pokemon/eyuka/bitmask.asm"
CMugetsuBitmasks:    INCLUDE "gfx/pokemon/cmugetsu/bitmask.asm"
MugetsuBitmasks: INCLUDE "gfx/pokemon/mugetsu/bitmask.asm"
EMugetsuBitmasks: INCLUDE "gfx/pokemon/emugetsu/bitmask.asm"
CGengetsuBitmasks: INCLUDE "gfx/pokemon/cgengetsu/bitmask.asm"
GengetsuBitmasks:  INCLUDE "gfx/pokemon/gengetsu/bitmask.asm"
EGengetsuBitmasks: INCLUDE "gfx/pokemon/egengetsu/bitmask.asm"
AliceBitmasks:  INCLUDE "gfx/pokemon/alice/bitmask.asm"
EAliceBitmasks:   INCLUDE "gfx/pokemon/ealice/bitmask.asm"
MaiBitmasks:      INCLUDE "gfx/pokemon/mai/bitmask.asm"
EMaiBitmasks:     INCLUDE "gfx/pokemon/emai/bitmask.asm"
CYukiBitmasks:       INCLUDE "gfx/pokemon/cyuki/bitmask.asm"
YukiBitmasks:    INCLUDE "gfx/pokemon/yuki/bitmask.asm"
YumekoBitmasks:   INCLUDE "gfx/pokemon/yumeko/bitmask.asm"
EYumekoBitmasks:   INCLUDE "gfx/pokemon/eyumeko/bitmask.asm"
CShinkiBitmasks:     INCLUDE "gfx/pokemon/cshinki/bitmask.asm"
ShinkiBitmasks:    INCLUDE "gfx/pokemon/shinki/bitmask.asm"
EShinkiBitmasks:     INCLUDE "gfx/pokemon/eshinki/bitmask.asm"
CRumiaBitmasks:       INCLUDE "gfx/pokemon/crumia/bitmask.asm"
RumiaBitmasks:    INCLUDE "gfx/pokemon/rumia/bitmask.asm"
ERumiaBitmasks:      INCLUDE "gfx/pokemon/erumia/bitmask.asm"
CDaichanBitmasks:     INCLUDE "gfx/pokemon/cdaichan/bitmask.asm"
DaichanBitmasks:    INCLUDE "gfx/pokemon/daichan/bitmask.asm"
CirnoBitmasks:  INCLUDE "gfx/pokemon/cirno/bitmask.asm"
CMeilingBitmasks:     INCLUDE "gfx/pokemon/cmeiling/bitmask.asm"
EMeilingBitmasks:  INCLUDE "gfx/pokemon/emeiling/bitmask.asm"
CKoakumaBitmasks: INCLUDE "gfx/pokemon/ckoakuma/bitmask.asm"
KoakumaBitmasks:  INCLUDE "gfx/pokemon/koakuma/bitmask.asm"
EKoakumaBitmasks:    INCLUDE "gfx/pokemon/ekoakuma/bitmask.asm"
PatchouliBitmasks:    INCLUDE "gfx/pokemon/patchouli/bitmask.asm"
EPatchouliBitmasks:     INCLUDE "gfx/pokemon/epatchouli/bitmask.asm"
CRemiliaBitmasks:    INCLUDE "gfx/pokemon/cremilia/bitmask.asm"
RemiliaBitmasks:    INCLUDE "gfx/pokemon/remilia/bitmask.asm"
ERemiliaBitmasks: INCLUDE "gfx/pokemon/eremilia/bitmask.asm"
CFlandreBitmasks:     INCLUDE "gfx/pokemon/cflandre/bitmask.asm"
FlandreBitmasks:     INCLUDE "gfx/pokemon/flandre/bitmask.asm"
EFlandreBitmasks:    INCLUDE "gfx/pokemon/eflandre/bitmask.asm"
SeakingBitmasks:    INCLUDE "gfx/pokemon/seaking/bitmask.asm"
StaryuBitmasks:     INCLUDE "gfx/pokemon/staryu/bitmask.asm"
StarmieBitmasks:    INCLUDE "gfx/pokemon/starmie/bitmask.asm"
ScytherBitmasks:    INCLUDE "gfx/pokemon/scyther/bitmask.asm"
JynxBitmasks:       INCLUDE "gfx/pokemon/jynx/bitmask.asm"
ElectabuzzBitmasks: INCLUDE "gfx/pokemon/electabuzz/bitmask.asm"
MagmarBitmasks:     INCLUDE "gfx/pokemon/magmar/bitmask.asm"
PinsirBitmasks:     INCLUDE "gfx/pokemon/pinsir/bitmask.asm"
LaprasBitmasks:     INCLUDE "gfx/pokemon/lapras/bitmask.asm"
DittoBitmasks:      INCLUDE "gfx/pokemon/ditto/bitmask.asm"
EeveeBitmasks:      INCLUDE "gfx/pokemon/eevee/bitmask.asm"
VaporeonBitmasks:   INCLUDE "gfx/pokemon/vaporeon/bitmask.asm"
JolteonBitmasks:    INCLUDE "gfx/pokemon/jolteon/bitmask.asm"
FlareonBitmasks:    INCLUDE "gfx/pokemon/flareon/bitmask.asm"
PorygonBitmasks:    INCLUDE "gfx/pokemon/porygon/bitmask.asm"
OmanyteBitmasks:    INCLUDE "gfx/pokemon/omanyte/bitmask.asm"
OmastarBitmasks:    INCLUDE "gfx/pokemon/omastar/bitmask.asm"
KabutoBitmasks:     INCLUDE "gfx/pokemon/kabuto/bitmask.asm"
KabutopsBitmasks:   INCLUDE "gfx/pokemon/kabutops/bitmask.asm"
AerodactylBitmasks: INCLUDE "gfx/pokemon/aerodactyl/bitmask.asm"
SnorlaxBitmasks:    INCLUDE "gfx/pokemon/snorlax/bitmask.asm"
DratiniBitmasks:    INCLUDE "gfx/pokemon/dratini/bitmask.asm"
DragonairBitmasks:  INCLUDE "gfx/pokemon/dragonair/bitmask.asm"
DragoniteBitmasks:  INCLUDE "gfx/pokemon/dragonite/bitmask.asm"
MewBitmasks:        INCLUDE "gfx/pokemon/mew/bitmask.asm"
CYoumuBitmasks:  INCLUDE "gfx/pokemon/cyoumu/bitmask.asm"
YoumuBitmasks:    INCLUDE "gfx/pokemon/youmu/bitmask.asm"
EYoumuBitmasks:   INCLUDE "gfx/pokemon/eyoumu/bitmask.asm"
CReisenBitmasks:  INCLUDE "gfx/pokemon/creisen/bitmask.asm"
ReisenBitmasks:    INCLUDE "gfx/pokemon/reisen/bitmask.asm"
CSanaeBitmasks:   INCLUDE "gfx/pokemon/csanae/bitmask.asm"
SanaeBitmasks:   INCLUDE "gfx/pokemon/sanae/bitmask.asm"
ESanaeBitmasks: INCLUDE "gfx/pokemon/esanae/bitmask.asm"
SentretBitmasks:    INCLUDE "gfx/pokemon/sentret/bitmask.asm"
FurretBitmasks:     INCLUDE "gfx/pokemon/furret/bitmask.asm"
HoothootBitmasks:   INCLUDE "gfx/pokemon/hoothoot/bitmask.asm"
NoctowlBitmasks:    INCLUDE "gfx/pokemon/noctowl/bitmask.asm"
LedybaBitmasks:     INCLUDE "gfx/pokemon/ledyba/bitmask.asm"
LedianBitmasks:     INCLUDE "gfx/pokemon/ledian/bitmask.asm"
SpinarakBitmasks:   INCLUDE "gfx/pokemon/spinarak/bitmask.asm"
AriadosBitmasks:    INCLUDE "gfx/pokemon/ariados/bitmask.asm"
CrobatBitmasks:     INCLUDE "gfx/pokemon/crobat/bitmask.asm"
ChinchouBitmasks:   INCLUDE "gfx/pokemon/chinchou/bitmask.asm"
LanturnBitmasks:    INCLUDE "gfx/pokemon/lanturn/bitmask.asm"
CleffaBitmasks:     INCLUDE "gfx/pokemon/cleffa/bitmask.asm"
IgglybuffBitmasks:  INCLUDE "gfx/pokemon/igglybuff/bitmask.asm"
TogepiBitmasks:     INCLUDE "gfx/pokemon/togepi/bitmask.asm"
TogeticBitmasks:    INCLUDE "gfx/pokemon/togetic/bitmask.asm"
NatuBitmasks:       INCLUDE "gfx/pokemon/natu/bitmask.asm"
XatuBitmasks:       INCLUDE "gfx/pokemon/xatu/bitmask.asm"
MareepBitmasks:     INCLUDE "gfx/pokemon/mareep/bitmask.asm"
FlaaffyBitmasks:    INCLUDE "gfx/pokemon/flaaffy/bitmask.asm"
AmpharosBitmasks:   INCLUDE "gfx/pokemon/ampharos/bitmask.asm"
BellossomBitmasks:  INCLUDE "gfx/pokemon/bellossom/bitmask.asm"
SudowoodoBitmasks:  INCLUDE "gfx/pokemon/sudowoodo/bitmask.asm"
MarillBitmasks:     INCLUDE "gfx/pokemon/marill/bitmask.asm"
AzumarillBitmasks:  INCLUDE "gfx/pokemon/azumarill/bitmask.asm"
PolitoedBitmasks:   INCLUDE "gfx/pokemon/politoed/bitmask.asm"
HoppipBitmasks:     INCLUDE "gfx/pokemon/hoppip/bitmask.asm"
SkiploomBitmasks:   INCLUDE "gfx/pokemon/skiploom/bitmask.asm"
JumpluffBitmasks:   INCLUDE "gfx/pokemon/jumpluff/bitmask.asm"
AipomBitmasks:      INCLUDE "gfx/pokemon/aipom/bitmask.asm"
SunkernBitmasks:    INCLUDE "gfx/pokemon/sunkern/bitmask.asm"
SunfloraBitmasks:   INCLUDE "gfx/pokemon/sunflora/bitmask.asm"
YanmaBitmasks:      INCLUDE "gfx/pokemon/yanma/bitmask.asm"
QuagsireBitmasks:   INCLUDE "gfx/pokemon/quagsire/bitmask.asm"
EspeonBitmasks:     INCLUDE "gfx/pokemon/espeon/bitmask.asm"
UmbreonBitmasks:    INCLUDE "gfx/pokemon/umbreon/bitmask.asm"
MurkrowBitmasks:    INCLUDE "gfx/pokemon/murkrow/bitmask.asm"
MisdreavusBitmasks: INCLUDE "gfx/pokemon/misdreavus/bitmask.asm"
WobbuffetBitmasks:  INCLUDE "gfx/pokemon/wobbuffet/bitmask.asm"
GirafarigBitmasks:  INCLUDE "gfx/pokemon/girafarig/bitmask.asm"
PinecoBitmasks:     INCLUDE "gfx/pokemon/pineco/bitmask.asm"
ForretressBitmasks: INCLUDE "gfx/pokemon/forretress/bitmask.asm"
DunsparceBitmasks:  INCLUDE "gfx/pokemon/dunsparce/bitmask.asm"
GligarBitmasks:     INCLUDE "gfx/pokemon/gligar/bitmask.asm"
SteelixBitmasks:    INCLUDE "gfx/pokemon/steelix/bitmask.asm"
SnubbullBitmasks:   INCLUDE "gfx/pokemon/snubbull/bitmask.asm"
GranbullBitmasks:   INCLUDE "gfx/pokemon/granbull/bitmask.asm"
ScizorBitmasks:     INCLUDE "gfx/pokemon/scizor/bitmask.asm"
ShuckleBitmasks:    INCLUDE "gfx/pokemon/shuckle/bitmask.asm"
HeracrossBitmasks:  INCLUDE "gfx/pokemon/heracross/bitmask.asm"
TeddiursaBitmasks:  INCLUDE "gfx/pokemon/teddiursa/bitmask.asm"
UrsaringBitmasks:   INCLUDE "gfx/pokemon/ursaring/bitmask.asm"
SlugmaBitmasks:     INCLUDE "gfx/pokemon/slugma/bitmask.asm"
MagcargoBitmasks:   INCLUDE "gfx/pokemon/magcargo/bitmask.asm"
SwinubBitmasks:     INCLUDE "gfx/pokemon/swinub/bitmask.asm"
PiloswineBitmasks:  INCLUDE "gfx/pokemon/piloswine/bitmask.asm"
RemoraidBitmasks:   INCLUDE "gfx/pokemon/remoraid/bitmask.asm"
OctilleryBitmasks:  INCLUDE "gfx/pokemon/octillery/bitmask.asm"
DelibirdBitmasks:   INCLUDE "gfx/pokemon/delibird/bitmask.asm"
MantineBitmasks:    INCLUDE "gfx/pokemon/mantine/bitmask.asm"
SkarmoryBitmasks:   INCLUDE "gfx/pokemon/skarmory/bitmask.asm"
HoundourBitmasks:   INCLUDE "gfx/pokemon/houndour/bitmask.asm"
HoundoomBitmasks:   INCLUDE "gfx/pokemon/houndoom/bitmask.asm"
KingdraBitmasks:    INCLUDE "gfx/pokemon/kingdra/bitmask.asm"
PhanpyBitmasks:     INCLUDE "gfx/pokemon/phanpy/bitmask.asm"
DonphanBitmasks:    INCLUDE "gfx/pokemon/donphan/bitmask.asm"
Porygon2Bitmasks:   INCLUDE "gfx/pokemon/porygon2/bitmask.asm"
StantlerBitmasks:   INCLUDE "gfx/pokemon/stantler/bitmask.asm"
SmeargleBitmasks:   INCLUDE "gfx/pokemon/smeargle/bitmask.asm"
TyrogueBitmasks:    INCLUDE "gfx/pokemon/tyrogue/bitmask.asm"
HitmontopBitmasks:  INCLUDE "gfx/pokemon/hitmontop/bitmask.asm"
SmoochumBitmasks:   INCLUDE "gfx/pokemon/smoochum/bitmask.asm"
ElekidBitmasks:     INCLUDE "gfx/pokemon/elekid/bitmask.asm"
MagbyBitmasks:      INCLUDE "gfx/pokemon/magby/bitmask.asm"
MiltankBitmasks:    INCLUDE "gfx/pokemon/miltank/bitmask.asm"
BlisseyBitmasks:    INCLUDE "gfx/pokemon/blissey/bitmask.asm"
RaikouBitmasks:     INCLUDE "gfx/pokemon/raikou/bitmask.asm"
EnteiBitmasks:      INCLUDE "gfx/pokemon/entei/bitmask.asm"
SuicuneBitmasks:    INCLUDE "gfx/pokemon/suicune/bitmask.asm"
LarvitarBitmasks:   INCLUDE "gfx/pokemon/larvitar/bitmask.asm"
PupitarBitmasks:    INCLUDE "gfx/pokemon/pupitar/bitmask.asm"
TyranitarBitmasks:  INCLUDE "gfx/pokemon/tyranitar/bitmask.asm"
LugiaBitmasks:      INCLUDE "gfx/pokemon/lugia/bitmask.asm"
HoOhBitmasks:       INCLUDE "gfx/pokemon/ho_oh/bitmask.asm"
CelebiBitmasks:     INCLUDE "gfx/pokemon/celebi/bitmask.asm"
AzurillBitmasks:    INCLUDE "gfx/pokemon/azurill/bitmask.asm"
WynautBitmasks:     INCLUDE "gfx/pokemon/wynaut/bitmask.asm"
AmbipomBitmasks:    INCLUDE "gfx/pokemon/ambipom/bitmask.asm"
MismagiusBitmasks:  INCLUDE "gfx/pokemon/mismagius/bitmask.asm"
HonchkrowBitmasks:  INCLUDE "gfx/pokemon/honchkrow/bitmask.asm"
BonslyBitmasks:     INCLUDE "gfx/pokemon/bonsly/bitmask.asm"
MimeJrBitmasks:     INCLUDE "gfx/pokemon/mime_jr_/bitmask.asm"
HappinyBitmasks:    INCLUDE "gfx/pokemon/happiny/bitmask.asm"
MunchlaxBitmasks:   INCLUDE "gfx/pokemon/munchlax/bitmask.asm"
MantykeBitmasks:    INCLUDE "gfx/pokemon/mantyke/bitmask.asm"
WeavileBitmasks:    INCLUDE "gfx/pokemon/weavile/bitmask.asm"
MagnezoneBitmasks:  INCLUDE "gfx/pokemon/magnezone/bitmask.asm"
LickilickyBitmasks: INCLUDE "gfx/pokemon/lickilicky/bitmask.asm"
RhyperiorBitmasks:  INCLUDE "gfx/pokemon/rhyperior/bitmask.asm"
TangrowthBitmasks:  INCLUDE "gfx/pokemon/tangrowth/bitmask.asm"
ElectivireBitmasks: INCLUDE "gfx/pokemon/electivire/bitmask.asm"
MagmortarBitmasks:  INCLUDE "gfx/pokemon/magmortar/bitmask.asm"
TogekissBitmasks:   INCLUDE "gfx/pokemon/togekiss/bitmask.asm"
YanmegaBitmasks:    INCLUDE "gfx/pokemon/yanmega/bitmask.asm"
LeafeonBitmasks:    INCLUDE "gfx/pokemon/leafeon/bitmask.asm"
GlaceonBitmasks:    INCLUDE "gfx/pokemon/glaceon/bitmask.asm"
GliscorBitmasks:    INCLUDE "gfx/pokemon/gliscor/bitmask.asm"
MamoswineBitmasks:  INCLUDE "gfx/pokemon/mamoswine/bitmask.asm"
PorygonZBitmasks:   INCLUDE "gfx/pokemon/porygon_z/bitmask.asm"
SylveonBitmasks:    INCLUDE "gfx/pokemon/sylveon/bitmask.asm"
PerrserkerBitmasks: INCLUDE "gfx/pokemon/perrserker/bitmask.asm"
CursolaBitmasks:    INCLUDE "gfx/pokemon/cursola/bitmask.asm"
SirfetchDBitmasks:  INCLUDE "gfx/pokemon/sirfetch_d/bitmask.asm"
MrRimeBitmasks:     INCLUDE "gfx/pokemon/mr__rime/bitmask.asm"
WyrdeerBitmasks:    INCLUDE "gfx/pokemon/wyrdeer/bitmask.asm"
KleavorBitmasks:    INCLUDE "gfx/pokemon/kleavor/bitmask.asm"
UrsalunaBitmasks:   INCLUDE "gfx/pokemon/ursaluna/bitmask.asm"
SneaslerBitmasks:   INCLUDE "gfx/pokemon/sneasler/bitmask.asm"
OverqwilBitmasks:   INCLUDE "gfx/pokemon/overqwil/bitmask.asm"
FarigirafBitmasks:  INCLUDE "gfx/pokemon/farigiraf/bitmask.asm"
ClodsireBitmasks:   INCLUDE "gfx/pokemon/clodsire/bitmask.asm"
AnnihilapeBitmasks: INCLUDE "gfx/pokemon/annihilape/bitmask.asm"

EggBitmasks:        INCLUDE "gfx/pokemon/egg/bitmask.asm"

UnownABitmasks: INCLUDE "gfx/pokemon/unown_a/bitmask.asm"
UnownBBitmasks: INCLUDE "gfx/pokemon/unown_b/bitmask.asm"
UnownCBitmasks: INCLUDE "gfx/pokemon/unown_c/bitmask.asm"
UnownDBitmasks: INCLUDE "gfx/pokemon/unown_d/bitmask.asm"
UnownEBitmasks: INCLUDE "gfx/pokemon/unown_e/bitmask.asm"
UnownFBitmasks: INCLUDE "gfx/pokemon/unown_f/bitmask.asm"
UnownGBitmasks: INCLUDE "gfx/pokemon/unown_g/bitmask.asm"
UnownHBitmasks: INCLUDE "gfx/pokemon/unown_h/bitmask.asm"
UnownIBitmasks: INCLUDE "gfx/pokemon/unown_i/bitmask.asm"
UnownJBitmasks: INCLUDE "gfx/pokemon/unown_j/bitmask.asm"
UnownKBitmasks: INCLUDE "gfx/pokemon/unown_k/bitmask.asm"
UnownLBitmasks: INCLUDE "gfx/pokemon/unown_l/bitmask.asm"
UnownMBitmasks: INCLUDE "gfx/pokemon/unown_m/bitmask.asm"
UnownNBitmasks: INCLUDE "gfx/pokemon/unown_n/bitmask.asm"
UnownOBitmasks: INCLUDE "gfx/pokemon/unown_o/bitmask.asm"
UnownPBitmasks: INCLUDE "gfx/pokemon/unown_p/bitmask.asm"
UnownQBitmasks: INCLUDE "gfx/pokemon/unown_q/bitmask.asm"
UnownRBitmasks: INCLUDE "gfx/pokemon/unown_r/bitmask.asm"
UnownSBitmasks: INCLUDE "gfx/pokemon/unown_s/bitmask.asm"
UnownTBitmasks: INCLUDE "gfx/pokemon/unown_t/bitmask.asm"
UnownUBitmasks: INCLUDE "gfx/pokemon/unown_u/bitmask.asm"
UnownVBitmasks: INCLUDE "gfx/pokemon/unown_v/bitmask.asm"
UnownWBitmasks: INCLUDE "gfx/pokemon/unown_w/bitmask.asm"
UnownXBitmasks: INCLUDE "gfx/pokemon/unown_x/bitmask.asm"
UnownYBitmasks: INCLUDE "gfx/pokemon/unown_y/bitmask.asm"
UnownZBitmasks: INCLUDE "gfx/pokemon/unown_z/bitmask.asm"
UnownExclamationBitmasks: INCLUDE "gfx/pokemon/unown_exclamation/bitmask.asm"
UnownQuestionBitmasks:    INCLUDE "gfx/pokemon/unown_question/bitmask.asm"

PichuPlainBitmasks: INCLUDE "gfx/pokemon/pichu_plain/bitmask.asm"
PichuSpikyBitmasks: INCLUDE "gfx/pokemon/pichu_spiky/bitmask.asm"

EKikuriSparkBitmasks:
EKikuriPlainBitmasks:  INCLUDE "gfx/pokemon/ekikuri_plain/bitmask.asm"
EKikuriFlyBitmasks:    INCLUDE "gfx/pokemon/ekikuri_fly/bitmask.asm"
EKikuriSurfBitmasks:   INCLUDE "gfx/pokemon/ekikuri_surf/bitmask.asm"
EKikuriPikaBitmasks:   INCLUDE "gfx/pokemon/ekikuri_pika/bitmask.asm"
EKikuriChuchuBitmasks: INCLUDE "gfx/pokemon/ekikuri_chuchu/bitmask.asm"

KikuriJohtoBitmasks:  INCLUDE "gfx/pokemon/kikuri_johto/bitmask.asm"
KikuriKantoBitmasks:  INCLUDE "gfx/pokemon/kikuri_kanto/bitmask.asm"
KikuriKogaBitmasks:   INCLUDE "gfx/pokemon/kikuri_koga/bitmask.asm"
KikuriAgathaBitmasks: INCLUDE "gfx/pokemon/kikuri_agatha/bitmask.asm"
KikuriArianaBitmasks: INCLUDE "gfx/pokemon/kikuri_ariana/bitmask.asm"

MagikarpPlainBitmasks:     INCLUDE "gfx/pokemon/magikarp_plain/bitmask.asm"
MagikarpSkellyBitmasks:    INCLUDE "gfx/pokemon/magikarp_skelly/bitmask.asm"
MagikarpCalico1Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico1/bitmask.asm"
MagikarpCalico2Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico2/bitmask.asm"
MagikarpCalico3Bitmasks:   INCLUDE "gfx/pokemon/magikarp_calico3/bitmask.asm"
MagikarpTwoToneBitmasks:   INCLUDE "gfx/pokemon/magikarp_twotone/bitmask.asm"
MagikarpOrcaBitmasks:      INCLUDE "gfx/pokemon/magikarp_orca/bitmask.asm"
MagikarpDapplesBitmasks:   INCLUDE "gfx/pokemon/magikarp_dapples/bitmask.asm"
MagikarpTigerBitmasks:     INCLUDE "gfx/pokemon/magikarp_tiger/bitmask.asm"
MagikarpZebraBitmasks:     INCLUDE "gfx/pokemon/magikarp_zebra/bitmask.asm"
MagikarpStripeBitmasks:    INCLUDE "gfx/pokemon/magikarp_stripe/bitmask.asm"
MagikarpBubblesBitmasks:   INCLUDE "gfx/pokemon/magikarp_bubbles/bitmask.asm"
MagikarpDiamondsBitmasks:  INCLUDE "gfx/pokemon/magikarp_diamonds/bitmask.asm"
MagikarpPatchesBitmasks:   INCLUDE "gfx/pokemon/magikarp_patches/bitmask.asm"
MagikarpForehead1Bitmasks: INCLUDE "gfx/pokemon/magikarp_forehead1/bitmask.asm"
MagikarpMask1Bitmasks:     INCLUDE "gfx/pokemon/magikarp_mask1/bitmask.asm"
MagikarpForehead2Bitmasks: INCLUDE "gfx/pokemon/magikarp_forehead2/bitmask.asm"
MagikarpMask2Bitmasks:     INCLUDE "gfx/pokemon/magikarp_mask2/bitmask.asm"
MagikarpSaucyBitmasks:     INCLUDE "gfx/pokemon/magikarp_saucy/bitmask.asm"
MagikarpRaindropBitmasks:  INCLUDE "gfx/pokemon/magikarp_raindrop/bitmask.asm"

DudunsparceTwoSegmentBitmasks:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/bitmask.asm"
DudunsparceThreeSegmentBitmasks: INCLUDE "gfx/pokemon/dudunsparce_three_segment/bitmask.asm"

GyaradosPlainBitmasks: INCLUDE "gfx/pokemon/gyarados_plain/bitmask.asm"
GyaradosRedBitmasks:   INCLUDE "gfx/pokemon/gyarados_red/bitmask.asm"

MewtwoPlainBitmasks:   INCLUDE "gfx/pokemon/mewtwo_plain/bitmask.asm"
MewtwoArmoredBitmasks: INCLUDE "gfx/pokemon/mewtwo_armored/bitmask.asm"

EMimaBitmasks:  INCLUDE "gfx/pokemon/rattata_plain/bitmask.asm"
EMimaAlolanBitmasks: INCLUDE "gfx/pokemon/rattata_alolan/bitmask.asm"

CElisPlainBitmasks:  INCLUDE "gfx/pokemon/celis_plain/bitmask.asm"
CElisAlolanBitmasks: INCLUDE "gfx/pokemon/celis_alolan/bitmask.asm"

CSarielPlainBitmasks:  INCLUDE "gfx/pokemon/csariel_plain/bitmask.asm"
CSarielAlolanBitmasks: INCLUDE "gfx/pokemon/csariel_alolan/bitmask.asm"

SarielPlainBitmasks:  INCLUDE "gfx/pokemon/sariel_plain/bitmask.asm"
SarielAlolanBitmasks: INCLUDE "gfx/pokemon/sariel_alolan/bitmask.asm"

ESarielPlainBitmasks:  INCLUDE "gfx/pokemon/esariel_plain/bitmask.asm"
ESarielAlolanBitmasks: INCLUDE "gfx/pokemon/esariel_alolan/bitmask.asm"

EMeiraPlainBitmasks:  INCLUDE "gfx/pokemon/emeira_plain/bitmask.asm"
EMeiraAlolanBitmasks: INCLUDE "gfx/pokemon/emeira_alolan/bitmask.asm"

CEllenPlainBitmasks:  INCLUDE "gfx/pokemon/cellen_plain/bitmask.asm"
CEllenAlolanBitmasks: INCLUDE "gfx/pokemon/cellen_alolan/bitmask.asm"

CChiyuriPlainBitmasks:  INCLUDE "gfx/pokemon/cchiyuri_plain/bitmask.asm"
CChiyuriAlolanBitmasks: INCLUDE "gfx/pokemon/cchiyuri_alolan/bitmask.asm"

ChiyuriPlainBitmasks:  INCLUDE "gfx/pokemon/chiyuri_plain/bitmask.asm"
ChiyuriAlolanBitmasks: INCLUDE "gfx/pokemon/chiyuri_alolan/bitmask.asm"

EChiyuriPlainBitmasks:    INCLUDE "gfx/pokemon/echiyuri_plain/bitmask.asm"
EChiyuriAlolanBitmasks:   INCLUDE "gfx/pokemon/echiyuri_alolan/bitmask.asm"
EChiyuriGalarianBitmasks: INCLUDE "gfx/pokemon/echiyuri_galarian/bitmask.asm"

CYumemiPlainBitmasks:  INCLUDE "gfx/pokemon/cyumemi_plain/bitmask.asm"
CYumemiAlolanBitmasks: INCLUDE "gfx/pokemon/cyumemi_alolan/bitmask.asm"

CSaraPlainBitmasks:  INCLUDE "gfx/pokemon/csara_plain/bitmask.asm"
CSaraAlolanBitmasks: INCLUDE "gfx/pokemon/csara_alolan/bitmask.asm"

SaraPlainBitmasks:  INCLUDE "gfx/pokemon/sara_plain/bitmask.asm"
SaraAlolanBitmasks: INCLUDE "gfx/pokemon/sara_alolan/bitmask.asm"

ESaraPlainBitmasks:  INCLUDE "gfx/pokemon/esara_plain/bitmask.asm"
ESaraAlolanBitmasks: INCLUDE "gfx/pokemon/esara_alolan/bitmask.asm"

EYukiPlainBitmasks:  INCLUDE "gfx/pokemon/eyuki_plain/bitmask.asm"
EYukiAlolanBitmasks: INCLUDE "gfx/pokemon/eyuki_alolan/bitmask.asm"

CYumekoPlainBitmasks:  INCLUDE "gfx/pokemon/cyumeko_plain/bitmask.asm"
CYumekoAlolanBitmasks: INCLUDE "gfx/pokemon/cyumeko_alolan/bitmask.asm"

ECirnoPlainBitmasks:  INCLUDE "gfx/pokemon/ecirno_plain/bitmask.asm"
ECirnoAlolanBitmasks: INCLUDE "gfx/pokemon/ecirno_alolan/bitmask.asm"

MeilingPlainBitmasks:  INCLUDE "gfx/pokemon/meiling_plain/bitmask.asm"
MeilingAlolanBitmasks: INCLUDE "gfx/pokemon/meiling_alolan/bitmask.asm"

CLuizePlainBitmasks:    INCLUDE "gfx/pokemon/cluize_plain/bitmask.asm"
CLuizeGalarianBitmasks: INCLUDE "gfx/pokemon/cluize_galarian/bitmask.asm"

LuizePlainBitmasks:    INCLUDE "gfx/pokemon/luize_plain/bitmask.asm"
LuizeGalarianBitmasks: INCLUDE "gfx/pokemon/luize_galarian/bitmask.asm"

ELuizePlainBitmasks:   INCLUDE "gfx/pokemon/eluize_plain/bitmask.asm"
ELuizeGalarianBitmasks: INCLUDE "gfx/pokemon/eluize_galarian/bitmask.asm"

CAlicePlainBitmasks:    INCLUDE "gfx/pokemon/calice_plain/bitmask.asm"
CAliceGalarianBitmasks: INCLUDE "gfx/pokemon/calice_galarian/bitmask.asm"

CMaiPlainBitmasks:     INCLUDE "gfx/pokemon/cmai_plain/bitmask.asm"
CMaiGalarianBitmasks:  INCLUDE "gfx/pokemon/cmai_galarian/bitmask.asm"

CPatchouliPlainBitmasks:    INCLUDE "gfx/pokemon/cpatchouli_plain/bitmask.asm"
CPatchouliGalarianBitmasks: INCLUDE "gfx/pokemon/cpatchouli_galarian/bitmask.asm"

MrMimePlainBitmasks:    INCLUDE "gfx/pokemon/mr__mime_plain/bitmask.asm"
MrMimeGalarianBitmasks: INCLUDE "gfx/pokemon/mr__mime_galarian/bitmask.asm"

ArticunoPlainBitmasks:    INCLUDE "gfx/pokemon/articuno_plain/bitmask.asm"
ArticunoGalarianBitmasks: INCLUDE "gfx/pokemon/articuno_galarian/bitmask.asm"

ZapdosPlainBitmasks:    INCLUDE "gfx/pokemon/zapdos_plain/bitmask.asm"
ZapdosGalarianBitmasks: INCLUDE "gfx/pokemon/zapdos_galarian/bitmask.asm"

MoltresPlainBitmasks:    INCLUDE "gfx/pokemon/moltres_plain/bitmask.asm"
MoltresGalarianBitmasks: INCLUDE "gfx/pokemon/moltres_galarian/bitmask.asm"

SlowkingPlainBitmasks:    INCLUDE "gfx/pokemon/slowking_plain/bitmask.asm"
SlowkingGalarianBitmasks: INCLUDE "gfx/pokemon/slowking_galarian/bitmask.asm"

CorsolaPlainBitmasks:    INCLUDE "gfx/pokemon/corsola_plain/bitmask.asm"
CorsolaGalarianBitmasks: INCLUDE "gfx/pokemon/corsola_galarian/bitmask.asm"

EOrangePlainBitmasks:   INCLUDE "gfx/pokemon/eorange_plain/bitmask.asm"
EOrangeHisuianBitmasks: INCLUDE "gfx/pokemon/eorange_hisuian/bitmask.asm"

CKurumiPlainBitmasks:   INCLUDE "gfx/pokemon/ckurumi_plain/bitmask.asm"
CKurumiHisuianBitmasks: INCLUDE "gfx/pokemon/ckurumi_hisuian/bitmask.asm"

EDaichanPlainBitmasks:   INCLUDE "gfx/pokemon/edaichan_plain/bitmask.asm"
EDaichanHisuianBitmasks: INCLUDE "gfx/pokemon/edaichan_hisuian/bitmask.asm"

CCirnoPlainBitmasks:   INCLUDE "gfx/pokemon/ccirno_plain/bitmask.asm"
CCirnoHisuianBitmasks: INCLUDE "gfx/pokemon/ccirno_hisuian/bitmask.asm"

EReisenPlainBitmasks:   INCLUDE "gfx/pokemon/ereisen_plain/bitmask.asm"
EReisenHisuianBitmasks: INCLUDE "gfx/pokemon/ereisen_hisuian/bitmask.asm"

QwilfishPlainBitmasks:   INCLUDE "gfx/pokemon/qwilfish_plain/bitmask.asm"
QwilfishHisuianBitmasks: INCLUDE "gfx/pokemon/qwilfish_hisuian/bitmask.asm"

SneaselPlainBitmasks:   INCLUDE "gfx/pokemon/sneasel_plain/bitmask.asm"
SneaselHisuianBitmasks: INCLUDE "gfx/pokemon/sneasel_hisuian/bitmask.asm"

WooperPlainBitmasks:    INCLUDE "gfx/pokemon/wooper_plain/bitmask.asm"
WooperPaldeanBitmasks:  INCLUDE "gfx/pokemon/wooper_paldean/bitmask.asm"

TaurosPlainBitmasks:        INCLUDE "gfx/pokemon/tauros_plain/bitmask.asm"
TaurosPaldeanBitmasks:      INCLUDE "gfx/pokemon/tauros_paldean/bitmask.asm"
TaurosPaldeanFireBitmasks:  INCLUDE "gfx/pokemon/tauros_paldean_fire/bitmask.asm"
TaurosPaldeanWaterBitmasks: INCLUDE "gfx/pokemon/tauros_paldean_water/bitmask.asm"
