CReimuAnimationExtra:  INCLUDE "gfx/pokemon/creimu/anim_idle.asm"
ReimuAnimationExtra:    INCLUDE "gfx/pokemon/reimu/anim_idle.asm"
TReimuAnimationExtra:   INCLUDE "gfx/pokemon/treimu/anim_idle.asm"
CMarisaAnimationExtra: INCLUDE "gfx/pokemon/cmarisa/anim_idle.asm"
MarisaAnimationExtra: INCLUDE "gfx/pokemon/marisa/anim_idle.asm"
AMarisaAnimationExtra:  INCLUDE "gfx/pokemon/amarisa/anim_idle.asm"
CSakuyaAnimationExtra:   INCLUDE "gfx/pokemon/csakuya/anim_idle.asm"
SakuyaAnimationExtra:  INCLUDE "gfx/pokemon/sakuya/anim_idle.asm"
HSakuyaAnimationExtra:  INCLUDE "gfx/pokemon/hsakuya/anim_idle.asm"
CGyokuAnimationExtra:   INCLUDE "gfx/pokemon/cgyoku/anim_idle.asm"
MGyokuAnimationExtra:    INCLUDE "gfx/pokemon/mgyoku/anim_idle.asm"
FGyokuAnimationExtra: INCLUDE "gfx/pokemon/fgyoku/anim_idle.asm"
OGyokuAnimationExtra:     INCLUDE "gfx/pokemon/ogyoku/anim_idle.asm"
CMaganAnimationExtra:     INCLUDE "gfx/pokemon/cmagan/anim_idle.asm"
MaganAnimationExtra:   INCLUDE "gfx/pokemon/magan/anim_idle.asm"
CMimaAnimationExtra:  INCLUDE "gfx/pokemon/cmima/anim_idle.asm"
MimaAnimationExtra:    INCLUDE "gfx/pokemon/mima/anim_idle.asm"
ElisAnimationExtra:    INCLUDE "gfx/pokemon/elis/anim_idle.asm"
CKikuriAnimationExtra:      INCLUDE "gfx/pokemon/ckikuri/anim_idle.asm"
CKongaraAnimationExtra:   INCLUDE "gfx/pokemon/ckongara/anim_idle.asm"
KongaraAnimationExtra:   INCLUDE "gfx/pokemon/kongara/anim_idle.asm"
CRikaAnimationExtra:   INCLUDE "gfx/pokemon/crika/anim_idle.asm"
RikaAnimationExtra:   INCLUDE "gfx/pokemon/rika/anim_idle.asm"
ARikaAnimationExtra:   INCLUDE "gfx/pokemon/arika/anim_idle.asm"
CMeiraAnimationExtra:   INCLUDE "gfx/pokemon/cmeira/anim_idle.asm"
MeiraAnimationExtra:   INCLUDE "gfx/pokemon/meira/anim_idle.asm"
EllenAnimationExtra: INCLUDE "gfx/pokemon/ellen/anim_idle.asm"
CKotohimeAnimationExtra:      INCLUDE "gfx/pokemon/ckotohime/anim_idle.asm"
KotohimeAnimationExtra:     INCLUDE "gfx/pokemon/kotohime/anim_idle.asm"
CKanaAnimationExtra:      INCLUDE "gfx/pokemon/ckana/anim_idle.asm"
KanaAnimationExtra:  INCLUDE "gfx/pokemon/kana/anim_idle.asm"
CRikakoAnimationExtra:   INCLUDE "gfx/pokemon/crikako/anim_idle.asm"
RikakoAnimationExtra:    INCLUDE "gfx/pokemon/rikako/anim_idle.asm"
YumemiAnimationExtra:    INCLUDE "gfx/pokemon/yumemi/anim_idle.asm"
COrangeAnimationExtra:     INCLUDE "gfx/pokemon/corange/anim_idle.asm"
OrangeAnimationExtra:   INCLUDE "gfx/pokemon/orange/anim_idle.asm"
KurumiAnimationExtra:    INCLUDE "gfx/pokemon/kurumi/anim_idle.asm"
CEllyAnimationExtra:  INCLUDE "gfx/pokemon/celly/anim_idle.asm"
EllyAnimationExtra:       INCLUDE "gfx/pokemon/elly/anim_idle.asm"
CYukaAnimationExtra:   INCLUDE "gfx/pokemon/cyuka/anim_idle.asm"
YukaAnimationExtra:     INCLUDE "gfx/pokemon/yuka/anim_idle.asm"
AYukaAnimationExtra:    INCLUDE "gfx/pokemon/ayuka/anim_idle.asm"
CMugetsuAnimationExtra:    INCLUDE "gfx/pokemon/cmugetsu/anim_idle.asm"
MugetsuAnimationExtra: INCLUDE "gfx/pokemon/mugetsu/anim_idle.asm"
CGengetsuAnimationExtra: INCLUDE "gfx/pokemon/cgengetsu/anim_idle.asm"
GengetsuAnimationExtra:  INCLUDE "gfx/pokemon/gengetsu/anim_idle.asm"
AliceAnimationExtra:  INCLUDE "gfx/pokemon/alice/anim_idle.asm"
AAliceAnimationExtra:   INCLUDE "gfx/pokemon/aalice/anim_idle.asm"
MaiAnimationExtra:      INCLUDE "gfx/pokemon/mai/anim_idle.asm"
CYukiAnimationExtra:       INCLUDE "gfx/pokemon/cyuki/anim_idle.asm"
YukiAnimationExtra:    INCLUDE "gfx/pokemon/yuki/anim_idle.asm"
YumekoAnimationExtra:   INCLUDE "gfx/pokemon/yumeko/anim_idle.asm"
CShinkiAnimationExtra:     INCLUDE "gfx/pokemon/cshinki/anim_idle.asm"
ShinkiAnimationExtra:    INCLUDE "gfx/pokemon/shinki/anim_idle.asm"
CRumiaAnimationExtra:       INCLUDE "gfx/pokemon/crumia/anim_idle.asm"
RumiaAnimationExtra:    INCLUDE "gfx/pokemon/rumia/anim_idle.asm"
ARumiaAnimationExtra:      INCLUDE "gfx/pokemon/arumia/anim_idle.asm"
CDaichanAnimationExtra:     INCLUDE "gfx/pokemon/cdaichan/anim_idle.asm"
DaichanAnimationExtra:    INCLUDE "gfx/pokemon/daichan/anim_idle.asm"
CirnoAnimationExtra:  INCLUDE "gfx/pokemon/cirno/anim_idle.asm"
CMeilingAnimationExtra:     INCLUDE "gfx/pokemon/cmeiling/anim_idle.asm"
AMeilingAnimationExtra:  INCLUDE "gfx/pokemon/ameiling/anim_idle.asm"
CKoakumaAnimationExtra: INCLUDE "gfx/pokemon/ckoakuma/anim_idle.asm"
KoakumaAnimationExtra:  INCLUDE "gfx/pokemon/koakuma/anim_idle.asm"
HKoakumaAnimationExtra:    INCLUDE "gfx/pokemon/hkoakuma/anim_idle.asm"
PatchouliAnimationExtra:    INCLUDE "gfx/pokemon/patchouli/anim_idle.asm"
TPatchouliAnimationExtra:     INCLUDE "gfx/pokemon/tpatchouli/anim_idle.asm"
CRemiliaAnimationExtra:    INCLUDE "gfx/pokemon/cremilia/anim_idle.asm"
RemiliaAnimationExtra:    INCLUDE "gfx/pokemon/remilia/anim_idle.asm"
SRemiliaAnimationExtra: INCLUDE "gfx/pokemon/sremilia/anim_idle.asm"
CFlandreAnimationExtra:     INCLUDE "gfx/pokemon/cflandre/anim_idle.asm"
FlandreAnimationExtra:     INCLUDE "gfx/pokemon/flandre/anim_idle.asm"
AFlandreAnimationExtra:    INCLUDE "gfx/pokemon/aflandre/anim_idle.asm"
CLettyAnimationExtra:    INCLUDE "gfx/pokemon/cletty/anim_idle.asm"
LettyAnimationExtra:     INCLUDE "gfx/pokemon/letty/anim_idle.asm"
DLettyAnimationExtra:    INCLUDE "gfx/pokemon/dletty/anim_idle.asm"
ChenAnimationExtra:    INCLUDE "gfx/pokemon/chen/anim_idle.asm"
HChenAnimationExtra:       INCLUDE "gfx/pokemon/hchen/anim_idle.asm"
CLilyWhiteAnimationExtra: INCLUDE "gfx/pokemon/clilywhite/anim_idle.asm"
LilyWhiteAnimationExtra:     INCLUDE "gfx/pokemon/lilywhite/anim_idle.asm"
DLilyWhiteAnimationExtra:     INCLUDE "gfx/pokemon/dlilywhite/anim_idle.asm"
CLyricaAnimationExtra:     INCLUDE "gfx/pokemon/clyrica/anim_idle.asm"
LyricaAnimationExtra:      INCLUDE "gfx/pokemon/lyrica/anim_idle.asm"
TLyricaAnimationExtra:      INCLUDE "gfx/pokemon/tlyrica/anim_idle.asm"
CMerlinAnimationExtra:   INCLUDE "gfx/pokemon/cmerlin/anim_idle.asm"
MerlinAnimationExtra:    INCLUDE "gfx/pokemon/merlin/anim_idle.asm"
SMerlinAnimationExtra:    INCLUDE "gfx/pokemon/smerlin/anim_idle.asm"
CLunasaAnimationExtra:    INCLUDE "gfx/pokemon/clunasa/anim_idle.asm"
LunasaAnimationExtra:    INCLUDE "gfx/pokemon/lunasa/anim_idle.asm"
ALunasaAnimationExtra:    INCLUDE "gfx/pokemon/alunasa/anim_idle.asm"
CYuyukoAnimationExtra:     INCLUDE "gfx/pokemon/cyuyuko/anim_idle.asm"
YuyukoAnimationExtra:   INCLUDE "gfx/pokemon/yuyuko/anim_idle.asm"
AYuyukoAnimationExtra: INCLUDE "gfx/pokemon/ayuyuko/anim_idle.asm"
CRanAnimationExtra:    INCLUDE "gfx/pokemon/cran/anim_idle.asm"
YukariAnimationExtra:    INCLUDE "gfx/pokemon/yukari/anim_idle.asm"
TYukariAnimationExtra:  INCLUDE "gfx/pokemon/tyukari/anim_idle.asm"
CSuikaAnimationExtra:  INCLUDE "gfx/pokemon/csuika/anim_idle.asm"
TSuikaAnimationExtra:        INCLUDE "gfx/pokemon/tsuika/anim_idle.asm"
CYoumuAnimationExtra:  INCLUDE "gfx/pokemon/cyoumu/anim_idle.asm"
YoumuAnimationExtra:    INCLUDE "gfx/pokemon/youmu/anim_idle.asm"
SYoumuAnimationExtra:   INCLUDE "gfx/pokemon/syoumu/anim_idle.asm"
CReisenAnimationExtra:  INCLUDE "gfx/pokemon/creisen/anim_idle.asm"
ReisenAnimationExtra:    INCLUDE "gfx/pokemon/reisen/anim_idle.asm"
CSanaeAnimationExtra:   INCLUDE "gfx/pokemon/csanae/anim_idle.asm"
SanaeAnimationExtra:   INCLUDE "gfx/pokemon/sanae/anim_idle.asm"
DSanaeAnimationExtra: INCLUDE "gfx/pokemon/dsanae/anim_idle.asm"
SentretAnimationExtra:    INCLUDE "gfx/pokemon/sentret/anim_idle.asm"
FurretAnimationExtra:     INCLUDE "gfx/pokemon/furret/anim_idle.asm"
HoothootAnimationExtra:   INCLUDE "gfx/pokemon/hoothoot/anim_idle.asm"
NoctowlAnimationExtra:    INCLUDE "gfx/pokemon/noctowl/anim_idle.asm"
LedybaAnimationExtra:     INCLUDE "gfx/pokemon/ledyba/anim_idle.asm"
LedianAnimationExtra:     INCLUDE "gfx/pokemon/ledian/anim_idle.asm"
SpinarakAnimationExtra:   INCLUDE "gfx/pokemon/spinarak/anim_idle.asm"
AriadosAnimationExtra:    INCLUDE "gfx/pokemon/ariados/anim_idle.asm"
CrobatAnimationExtra:     INCLUDE "gfx/pokemon/crobat/anim_idle.asm"
ChinchouAnimationExtra:   INCLUDE "gfx/pokemon/chinchou/anim_idle.asm"
LanturnAnimationExtra:    INCLUDE "gfx/pokemon/lanturn/anim_idle.asm"
CleffaAnimationExtra:     INCLUDE "gfx/pokemon/cleffa/anim_idle.asm"
IgglybuffAnimationExtra:  INCLUDE "gfx/pokemon/igglybuff/anim_idle.asm"
TogepiAnimationExtra:     INCLUDE "gfx/pokemon/togepi/anim_idle.asm"
TogeticAnimationExtra:    INCLUDE "gfx/pokemon/togetic/anim_idle.asm"
NatuAnimationExtra:       INCLUDE "gfx/pokemon/natu/anim_idle.asm"
XatuAnimationExtra:       INCLUDE "gfx/pokemon/xatu/anim_idle.asm"
MareepAnimationExtra:     INCLUDE "gfx/pokemon/mareep/anim_idle.asm"
FlaaffyAnimationExtra:    INCLUDE "gfx/pokemon/flaaffy/anim_idle.asm"
AmpharosAnimationExtra:   INCLUDE "gfx/pokemon/ampharos/anim_idle.asm"
BellossomAnimationExtra:  INCLUDE "gfx/pokemon/bellossom/anim_idle.asm"
SudowoodoAnimationExtra:  INCLUDE "gfx/pokemon/sudowoodo/anim_idle.asm"
MarillAnimationExtra:     INCLUDE "gfx/pokemon/marill/anim_idle.asm"
AzumarillAnimationExtra:  INCLUDE "gfx/pokemon/azumarill/anim_idle.asm"
PolitoedAnimationExtra:   INCLUDE "gfx/pokemon/politoed/anim_idle.asm"
HoppipAnimationExtra:     INCLUDE "gfx/pokemon/hoppip/anim_idle.asm"
SkiploomAnimationExtra:   INCLUDE "gfx/pokemon/skiploom/anim_idle.asm"
JumpluffAnimationExtra:   INCLUDE "gfx/pokemon/jumpluff/anim_idle.asm"
AipomAnimationExtra:      INCLUDE "gfx/pokemon/aipom/anim_idle.asm"
SunkernAnimationExtra:    INCLUDE "gfx/pokemon/sunkern/anim_idle.asm"
SunfloraAnimationExtra:   INCLUDE "gfx/pokemon/sunflora/anim_idle.asm"
YanmaAnimationExtra:      INCLUDE "gfx/pokemon/yanma/anim_idle.asm"
QuagsireAnimationExtra:   INCLUDE "gfx/pokemon/quagsire/anim_idle.asm"
EspeonAnimationExtra:     INCLUDE "gfx/pokemon/espeon/anim_idle.asm"
UmbreonAnimationExtra:    INCLUDE "gfx/pokemon/umbreon/anim_idle.asm"
MurkrowAnimationExtra:    INCLUDE "gfx/pokemon/murkrow/anim_idle.asm"
MisdreavusAnimationExtra: INCLUDE "gfx/pokemon/misdreavus/anim_idle.asm"
WobbuffetAnimationExtra:  INCLUDE "gfx/pokemon/wobbuffet/anim_idle.asm"
GirafarigAnimationExtra:  INCLUDE "gfx/pokemon/girafarig/anim_idle.asm"
PinecoAnimationExtra:     INCLUDE "gfx/pokemon/pineco/anim_idle.asm"
ForretressAnimationExtra: INCLUDE "gfx/pokemon/forretress/anim_idle.asm"
DunsparceAnimationExtra:  INCLUDE "gfx/pokemon/dunsparce/anim_idle.asm"
GligarAnimationExtra:     INCLUDE "gfx/pokemon/gligar/anim_idle.asm"
SteelixAnimationExtra:    INCLUDE "gfx/pokemon/steelix/anim_idle.asm"
SnubbullAnimationExtra:   INCLUDE "gfx/pokemon/snubbull/anim_idle.asm"
GranbullAnimationExtra:   INCLUDE "gfx/pokemon/granbull/anim_idle.asm"
ScizorAnimationExtra:     INCLUDE "gfx/pokemon/scizor/anim_idle.asm"
ShuckleAnimationExtra:    INCLUDE "gfx/pokemon/shuckle/anim_idle.asm"
HeracrossAnimationExtra:  INCLUDE "gfx/pokemon/heracross/anim_idle.asm"
TeddiursaAnimationExtra:  INCLUDE "gfx/pokemon/teddiursa/anim_idle.asm"
UrsaringAnimationExtra:   INCLUDE "gfx/pokemon/ursaring/anim_idle.asm"
SlugmaAnimationExtra:     INCLUDE "gfx/pokemon/slugma/anim_idle.asm"
MagcargoAnimationExtra:   INCLUDE "gfx/pokemon/magcargo/anim_idle.asm"
SwinubAnimationExtra:     INCLUDE "gfx/pokemon/swinub/anim_idle.asm"
PiloswineAnimationExtra:  INCLUDE "gfx/pokemon/piloswine/anim_idle.asm"
RemoraidAnimationExtra:   INCLUDE "gfx/pokemon/remoraid/anim_idle.asm"
OctilleryAnimationExtra:  INCLUDE "gfx/pokemon/octillery/anim_idle.asm"
DelibirdAnimationExtra:   INCLUDE "gfx/pokemon/delibird/anim_idle.asm"
MantineAnimationExtra:    INCLUDE "gfx/pokemon/mantine/anim_idle.asm"
SkarmoryAnimationExtra:   INCLUDE "gfx/pokemon/skarmory/anim_idle.asm"
HoundourAnimationExtra:   INCLUDE "gfx/pokemon/houndour/anim_idle.asm"
HoundoomAnimationExtra:   INCLUDE "gfx/pokemon/houndoom/anim_idle.asm"
KingdraAnimationExtra:    INCLUDE "gfx/pokemon/kingdra/anim_idle.asm"
PhanpyAnimationExtra:     INCLUDE "gfx/pokemon/phanpy/anim_idle.asm"
DonphanAnimationExtra:    INCLUDE "gfx/pokemon/donphan/anim_idle.asm"
CLunasa2AnimationExtra:   INCLUDE "gfx/pokemon/clunasa2/anim_idle.asm"
StantlerAnimationExtra:   INCLUDE "gfx/pokemon/stantler/anim_idle.asm"
SmeargleAnimationExtra:   INCLUDE "gfx/pokemon/smeargle/anim_idle.asm"
TyrogueAnimationExtra:    INCLUDE "gfx/pokemon/tyrogue/anim_idle.asm"
HitmontopAnimationExtra:  INCLUDE "gfx/pokemon/hitmontop/anim_idle.asm"
SmoochumAnimationExtra:   INCLUDE "gfx/pokemon/smoochum/anim_idle.asm"
ElekidAnimationExtra:     INCLUDE "gfx/pokemon/elekid/anim_idle.asm"
MagbyAnimationExtra:      INCLUDE "gfx/pokemon/magby/anim_idle.asm"
MiltankAnimationExtra:    INCLUDE "gfx/pokemon/miltank/anim_idle.asm"
BlisseyAnimationExtra:    INCLUDE "gfx/pokemon/blissey/anim_idle.asm"
RaikouAnimationExtra:     INCLUDE "gfx/pokemon/raikou/anim_idle.asm"
EnteiAnimationExtra:      INCLUDE "gfx/pokemon/entei/anim_idle.asm"
SuicuneAnimationExtra:    INCLUDE "gfx/pokemon/suicune/anim_idle.asm"
LarvitarAnimationExtra:   INCLUDE "gfx/pokemon/larvitar/anim_idle.asm"
PupitarAnimationExtra:    INCLUDE "gfx/pokemon/pupitar/anim_idle.asm"
TyranitarAnimationExtra:  INCLUDE "gfx/pokemon/tyranitar/anim_idle.asm"
LugiaAnimationExtra:      INCLUDE "gfx/pokemon/lugia/anim_idle.asm"
HoOhAnimationExtra:       INCLUDE "gfx/pokemon/ho_oh/anim_idle.asm"
CelebiAnimationExtra:     INCLUDE "gfx/pokemon/celebi/anim_idle.asm"
AzurillAnimationExtra:    INCLUDE "gfx/pokemon/azurill/anim_idle.asm"
WynautAnimationExtra:     INCLUDE "gfx/pokemon/wynaut/anim_idle.asm"
AmbipomAnimationExtra:    INCLUDE "gfx/pokemon/ambipom/anim_idle.asm"
MismagiusAnimationExtra:  INCLUDE "gfx/pokemon/mismagius/anim_idle.asm"
HonchkrowAnimationExtra:  INCLUDE "gfx/pokemon/honchkrow/anim_idle.asm"
BonslyAnimationExtra:     INCLUDE "gfx/pokemon/bonsly/anim_idle.asm"
MimeJrAnimationExtra:     INCLUDE "gfx/pokemon/mime_jr_/anim_idle.asm"
HappinyAnimationExtra:    INCLUDE "gfx/pokemon/happiny/anim_idle.asm"
MunchlaxAnimationExtra:   INCLUDE "gfx/pokemon/munchlax/anim_idle.asm"
MantykeAnimationExtra:    INCLUDE "gfx/pokemon/mantyke/anim_idle.asm"
WeavileAnimationExtra:    INCLUDE "gfx/pokemon/weavile/anim_idle.asm"
MagnezoneAnimationExtra:  INCLUDE "gfx/pokemon/magnezone/anim_idle.asm"
LickilickyAnimationExtra: INCLUDE "gfx/pokemon/lickilicky/anim_idle.asm"
RhyperiorAnimationExtra:  INCLUDE "gfx/pokemon/rhyperior/anim_idle.asm"
TangrowthAnimationExtra:  INCLUDE "gfx/pokemon/tangrowth/anim_idle.asm"
ElectivireAnimationExtra: INCLUDE "gfx/pokemon/electivire/anim_idle.asm"
MagmortarAnimationExtra:  INCLUDE "gfx/pokemon/magmortar/anim_idle.asm"
TogekissAnimationExtra:   INCLUDE "gfx/pokemon/togekiss/anim_idle.asm"
YanmegaAnimationExtra:    INCLUDE "gfx/pokemon/yanmega/anim_idle.asm"
LeafeonAnimationExtra:    INCLUDE "gfx/pokemon/leafeon/anim_idle.asm"
GlaceonAnimationExtra:    INCLUDE "gfx/pokemon/glaceon/anim_idle.asm"
GliscorAnimationExtra:    INCLUDE "gfx/pokemon/gliscor/anim_idle.asm"
MamoswineAnimationExtra:  INCLUDE "gfx/pokemon/mamoswine/anim_idle.asm"
CLunasaZAnimationExtra:   INCLUDE "gfx/pokemon/clunasa_z/anim_idle.asm"
SylveonAnimationExtra:    INCLUDE "gfx/pokemon/sylveon/anim_idle.asm"
PerrserkerAnimationExtra: INCLUDE "gfx/pokemon/perrserker/anim_idle.asm"
CursolaAnimationExtra:    INCLUDE "gfx/pokemon/cursola/anim_idle.asm"
SirfetchDAnimationExtra:  INCLUDE "gfx/pokemon/sirfetch_d/anim_idle.asm"
MrRimeAnimationExtra:     INCLUDE "gfx/pokemon/mr__rime/anim_idle.asm"
WyrdeerAnimationExtra:    INCLUDE "gfx/pokemon/wyrdeer/anim_idle.asm"
KleavorAnimationExtra:    INCLUDE "gfx/pokemon/kleavor/anim_idle.asm"
UrsalunaAnimationExtra:   INCLUDE "gfx/pokemon/ursaluna/anim_idle.asm"
SneaslerAnimationExtra:   INCLUDE "gfx/pokemon/sneasler/anim_idle.asm"
OverqwilAnimationExtra:   INCLUDE "gfx/pokemon/overqwil/anim_idle.asm"
FarigirafAnimationExtra:  INCLUDE "gfx/pokemon/farigiraf/anim_idle.asm"
ClodsireAnimationExtra:   INCLUDE "gfx/pokemon/clodsire/anim_idle.asm"
AnnihilapeAnimationExtra: INCLUDE "gfx/pokemon/annihilape/anim_idle.asm"

EggAnimationExtra:        INCLUDE "gfx/pokemon/egg/anim_idle.asm"

UnownAAnimationExtra: INCLUDE "gfx/pokemon/unown_a/anim_idle.asm"
UnownBAnimationExtra: INCLUDE "gfx/pokemon/unown_b/anim_idle.asm"
UnownCAnimationExtra: INCLUDE "gfx/pokemon/unown_c/anim_idle.asm"
UnownDAnimationExtra: INCLUDE "gfx/pokemon/unown_d/anim_idle.asm"
UnownEAnimationExtra: INCLUDE "gfx/pokemon/unown_e/anim_idle.asm"
UnownFAnimationExtra: INCLUDE "gfx/pokemon/unown_f/anim_idle.asm"
UnownGAnimationExtra: INCLUDE "gfx/pokemon/unown_g/anim_idle.asm"
UnownHAnimationExtra: INCLUDE "gfx/pokemon/unown_h/anim_idle.asm"
UnownIAnimationExtra: INCLUDE "gfx/pokemon/unown_i/anim_idle.asm"
UnownJAnimationExtra: INCLUDE "gfx/pokemon/unown_j/anim_idle.asm"
UnownKAnimationExtra: INCLUDE "gfx/pokemon/unown_k/anim_idle.asm"
UnownLAnimationExtra: INCLUDE "gfx/pokemon/unown_l/anim_idle.asm"
UnownMAnimationExtra: INCLUDE "gfx/pokemon/unown_m/anim_idle.asm"
UnownNAnimationExtra: INCLUDE "gfx/pokemon/unown_n/anim_idle.asm"
UnownOAnimationExtra: INCLUDE "gfx/pokemon/unown_o/anim_idle.asm"
UnownPAnimationExtra: INCLUDE "gfx/pokemon/unown_p/anim_idle.asm"
UnownQAnimationExtra: INCLUDE "gfx/pokemon/unown_q/anim_idle.asm"
UnownRAnimationExtra: INCLUDE "gfx/pokemon/unown_r/anim_idle.asm"
UnownSAnimationExtra: INCLUDE "gfx/pokemon/unown_s/anim_idle.asm"
UnownTAnimationExtra: INCLUDE "gfx/pokemon/unown_t/anim_idle.asm"
UnownUAnimationExtra: INCLUDE "gfx/pokemon/unown_u/anim_idle.asm"
UnownVAnimationExtra: INCLUDE "gfx/pokemon/unown_v/anim_idle.asm"
UnownWAnimationExtra: INCLUDE "gfx/pokemon/unown_w/anim_idle.asm"
UnownXAnimationExtra: INCLUDE "gfx/pokemon/unown_x/anim_idle.asm"
UnownYAnimationExtra: INCLUDE "gfx/pokemon/unown_y/anim_idle.asm"
UnownZAnimationExtra: INCLUDE "gfx/pokemon/unown_z/anim_idle.asm"
UnownExclamationAnimationExtra: INCLUDE "gfx/pokemon/unown_exclamation/anim_idle.asm"
UnownQuestionAnimationExtra:    INCLUDE "gfx/pokemon/unown_question/anim_idle.asm"

PichuAnimationExtra: INCLUDE "gfx/pokemon/pichu/anim_idle.asm"
PichuSpikyAnimationExtra: INCLUDE "gfx/pokemon/pichu_spiky/anim_idle.asm"

KikuriJohtoAnimationExtra:  INCLUDE "gfx/pokemon/kikuri_johto/anim_idle.asm"
KikuriKantoAnimationExtra:  INCLUDE "gfx/pokemon/kikuri_kanto/anim_idle.asm"
KikuriKogaAnimationExtra:   INCLUDE "gfx/pokemon/kikuri_koga/anim_idle.asm"
KikuriAgathaAnimationExtra: INCLUDE "gfx/pokemon/kikuri_agatha/anim_idle.asm"
KikuriArianaAnimationExtra: INCLUDE "gfx/pokemon/kikuri_ariana/anim_idle.asm"

LilyBlackAnimationExtra:
LilyBlackSkellyAnimationExtra:
LilyBlackCalico1AnimationExtra:
LilyBlackCalico2AnimationExtra:
LilyBlackCalico3AnimationExtra:
LilyBlackTwoToneAnimationExtra:
LilyBlackOrcaAnimationExtra:
LilyBlackDapplesAnimationExtra:
LilyBlackTigerAnimationExtra:
LilyBlackZebraAnimationExtra:
LilyBlackStripeAnimationExtra:
LilyBlackBubblesAnimationExtra:
LilyBlackDiamondsAnimationExtra:
LilyBlackPatchesAnimationExtra:
LilyBlackForehead1AnimationExtra:
LilyBlackMask1AnimationExtra:
LilyBlackForehead2AnimationExtra:
LilyBlackMask2AnimationExtra:
LilyBlackSaucyAnimationExtra:
LilyBlackRaindropAnimationExtra: INCLUDE "gfx/pokemon/lilyblack/anim_idle.asm"

DudunsparceTwoSegmentAnimationExtra:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim_idle.asm"
DudunsparceThreeSegmentAnimationExtra: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim_idle.asm"

SLilyBlackAnimationExtra: INCLUDE "gfx/pokemon/slilyblack/anim_idle.asm"
SLilyBlackRedAnimationExtra:   INCLUDE "gfx/pokemon/slilyblack_red/anim_idle.asm"

SuikaAnimationExtra:   INCLUDE "gfx/pokemon/suika/anim_idle.asm"
SuikaArmoredAnimationExtra: INCLUDE "gfx/pokemon/suika_armored/anim_idle.asm"

CElisAnimationExtra:  INCLUDE "gfx/pokemon/celis/anim_idle.asm"

CSarielAnimationExtra:  INCLUDE "gfx/pokemon/csariel/anim_idle.asm"

SarielAnimationExtra:  INCLUDE "gfx/pokemon/sariel/anim_idle.asm"

CEllenAnimationExtra:  INCLUDE "gfx/pokemon/cellen/anim_idle.asm"

CChiyuriAnimationExtra:  INCLUDE "gfx/pokemon/cchiyuri/anim_idle.asm"

ChiyuriAnimationExtra:  INCLUDE "gfx/pokemon/chiyuri/anim_idle.asm"

CYumemiAnimationExtra:  INCLUDE "gfx/pokemon/cyumemi/anim_idle.asm"

CSaraAnimationExtra:  INCLUDE "gfx/pokemon/csara/anim_idle.asm"

SaraAnimationExtra:  INCLUDE "gfx/pokemon/sara/anim_idle.asm"

CYumekoAnimationExtra:  INCLUDE "gfx/pokemon/cyumeko/anim_idle.asm"

SCirnoAnimationExtra:  INCLUDE "gfx/pokemon/scirno/anim_idle.asm"

MeilingAnimationExtra:  INCLUDE "gfx/pokemon/meiling/anim_idle.asm"

CLuizeAnimationExtra:    INCLUDE "gfx/pokemon/cluize/anim_idle.asm"

LuizeAnimationExtra:    INCLUDE "gfx/pokemon/luize/anim_idle.asm"

DLuizeAnimationExtra:   INCLUDE "gfx/pokemon/dluize/anim_idle.asm"

CAliceAnimationExtra:    INCLUDE "gfx/pokemon/calice/anim_idle.asm"

CMaiAnimationExtra:     INCLUDE "gfx/pokemon/cmai/anim_idle.asm"

CPatchouliAnimationExtra:    INCLUDE "gfx/pokemon/cpatchouli/anim_idle.asm"

CChenAnimationExtra:    INCLUDE "gfx/pokemon/cchen/anim_idle.asm"

RanAnimationExtra:    INCLUDE "gfx/pokemon/ran/anim_idle.asm"

TRanAnimationExtra:    INCLUDE "gfx/pokemon/tran/anim_idle.asm"

CYukariAnimationExtra:    INCLUDE "gfx/pokemon/cyukari/anim_idle.asm"

SlowkingAnimationExtra:    INCLUDE "gfx/pokemon/slowking/anim_idle.asm"

CorsolaAnimationExtra:    INCLUDE "gfx/pokemon/corsola/anim_idle.asm"

CKurumiAnimationExtra:   INCLUDE "gfx/pokemon/ckurumi/anim_idle.asm"

DDaichanAnimationExtra:   INCLUDE "gfx/pokemon/ddaichan/anim_idle.asm"

CCirnoAnimationExtra:   INCLUDE "gfx/pokemon/ccirno/anim_idle.asm"

TReisenAnimationExtra:   INCLUDE "gfx/pokemon/treisen/anim_idle.asm"

QwilfishAnimationExtra:   INCLUDE "gfx/pokemon/qwilfish/anim_idle.asm"

SneaselAnimationExtra:   INCLUDE "gfx/pokemon/sneasel/anim_idle.asm"

WooperAnimationExtra:   INCLUDE "gfx/pokemon/wooper/anim_idle.asm"

CLilyBlackAnimationExtra:        INCLUDE "gfx/pokemon/clilyblack/anim_idle.asm"
