AnimationExtraPointers:
	table_width 2, AnimationExtraPointers
	dw CReimuAnimationExtra
	dw ReimuAnimationExtra
	dw TReimuAnimationExtra
	dw CMarisaAnimationExtra
	dw MarisaAnimationExtra
	dw AMarisaAnimationExtra
	dw CSakuyaAnimationExtra
	dw SakuyaAnimationExtra
	dw HSakuyaAnimationExtra
	dw CGyokuAnimationExtra
	dw MGyokuAnimationExtra
	dw FGyokuAnimationExtra
	dw OGyokuAnimationExtra
	dw CMaganAnimationExtra
	dw MaganAnimationExtra
	dw CMimaAnimationExtra
	dw MimaAnimationExtra
	dw CElisAnimationExtra
	dw ElisAnimationExtra
	dw CKikuriAnimationExtra
	dw KikuriJohtoAnimationExtra
	dw CSarielAnimationExtra
	dw SarielAnimationExtra
	dw CKongaraAnimationExtra
	dw KongaraAnimationExtra
	dw CRikaAnimationExtra
	dw RikaAnimationExtra
	dw ARikaAnimationExtra
	dw CMeiraAnimationExtra
	dw MeiraAnimationExtra
	dw CEllenAnimationExtra
	dw EllenAnimationExtra
	dw CKotohimeAnimationExtra
	dw KotohimeAnimationExtra
	dw CKanaAnimationExtra
	dw KanaAnimationExtra
	dw CRikakoAnimationExtra
	dw RikakoAnimationExtra
	dw CChiyuriAnimationExtra
	dw ChiyuriAnimationExtra
	dw CYumemiAnimationExtra
	dw YumemiAnimationExtra
	dw COrangeAnimationExtra
	dw OrangeAnimationExtra
	dw CKurumiAnimationExtra
	dw KurumiAnimationExtra
	dw CEllyAnimationExtra
	dw EllyAnimationExtra
	dw CYukaAnimationExtra
	dw YukaAnimationExtra
	dw AYukaAnimationExtra
	dw CMugetsuAnimationExtra
	dw MugetsuAnimationExtra
	dw CGengetsuAnimationExtra
	dw GengetsuAnimationExtra
	dw CSaraAnimationExtra
	dw SaraAnimationExtra
	dw CLuizeAnimationExtra
	dw LuizeAnimationExtra
	dw DLuizeAnimationExtra
	dw CAliceAnimationExtra
	dw AliceAnimationExtra
	dw AAliceAnimationExtra
	dw CMaiAnimationExtra
	dw MaiAnimationExtra
	dw CYukiAnimationExtra
	dw YukiAnimationExtra
	dw CYumekoAnimationExtra
	dw YumekoAnimationExtra
	dw CShinkiAnimationExtra
	dw ShinkiAnimationExtra
	dw CRumiaAnimationExtra
	dw RumiaAnimationExtra
	dw ARumiaAnimationExtra
	dw CDaichanAnimationExtra
	dw DaichanAnimationExtra
	dw DDaichanAnimationExtra
	dw CCirnoAnimationExtra
	dw CirnoAnimationExtra
	dw SCirnoAnimationExtra
	dw CMeilingAnimationExtra
	dw MeilingAnimationExtra
	dw AMeilingAnimationExtra
	dw CKoakumaAnimationExtra
	dw KoakumaAnimationExtra
	dw HKoakumaAnimationExtra
	dw CPatchouliAnimationExtra
	dw PatchouliAnimationExtra
	dw TPatchouliAnimationExtra
	dw CRemiliaAnimationExtra
	dw RemiliaAnimationExtra
	dw SRemiliaAnimationExtra
	dw CFlandreAnimationExtra
	dw FlandreAnimationExtra
	dw AFlandreAnimationExtra
	dw CLettyAnimationExtra
	dw LettyAnimationExtra
	dw DLettyAnimationExtra
	dw CChenAnimationExtra
	dw ChenAnimationExtra
	dw HChenAnimationExtra
	dw CLilyWhiteAnimationExtra
	dw LilyWhiteAnimationExtra
	dw DLilyWhiteAnimationExtra
	dw CLilyBlackAnimationExtra
	dw LilyBlackAnimationExtra
	dw SLilyBlackAnimationExtra
	dw CLyricaAnimationExtra
	dw LyricaAnimationExtra
	dw TLyricaAnimationExtra
	dw CMerlinAnimationExtra
	dw MerlinAnimationExtra
	dw SMerlinAnimationExtra
	dw CLunasaAnimationExtra
	dw LunasaAnimationExtra
	dw ALunasaAnimationExtra
	dw CYuyukoAnimationExtra
	dw YuyukoAnimationExtra
	dw AYuyukoAnimationExtra
	dw CRanAnimationExtra
	dw RanAnimationExtra
	dw TRanAnimationExtra
	dw CYukariAnimationExtra
	dw YukariAnimationExtra
	dw TYukariAnimationExtra
	dw CSuikaAnimationExtra
	dw SuikaAnimationExtra
	dw TSuikaAnimationExtra
	dw CYoumuAnimationExtra
	dw YoumuAnimationExtra
	dw SYoumuAnimationExtra
	dw CReisenAnimationExtra
	dw ReisenAnimationExtra
	dw TReisenAnimationExtra
	dw CSanaeAnimationExtra
	dw SanaeAnimationExtra
	dw DSanaeAnimationExtra
	dw CWriggleAnimationExtra
	dw WriggleAnimationExtra
	dw SWriggleAnimationExtra
	dw CMystiaAnimationExtra
	dw MystiaAnimationExtra
	dw TMystiaAnimationExtra
	dw CKeineAnimationExtra
	dw KeineAnimationExtra
	dw AKeineAnimationExtra
	dw CTeiAnimationExtra
	dw TeiAnimationExtra
	dw TTeiAnimationExtra
	dw CEirinAnimationExtra
	dw EirinAnimationExtra
	dw TEirinAnimationExtra
	dw CKaguyaAnimationExtra
	dw KaguyaAnimationExtra
	dw TKaguyaAnimationExtra
	dw CMokouAnimationExtra
	dw MokouAnimationExtra
	dw AMokouAnimationExtra
	dw BellossomAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw HoppipAnimationExtra
	dw SkiploomAnimationExtra
	dw JumpluffAnimationExtra
	dw AipomAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw YanmaAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw SlowkingAnimationExtra
	dw MisdreavusAnimationExtra
	dw UnownAAnimationExtra
	dw WobbuffetAnimationExtra
	dw GirafarigAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw QwilfishAnimationExtra
	dw ScizorAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw CorsolaAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw DelibirdAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw KingdraAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw CLunasa2AnimationExtra
	dw StantlerAnimationExtra
	dw SmeargleAnimationExtra
	dw TyrogueAnimationExtra
	dw HitmontopAnimationExtra
	dw SmoochumAnimationExtra
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw MiltankAnimationExtra
	dw BlisseyAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LugiaAnimationExtra
	dw HoOhAnimationExtra
	dw CelebiAnimationExtra
	dw AzurillAnimationExtra
	dw WynautAnimationExtra
	dw AmbipomAnimationExtra
	dw EggAnimationExtra
	dw EggAnimationExtra ; $100
	dw MismagiusAnimationExtra
	dw HonchkrowAnimationExtra
	dw BonslyAnimationExtra
	dw MimeJrAnimationExtra
	dw HappinyAnimationExtra
	dw MunchlaxAnimationExtra
	dw MantykeAnimationExtra
	dw WeavileAnimationExtra
	dw MagnezoneAnimationExtra
	dw LickilickyAnimationExtra
	dw RhyperiorAnimationExtra
	dw TangrowthAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmortarAnimationExtra
	dw TogekissAnimationExtra
	dw YanmegaAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw GliscorAnimationExtra
	dw MamoswineAnimationExtra
	dw CLunasaZAnimationExtra
	dw SylveonAnimationExtra
	dw PerrserkerAnimationExtra
	dw CursolaAnimationExtra
	dw SirfetchDAnimationExtra
	dw MrRimeAnimationExtra
	dw WyrdeerAnimationExtra
	dw KleavorAnimationExtra
	dw UrsalunaAnimationExtra
	dw SneaslerAnimationExtra
	dw OverqwilAnimationExtra
	dw DudunsparceTwoSegmentAnimationExtra
	dw FarigirafAnimationExtra
	dw ClodsireAnimationExtra
	dw AnnihilapeAnimationExtra
	assert_table_length NUM_SPECIES

	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

	dw KikuriKantoAnimationExtra
	dw KikuriKogaAnimationExtra
	dw KikuriAgathaAnimationExtra
	dw KikuriArianaAnimationExtra


	dw TTeiSpikyAnimationExtra

	dw LilyBlackSkellyAnimationExtra
	dw LilyBlackCalico1AnimationExtra
	dw LilyBlackCalico2AnimationExtra
	dw LilyBlackCalico3AnimationExtra
	dw LilyBlackTwoToneAnimationExtra
	dw LilyBlackOrcaAnimationExtra
	dw LilyBlackDapplesAnimationExtra
	dw LilyBlackTigerAnimationExtra
	dw LilyBlackZebraAnimationExtra
	dw LilyBlackStripeAnimationExtra
	dw LilyBlackBubblesAnimationExtra
	dw LilyBlackDiamondsAnimationExtra
	dw LilyBlackPatchesAnimationExtra
	dw LilyBlackForehead1AnimationExtra
	dw LilyBlackMask1AnimationExtra
	dw LilyBlackForehead2AnimationExtra
	dw LilyBlackMask2AnimationExtra
	dw LilyBlackSaucyAnimationExtra
	dw LilyBlackRaindropAnimationExtra

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw SLilyBlackRedAnimationExtra

	dw SuikaArmoredAnimationExtra

	dw DudunsparceThreeSegmentAnimationExtra

	assert_table_length NUM_UNIQUE_POKEMON
