AnimationExtraPointers:
	table_width 2, AnimationExtraPointers
	dw CReimuAnimationExtra
	dw ReimuAnimationExtra
	dw EReimuAnimationExtra
	dw CMarisaAnimationExtra
	dw MarisaAnimationExtra
	dw EMarisaAnimationExtra
	dw CSakuyaAnimationExtra
	dw SakuyaAnimationExtra
	dw ESakuyaAnimationExtra
	dw CGyokuAnimationExtra
	dw MGyokuAnimationExtra
	dw FGyokuAnimationExtra
	dw OGyokuAnimationExtra
	dw CMaganAnimationExtra
	dw MaganAnimationExtra
	dw EMaganAnimationExtra
	dw CMimaAnimationExtra
	dw MimaAnimationExtra
	dw EMimaAnimationExtra
	dw CElisPlainAnimationExtra
	dw ElisAnimationExtra
	dw EElisAnimationExtra
	dw CKikuriAnimationExtra
	dw KikuriJohtoAnimationExtra
	dw EKikuriPlainAnimationExtra
	dw CSarielPlainAnimationExtra
	dw SarielPlainAnimationExtra
	dw ESarielPlainAnimationExtra
	dw CKongaraAnimationExtra
	dw KongaraAnimationExtra
	dw EKongaraAnimationExtra
	dw CRikaAnimationExtra
	dw RikaAnimationExtra
	dw ERikaAnimationExtra
	dw CMeiraAnimationExtra
	dw MeiraAnimationExtra
	dw EMeiraPlainAnimationExtra
	dw CEllenPlainAnimationExtra
	dw EllenAnimationExtra
	dw EEllenAnimationExtra
	dw CKotohimeAnimationExtra
	dw KotohimeAnimationExtra
	dw EKotohimeAnimationExtra
	dw CKanaAnimationExtra
	dw KanaAnimationExtra
	dw EKanaAnimationExtra
	dw CRikakoAnimationExtra
	dw RikakoAnimationExtra
	dw ERikakoAnimationExtra
	dw CChiyuriPlainAnimationExtra
	dw ChiyuriPlainAnimationExtra
	dw EChiyuriPlainAnimationExtra
	dw CYumemiPlainAnimationExtra
	dw YumemiAnimationExtra
	dw EYumemiAnimationExtra
	dw COrangeAnimationExtra
	dw OrangeAnimationExtra
	dw EOrangePlainAnimationExtra
	dw CKurumiPlainAnimationExtra
	dw KurumiAnimationExtra
	dw EKurumiAnimationExtra
	dw CEllyAnimationExtra
	dw EllyAnimationExtra
	dw EEllyAnimationExtra
	dw CYukaAnimationExtra
	dw YukaAnimationExtra
	dw EYukaAnimationExtra
	dw CMugetsuAnimationExtra
	dw MugetsuAnimationExtra
	dw EMugetsuAnimationExtra
	dw CGengetsuAnimationExtra
	dw GengetsuAnimationExtra
	dw EGengetsuAnimationExtra
	dw CSaraPlainAnimationExtra
	dw SaraPlainAnimationExtra
	dw ESaraPlainAnimationExtra
	dw CLuizePlainAnimationExtra
	dw LuizePlainAnimationExtra
	dw ELuizePlainAnimationExtra
	dw CAlicePlainAnimationExtra
	dw AliceAnimationExtra
	dw EAliceAnimationExtra
	dw FarfetchDPlainAnimationExtra
	dw MaiAnimationExtra
	dw EMaiAnimationExtra
	dw CYukiAnimationExtra
	dw YukiAnimationExtra
	dw EYukiPlainAnimationExtra
	dw CYumekoPlainAnimationExtra
	dw YumekoAnimationExtra
	dw EYumekoAnimationExtra
	dw CShinkiAnimationExtra
	dw ShinkiAnimationExtra
	dw EShinkiAnimationExtra
	dw CRumiaAnimationExtra
	dw RumiaAnimationExtra
	dw ERumiaAnimationExtra
	dw CDaichanAnimationExtra
	dw DaichanAnimationExtra
	dw EDaichanPlainAnimationExtra
	dw CCirnoPlainAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorPlainAnimationExtra
	dw CuboneAnimationExtra
	dw MarowakPlainAnimationExtra
	dw HitmonleeAnimationExtra
	dw HitmonchanAnimationExtra
	dw LickitungAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingPlainAnimationExtra
	dw RhyhornAnimationExtra
	dw RhydonAnimationExtra
	dw ChanseyAnimationExtra
	dw TangelaAnimationExtra
	dw KangaskhanAnimationExtra
	dw HorseaAnimationExtra
	dw SeadraAnimationExtra
	dw GoldeenAnimationExtra
	dw SeakingAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw MrMimePlainAnimationExtra
	dw ScytherAnimationExtra
	dw JynxAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw PinsirAnimationExtra
	dw TaurosPlainAnimationExtra
	dw MagikarpPlainAnimationExtra
	dw GyaradosPlainAnimationExtra
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw PorygonAnimationExtra
	dw OmanyteAnimationExtra
	dw OmastarAnimationExtra
	dw KabutoAnimationExtra
	dw KabutopsAnimationExtra
	dw AerodactylAnimationExtra
	dw SnorlaxAnimationExtra
	dw ArticunoPlainAnimationExtra
	dw ZapdosPlainAnimationExtra
	dw MoltresPlainAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw MewtwoPlainAnimationExtra
	dw MewAnimationExtra
	dw CYoumuAnimationExtra
	dw YoumuAnimationExtra
	dw EYoumuAnimationExtra
	dw CReisenAnimationExtra
	dw ReisenAnimationExtra
	dw EReisenPlainAnimationExtra
	dw CSanaeAnimationExtra
	dw SanaeAnimationExtra
	dw ESanaeAnimationExtra
	dw SentretAnimationExtra
	dw FurretAnimationExtra
	dw HoothootAnimationExtra
	dw NoctowlAnimationExtra
	dw LedybaAnimationExtra
	dw LedianAnimationExtra
	dw SpinarakAnimationExtra
	dw AriadosAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw PichuPlainAnimationExtra
	dw CleffaAnimationExtra
	dw IgglybuffAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw BellossomAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw HoppipAnimationExtra
	dw SkiploomAnimationExtra
	dw JumpluffAnimationExtra
	dw AipomAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw YanmaAnimationExtra
	dw WooperPlainAnimationExtra
	dw QuagsireAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw SlowkingPlainAnimationExtra
	dw MisdreavusAnimationExtra
	dw UnownAAnimationExtra
	dw WobbuffetAnimationExtra
	dw GirafarigAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw QwilfishPlainAnimationExtra
	dw ScizorAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselPlainAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw CorsolaPlainAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw DelibirdAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw KingdraAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw Porygon2AnimationExtra
	dw StantlerAnimationExtra
	dw SmeargleAnimationExtra
	dw TyrogueAnimationExtra
	dw HitmontopAnimationExtra
	dw SmoochumAnimationExtra
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw MiltankAnimationExtra
	dw BlisseyAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LugiaAnimationExtra
	dw HoOhAnimationExtra
	dw CelebiAnimationExtra
	dw AzurillAnimationExtra
	dw WynautAnimationExtra
	dw AmbipomAnimationExtra
	dw EggAnimationExtra
	dw EggAnimationExtra ; $100
	dw MismagiusAnimationExtra
	dw HonchkrowAnimationExtra
	dw BonslyAnimationExtra
	dw MimeJrAnimationExtra
	dw HappinyAnimationExtra
	dw MunchlaxAnimationExtra
	dw MantykeAnimationExtra
	dw WeavileAnimationExtra
	dw MagnezoneAnimationExtra
	dw LickilickyAnimationExtra
	dw RhyperiorAnimationExtra
	dw TangrowthAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmortarAnimationExtra
	dw TogekissAnimationExtra
	dw YanmegaAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw GliscorAnimationExtra
	dw MamoswineAnimationExtra
	dw PorygonZAnimationExtra
	dw SylveonAnimationExtra
	dw PerrserkerAnimationExtra
	dw CursolaAnimationExtra
	dw SirfetchDAnimationExtra
	dw MrRimeAnimationExtra
	dw WyrdeerAnimationExtra
	dw KleavorAnimationExtra
	dw UrsalunaAnimationExtra
	dw SneaslerAnimationExtra
	dw OverqwilAnimationExtra
	dw DudunsparceTwoSegmentAnimationExtra
	dw FarigirafAnimationExtra
	dw ClodsireAnimationExtra
	dw AnnihilapeAnimationExtra
	assert_table_length NUM_SPECIES

	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

	dw KikuriKantoAnimationExtra
	dw KikuriKogaAnimationExtra
	dw KikuriAgathaAnimationExtra
	dw KikuriArianaAnimationExtra

	dw EKikuriFlyAnimationExtra
	dw EKikuriSurfAnimationExtra
	dw EKikuriPikaAnimationExtra
	dw EKikuriChuchuAnimationExtra
	dw EKikuriSparkAnimationExtra

	dw PichuSpikyAnimationExtra

	dw MagikarpSkellyAnimationExtra
	dw MagikarpCalico1AnimationExtra
	dw MagikarpCalico2AnimationExtra
	dw MagikarpCalico3AnimationExtra
	dw MagikarpTwoToneAnimationExtra
	dw MagikarpOrcaAnimationExtra
	dw MagikarpDapplesAnimationExtra
	dw MagikarpTigerAnimationExtra
	dw MagikarpZebraAnimationExtra
	dw MagikarpStripeAnimationExtra
	dw MagikarpBubblesAnimationExtra
	dw MagikarpDiamondsAnimationExtra
	dw MagikarpPatchesAnimationExtra
	dw MagikarpForehead1AnimationExtra
	dw MagikarpMask1AnimationExtra
	dw MagikarpForehead2AnimationExtra
	dw MagikarpMask2AnimationExtra
	dw MagikarpSaucyAnimationExtra
	dw MagikarpRaindropAnimationExtra

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw GyaradosRedAnimationExtra

	dw MewtwoArmoredAnimationExtra

	dw DudunsparceThreeSegmentAnimationExtra

	dw EMimaAlolanAnimationExtra
	dw CElisAlolanAnimationExtra
	dw CSarielAlolanAnimationExtra
	dw SarielAlolanAnimationExtra
	dw ESarielAlolanAnimationExtra
	dw EMeiraAlolanAnimationExtra
	dw CEllenAlolanAnimationExtra
	dw CChiyuriAlolanAnimationExtra
	dw ChiyuriAlolanAnimationExtra
	dw EChiyuriAlolanAnimationExtra
	dw CYumemiAlolanAnimationExtra
	dw CSaraAlolanAnimationExtra
	dw SaraAlolanAnimationExtra
	dw ESaraAlolanAnimationExtra
	dw EYukiAlolanAnimationExtra
	dw CYumekoAlolanAnimationExtra
	dw ExeggutorAlolanAnimationExtra
	dw MarowakAlolanAnimationExtra

	dw EChiyuriGalarianAnimationExtra
	dw CLuizeGalarianAnimationExtra
	dw LuizeGalarianAnimationExtra
	dw ELuizeGalarianAnimationExtra
	dw CAliceGalarianAnimationExtra
	dw FarfetchDGalarianAnimationExtra
	dw WeezingGalarianAnimationExtra
	dw MrMimeGalarianAnimationExtra
	dw ArticunoGalarianAnimationExtra
	dw ZapdosGalarianAnimationExtra
	dw MoltresGalarianAnimationExtra
	dw SlowkingGalarianAnimationExtra
	dw CorsolaGalarianAnimationExtra

	dw EOrangeHisuianAnimationExtra
	dw CKurumiHisuianAnimationExtra
	dw EDaichanHisuianAnimationExtra
	dw CCirnoHisuianAnimationExtra
	dw EReisenHisuianAnimationExtra
	dw QwilfishHisuianAnimationExtra
	dw SneaselHisuianAnimationExtra

	dw WooperPaldeanAnimationExtra
	dw TaurosPaldeanAnimationExtra
	dw TaurosPaldeanFireAnimationExtra
	dw TaurosPaldeanWaterAnimationExtra

	assert_table_length NUM_UNIQUE_POKEMON
