Footprints:: ; needed for BANK(Footprints)

BlankFootprint::
CYuyukoFootprint::
SpinarakFootprint::
CGyokuFootprint::
OGyokuFootprint::
LettyFootprint::
DLettyFootprint::
CLunasaZFootprint::
UmbreonFootprint::
LeafeonFootprint::
GlaceonFootprint::
ElisFootprint::
CorsolaFootprint::
CursolaFootprint:: 
KikuriFootprint::
BellossomFootprint::
ChinchouFootprint::
CrobatFootprint::
YukiFootprint::
CChiyuriFootprint::
LyricaFootprint::
TYukariFootprint::
YukariFootprint::
DudunsparceFootprint::
ChiyuriFootprint::
DunsparceFootprint::
CKikuriFootprint::
CCirnoFootprint::
CirnoFootprint::
ForretressFootprint::
CShinkiFootprint::
CSaraFootprint::
AFlandreFootprint::
SLilyBlackFootprint::
ShinkiFootprint::
CFlandreFootprint::
HChenFootprint::
CMaganFootprint::
KingdraFootprint::
HKoakumaFootprint::
LanturnFootprint::
CLyricaFootprint::
MagcargoFootprint::
LilyBlackFootprint::
MagnezoneFootprint::
MantineFootprint::
MantykeFootprint::
MGyokuFootprint::
MisdreavusFootprint::
MismagiusFootprint::
CYumekoFootprint::
CRumiaFootprint::
OverqwilFootprint::
PinecoFootprint::
PupitarFootprint::
QwilfishFootprint::
RemoraidFootprint::
FlandreFootprint::
CLettyFootprint::
CYukiFootprint::
YumekoFootprint::
SlugmaFootprint::
SteelixFootprint::
SunkernFootprint::
GengetsuFootprint::
UnownFootprint::
CGengetsuFootprint::
DDaichanFootprint::
CPatchouliFootprint::
CKotohimeFootprint::
CReimuFootprint::
ReimuFootprint::
TReimuFootprint::
CMarisaFootprint::
MarisaFootprint::
AMarisaFootprint::
CSakuyaFootprint::
SakuyaFootprint::
HSakuyaFootprint::
FGyokuFootprint:: 
MaganFootprint::
CMimaFootprint:: 
MimaFootprint::

CElisFootprint::
CSarielFootprint::
SarielFootprint::
CKongaraFootprint::
KongaraFootprint::
CRikaFootprint::
RikaFootprint::
ARikaFootprint::
CMeiraFootprint:: 
MeiraFootprint:: 
CEllenFootprint:: 
EllenFootprint:: 
KotohimeFootprint:: 
CKanaFootprint:: 
KanaFootprint:: 
CRikakoFootprint:: 
RikakoFootprint:: 
CYumemiFootprint:: 
YumemiFootprint:: 
COrangeFootprint:: 
OrangeFootprint:: 
CKurumiFootprint:: 
KurumiFootprint:: 
CEllyFootprint:: 
EllyFootprint:: 
CYukaFootprint:: 
YukaFootprint:: 
AYukaFootprint:: 
CMugetsuFootprint:: 
MugetsuFootprint:: 
SaraFootprint:: 
CLuizeFootprint:: 
LuizeFootprint:: 
DLuizeFootprint:: 
CAliceFootprint:: 
AliceFootprint:: 
AAliceFootprint:: 
CMaiFootprint:: 
MaiFootprint::  
RumiaFootprint:: 
ARumiaFootprint:: 
CDaichanFootprint:: 
DaichanFootprint:: 
SCirnoFootprint:: 
CMeilingFootprint:: 
MeilingFootprint:: 
AMeilingFootprint:: 
CKoakumaFootprint:: 
KoakumaFootprint:: 
PatchouliFootprint:: 
TPatchouliFootprint:: 
CRemiliaFootprint:: 
RemiliaFootprint:: 
SRemiliaFootprint:: 
CChenFootprint:: 
ChenFootprint:: 
CLilyWhiteFootprint:: 
LilyWhiteFootprint:: 
DLilyWhiteFootprint:: 
CLilyBlackFootprint:: 
TLyricaFootprint:: 
CMerlinFootprint:: 
MerlinFootprint:: 
SMerlinFootprint:: 
CLunasaFootprint:: 
LunasaFootprint:: 
ALunasaFootprint:: 
YuyukoFootprint:: 
AYuyukoFootprint:: 
CRanFootprint:: 
RanFootprint:: 
TRanFootprint:: 
CYukariFootprint:: 
CSuikaFootprint:: 
SuikaFootprint:: 
TSuikaFootprint:: 
CYoumuFootprint::
YoumuFootprint:: 
SYoumuFootprint:: 
CReisenFootprint:: 
ReisenFootprint:: 
TReisenFootprint:: 
CSanaeFootprint:: 
SanaeFootprint:: 
DSanaeFootprint:: 
SentretFootprint:: 
FurretFootprint:: 
HoothootFootprint:: 
NoctowlFootprint:: 
LedybaFootprint:: 
LedianFootprint:: 
AriadosFootprint:: 
PichuFootprint:: 
CleffaFootprint:: 
IgglybuffFootprint:: 
TogepiFootprint:: 
TogeticFootprint:: 
NatuFootprint:: 
XatuFootprint:: 
MareepFootprint:: 
FlaaffyFootprint:: 
AmpharosFootprint:: 
MarillFootprint:: 
AzumarillFootprint::
SudowoodoFootprint::
PolitoedFootprint::
HoppipFootprint:: 
SkiploomFootprint::
JumpluffFootprint::
AipomFootprint::
SunfloraFootprint::
YanmaFootprint::
WooperFootprint::
QuagsireFootprint::
EspeonFootprint::
MurkrowFootprint::
SlowkingFootprint::
WobbuffetFootprint:: 
GirafarigFootprint::
GligarFootprint::
SnubbullFootprint::
GranbullFootprint::
ScizorFootprint::
ShuckleFootprint:: 
HeracrossFootprint::
SneaselFootprint::
TeddiursaFootprint::
UrsaringFootprint::
SwinubFootprint::
PiloswineFootprint::
OctilleryFootprint::
DelibirdFootprint:: 
SkarmoryFootprint::
HoundourFootprint::
HoundoomFootprint::
PhanpyFootprint::
DonphanFootprint::
CLunasa2Footprint:: 
StantlerFootprint::
SmeargleFootprint:: 
TyrogueFootprint:: 
HitmontopFootprint:: 
SmoochumFootprint:: 
ElekidFootprint::
MagbyFootprint:: 
MiltankFootprint::
BlisseyFootprint::
RaikouFootprint::
EnteiFootprint::
SuicuneFootprint::
LarvitarFootprint::
TyranitarFootprint::
LugiaFootprint:: 
HoOhFootprint:: 
CelebiFootprint::
AzurillFootprint::
WynautFootprint::
AmbipomFootprint::
EggFootprint::
HonchkrowFootprint::
BonslyFootprint:: 
MimeJrFootprint::
HappinyFootprint::
MunchlaxFootprint::
WeavileFootprint::
LickilickyFootprint::
RhyperiorFootprint::
TangrowthFootprint:: 
ElectivireFootprint::
MagmortarFootprint::
TogekissFootprint::
YanmegaFootprint::
GliscorFootprint::
MamoswineFootprint::
SylveonFootprint::
PerrserkerFootprint::
SirfetchDFootprint::
MrRimeFootprint::
WyrdeerFootprint::
KleavorFootprint::
UrsalunaFootprint::
SneaslerFootprint:: 
FarigirafFootprint::
ClodsireFootprint:: 
AnnihilapeFootprint:: INCBIN "gfx/footprints/blank.1bpp.lz"
