Footprints:: ; needed for BANK(Footprints)

BlankFootprint::
ERikakoFootprint::
KabutoFootprint::
SpinarakFootprint::
CGyokuFootprint::
OGyokuFootprint::
StaryuFootprint::
StarmieFootprint::
PorygonZFootprint::
UmbreonFootprint::
LeafeonFootprint::
GlaceonFootprint::
EMaganFootprint::
ElisFootprint::
CorsolaFootprint::
CursolaFootprint:: 
KikuriFootprint::
BellossomFootprint::
ChinchouFootprint::
EYumekoFootprint::
CrobatFootprint::
YukiFootprint::
CChiyuriFootprint::
DittoFootprint::
DragonairFootprint::
DratiniFootprint::
DudunsparceFootprint::
ChiyuriFootprint::
DunsparceFootprint::
CKikuriFootprint::
CCirnoFootprint::
CirnoFootprint::
ForretressFootprint::
CShinkiFootprint::
CSaraFootprint::
EFlandreFootprint::
EYukiFootprint::
GyaradosFootprint::
ShinkiFootprint::
CFlandreFootprint::
JynxFootprint::
CMaganFootprint::
KingdraFootprint::
EKoakumaFootprint::
LanturnFootprint::
LaprasFootprint::
MagcargoFootprint::
MagikarpFootprint::
MagnezoneFootprint::
MantineFootprint::
MantykeFootprint::
MGyokuFootprint::
MisdreavusFootprint::
MismagiusFootprint::
CYumekoFootprint::
CRumiaFootprint::
OverqwilFootprint::
PinecoFootprint::
PupitarFootprint::
QwilfishFootprint::
RemoraidFootprint::
FlandreFootprint::
SeakingFootprint::
CYukiFootprint::
YumekoFootprint::
SlugmaFootprint::
SteelixFootprint::
SunkernFootprint::
GengetsuFootprint::
EGengetsuFootprint::
UnownFootprint::
CGengetsuFootprint::
EDaichanFootprint::
EMugetsuFootprint::
CPatchouliFootprint::
CKotohimeFootprint::
CReimuFootprint::
ReimuFootprint::
EReimuFootprint::
CMarisaFootprint::
MarisaFootprint::
EMarisaFootprint::
CSakuyaFootprint::
SakuyaFootprint::
ESakuyaFootprint::
FGyokuFootprint:: 
MaganFootprint::
CMimaFootprint:: 
MimaFootprint::
EMimaFootprint::
CElisFootprint::
EElisFootprint::
EKikuriFootprint::
CSarielFootprint::
SarielFootprint::
ESarielFootprint::
CKongaraFootprint::
KongaraFootprint::
EKongaraFootprint::
CRikaFootprint::
RikaFootprint::
ERikaFootprint::
CMeiraFootprint:: 
MeiraFootprint:: 
EMeiraFootprint:: 
CEllenFootprint:: 
EllenFootprint:: 
EEllenFootprint:: 
KotohimeFootprint:: 
EKotohimeFootprint:: 
CKanaFootprint:: 
KanaFootprint:: 
EKanaFootprint:: 
CRikakoFootprint:: 
RikakoFootprint:: 
EChiyuriFootprint:: 
CYumemiFootprint:: 
YumemiFootprint:: 
EYumemiFootprint:: 
COrangeFootprint:: 
OrangeFootprint:: 
EOrangeFootprint:: 
CKurumiFootprint:: 
KurumiFootprint:: 
EKurumiFootprint:: 
CEllyFootprint:: 
EllyFootprint:: 
EEllyFootprint:: 
CYukaFootprint:: 
YukaFootprint:: 
EYukaFootprint:: 
CMugetsuFootprint:: 
MugetsuFootprint:: 
SaraFootprint:: 
ESaraFootprint:: 
CLuizeFootprint:: 
LuizeFootprint:: 
ELuizeFootprint:: 
CAliceFootprint:: 
AliceFootprint:: 
EAliceFootprint:: 
CMaiFootprint:: 
MaiFootprint:: 
EMaiFootprint:: 
EShinkiFootprint:: 
RumiaFootprint:: 
ERumiaFootprint:: 
CDaichanFootprint:: 
DaichanFootprint:: 
ECirnoFootprint:: 
CMeilingFootprint:: 
MeilingFootprint:: 
EMeilingFootprint:: 
CKoakumaFootprint:: 
KoakumaFootprint:: 
PatchouliFootprint:: 
EPatchouliFootprint:: 
CRemiliaFootprint:: 
RemiliaFootprint:: 
ERemiliaFootprint:: 
MrMimeFootprint:: 
ScytherFootprint:: 
ElectabuzzFootprint:: 
MagmarFootprint:: 
PinsirFootprint:: 
TaurosFootprint:: 
EeveeFootprint:: 
VaporeonFootprint:: 
JolteonFootprint:: 
FlareonFootprint:: 
PorygonFootprint:: 
OmanyteFootprint:: 
OmastarFootprint:: 
KabutopsFootprint:: 
AerodactylFootprint:: 
SnorlaxFootprint:: 
ArticunoFootprint:: 
ZapdosFootprint:: 
MoltresFootprint:: 
DragoniteFootprint:: 
MewtwoFootprint:: 
MewFootprint:: 
CYoumuFootprint::
YoumuFootprint:: 
EYoumuFootprint:: 
CReisenFootprint:: 
ReisenFootprint:: 
EReisenFootprint:: 
CSanaeFootprint:: 
SanaeFootprint:: 
ESanaeFootprint:: 
SentretFootprint:: 
FurretFootprint:: 
HoothootFootprint:: 
NoctowlFootprint:: 
LedybaFootprint:: 
LedianFootprint:: 
AriadosFootprint:: 
PichuFootprint:: 
CleffaFootprint:: 
IgglybuffFootprint:: 
TogepiFootprint:: 
TogeticFootprint:: 
NatuFootprint:: 
XatuFootprint:: 
MareepFootprint:: 
FlaaffyFootprint:: 
AmpharosFootprint:: 
MarillFootprint:: 
AzumarillFootprint::
SudowoodoFootprint::
PolitoedFootprint::
HoppipFootprint:: 
SkiploomFootprint::
JumpluffFootprint::
AipomFootprint::
SunfloraFootprint::
YanmaFootprint::
WooperFootprint::
QuagsireFootprint::
EspeonFootprint::
MurkrowFootprint::
SlowkingFootprint::
WobbuffetFootprint:: 
GirafarigFootprint::
GligarFootprint::
SnubbullFootprint::
GranbullFootprint::
ScizorFootprint::
ShuckleFootprint:: 
HeracrossFootprint::
SneaselFootprint::
TeddiursaFootprint::
UrsaringFootprint::
SwinubFootprint::
PiloswineFootprint::
OctilleryFootprint::
DelibirdFootprint:: 
SkarmoryFootprint::
HoundourFootprint::
HoundoomFootprint::
PhanpyFootprint::
DonphanFootprint::
Porygon2Footprint:: 
StantlerFootprint::
SmeargleFootprint:: 
TyrogueFootprint:: 
HitmontopFootprint:: 
SmoochumFootprint:: 
ElekidFootprint::
MagbyFootprint:: 
MiltankFootprint::
BlisseyFootprint::
RaikouFootprint::
EnteiFootprint::
SuicuneFootprint::
LarvitarFootprint::
TyranitarFootprint::
LugiaFootprint:: 
HoOhFootprint:: 
CelebiFootprint::
AzurillFootprint::
WynautFootprint::
AmbipomFootprint::
EggFootprint::
HonchkrowFootprint::
BonslyFootprint:: 
MimeJrFootprint::
HappinyFootprint::
MunchlaxFootprint::
WeavileFootprint::
LickilickyFootprint::
RhyperiorFootprint::
TangrowthFootprint:: 
ElectivireFootprint::
MagmortarFootprint::
TogekissFootprint::
YanmegaFootprint::
GliscorFootprint::
MamoswineFootprint::
SylveonFootprint::
PerrserkerFootprint::
SirfetchDFootprint::
MrRimeFootprint::
WyrdeerFootprint::
KleavorFootprint::
UrsalunaFootprint::
SneaslerFootprint:: 
FarigirafFootprint::
ClodsireFootprint:: 
AnnihilapeFootprint:: INCBIN "gfx/footprints/blank.1bpp.lz"
