FramesPointers:
	table_width 2, FramesPointers
	dw CReimuFrames
	dw ReimuFrames
	dw TReimuFrames
	dw CMarisaFrames
	dw MarisaFrames
	dw AMarisaFrames
	dw CSakuyaFrames
	dw SakuyaFrames
	dw HSakuyaFrames
	dw CGyokuFrames
	dw MGyokuFrames
	dw FGyokuFrames
	dw OGyokuFrames
	dw CMaganFrames
	dw MaganFrames
	dw CMimaFrames
	dw MimaFrames
	dw CElisFrames
	dw ElisFrames
	dw CKikuriFrames
	dw KikuriJohtoFrames
	dw CSarielFrames
	dw SarielFrames
	dw CKongaraFrames
	dw KongaraFrames
	dw CRikaFrames
	dw RikaFrames
	dw ARikaFrames
	dw CMeiraFrames
	dw MeiraFrames
	dw CEllenFrames
	dw EllenFrames
	dw CKotohimeFrames
	dw KotohimeFrames
	dw CKanaFrames
	dw KanaFrames
	dw CRikakoFrames
	dw RikakoFrames
	dw CChiyuriFrames
	dw ChiyuriFrames
	dw CYumemiFrames
	dw YumemiFrames
	dw COrangeFrames
	dw OrangeFrames
	dw CKurumiFrames
	dw KurumiFrames
	dw CEllyFrames
	dw EllyFrames
	dw CYukaFrames
	dw YukaFrames
	dw AYukaFrames
	dw CMugetsuFrames
	dw MugetsuFrames
	dw CGengetsuFrames
	dw GengetsuFrames
	dw CSaraFrames
	dw SaraFrames
	dw CLuizeFrames
	dw LuizeFrames
	dw DLuizeFrames
	dw CAliceFrames
	dw AliceFrames
	dw AAliceFrames
	dw CMaiFrames
	dw MaiFrames
	dw CYukiFrames
	dw YukiFrames
	dw CYumekoFrames
	dw YumekoFrames
	dw CShinkiFrames
	dw ShinkiFrames
	dw CRumiaFrames
	dw RumiaFrames
	dw ARumiaFrames
	dw CDaichanFrames
	dw DaichanFrames
	dw DDaichanFrames
	dw CCirnoFrames
	dw CirnoFrames
	dw SCirnoFrames
	dw CMeilingFrames
	dw MeilingFrames
	dw AMeilingFrames
	dw CKoakumaFrames
	dw KoakumaFrames
	dw HKoakumaFrames
	dw CPatchouliFrames
	dw PatchouliFrames
	dw TPatchouliFrames
	dw CRemiliaFrames
	dw RemiliaFrames
	dw SRemiliaFrames
	dw CFlandreFrames
	dw FlandreFrames
	dw AFlandreFrames
	dw CLettyFrames
	dw LettyFrames
	dw DLettyFrames
	dw MrMimeFrames
	dw ChenFrames
	dw HChenFrames
	dw CLilyWhiteFrames
	dw LilyWhiteFrames
	dw ELilyWhiteFrames
	dw CLilyBlackFrames
	dw LilyBlackFrames
	dw ELilyBlackFrames
	dw CLyricaFrames
	dw LyricaFrames
	dw TLyricaFrames
	dw CMerlinFrames
	dw MerlinFrames
	dw SMerlinFrames
	dw CLunasaFrames
	dw LunasaFrames
	dw ALunasaFrames
	dw CYuyukoFrames
	dw YuyukoFrames
	dw AYuyukoFrames
	dw CRanFrames
	dw RanFrames
	dw TRanFrames
	dw CYukariFrames
	dw YukariFrames
	dw TYukariFrames
	dw CSuikaFrames
	dw SuikaFrames
	dw TSuikaFrames
	dw CYoumuFrames
	dw YoumuFrames
	dw SYoumuFrames
	dw CReisenFrames
	dw ReisenFrames
	dw TReisenFrames
	dw CSanaeFrames
	dw SanaeFrames
	dw DSanaeFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw MisdreavusFrames
	dw UnownAFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw CLunasa2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw AzurillFrames
	dw WynautFrames
	dw AmbipomFrames
	dw EggFrames
	dw EggFrames ; $100
	dw MismagiusFrames
	dw HonchkrowFrames
	dw BonslyFrames
	dw MimeJrFrames
	dw HappinyFrames
	dw MunchlaxFrames
	dw MantykeFrames
	dw WeavileFrames
	dw MagnezoneFrames
	dw LickilickyFrames
	dw RhyperiorFrames
	dw TangrowthFrames
	dw ElectivireFrames
	dw MagmortarFrames
	dw TogekissFrames
	dw YanmegaFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw GliscorFrames
	dw MamoswineFrames
	dw CLunasaZFrames
	dw SylveonFrames
	dw PerrserkerFrames
	dw CursolaFrames
	dw SirfetchDFrames
	dw MrRimeFrames
	dw WyrdeerFrames
	dw KleavorFrames
	dw UrsalunaFrames
	dw SneaslerFrames
	dw OverqwilFrames
	dw DudunsparceTwoSegmentFrames
	dw FarigirafFrames
	dw ClodsireFrames
	dw AnnihilapeFrames
	assert_table_length NUM_SPECIES

	dw UnownBFrames
	dw UnownCFrames
	dw UnownDFrames
	dw UnownEFrames
	dw UnownFFrames
	dw UnownGFrames
	dw UnownHFrames
	dw UnownIFrames
	dw UnownJFrames
	dw UnownKFrames
	dw UnownLFrames
	dw UnownMFrames
	dw UnownNFrames
	dw UnownOFrames
	dw UnownPFrames
	dw UnownQFrames
	dw UnownRFrames
	dw UnownSFrames
	dw UnownTFrames
	dw UnownUFrames
	dw UnownVFrames
	dw UnownWFrames
	dw UnownXFrames
	dw UnownYFrames
	dw UnownZFrames
	dw UnownExclamationFrames
	dw UnownQuestionFrames

	dw KikuriKantoFrames
	dw KikuriKogaFrames
	dw KikuriAgathaFrames
	dw KikuriArianaFrames



	dw PichuSpikyFrames

	dw LilyBlackSkellyFrames
	dw LilyBlackCalico1Frames
	dw LilyBlackCalico2Frames
	dw LilyBlackCalico3Frames
	dw LilyBlackTwoToneFrames
	dw LilyBlackOrcaFrames
	dw LilyBlackDapplesFrames
	dw LilyBlackTigerFrames
	dw LilyBlackZebraFrames
	dw LilyBlackStripeFrames
	dw LilyBlackBubblesFrames
	dw LilyBlackDiamondsFrames
	dw LilyBlackPatchesFrames
	dw LilyBlackForehead1Frames
	dw LilyBlackMask1Frames
	dw LilyBlackForehead2Frames
	dw LilyBlackMask2Frames
	dw LilyBlackSaucyFrames
	dw LilyBlackRaindropFrames

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw ELilyBlackRedFrames

	dw SuikaArmoredFrames

	dw DudunsparceThreeSegmentFrames

	assert_table_length NUM_UNIQUE_POKEMON
