FramesPointers:
	table_width 2, FramesPointers
	dw CReimuFrames
	dw ReimuFrames
	dw EReimuFrames
	dw CMarisaFrames
	dw MarisaFrames
	dw EMarisaFrames
	dw CSakuyaFrames
	dw SakuyaFrames
	dw ESakuyaFrames
	dw CGyokuFrames
	dw MGyokuFrames
	dw FGyokuFrames
	dw OGyokuFrames
	dw CMaganFrames
	dw MaganFrames
	dw EMaganFrames
	dw CMimaFrames
	dw MimaFrames
	dw EMimaFrames
	dw CElisPlainFrames
	dw ElisFrames
	dw EElisFrames
	dw CKikuriFrames
	dw KikuriJohtoFrames
	dw EKikuriPlainFrames
	dw CSarielPlainFrames
	dw SarielPlainFrames
	dw ESarielPlainFrames
	dw CKongaraFrames
	dw KongaraFrames
	dw EKongaraFrames
	dw CRikaFrames
	dw RikaFrames
	dw ERikaFrames
	dw CMeiraFrames
	dw MeiraFrames
	dw EMeiraPlainFrames
	dw CEllenPlainFrames
	dw EllenFrames
	dw EEllenFrames
	dw CKotohimeFrames
	dw KotohimeFrames
	dw EKotohimeFrames
	dw CKanaFrames
	dw KanaFrames
	dw EKanaFrames
	dw CRikakoFrames
	dw RikakoFrames
	dw ERikakoFrames
	dw CChiyuriPlainFrames
	dw ChiyuriPlainFrames
	dw EChiyuriPlainFrames
	dw CYumemiPlainFrames
	dw YumemiFrames
	dw EYumemiFrames
	dw COrangeFrames
	dw OrangeFrames
	dw EOrangePlainFrames
	dw CKurumiPlainFrames
	dw KurumiFrames
	dw EKurumiFrames
	dw CEllyFrames
	dw EllyFrames
	dw EEllyFrames
	dw CYukaFrames
	dw YukaFrames
	dw EYukaFrames
	dw CMugetsuFrames
	dw MugetsuFrames
	dw EMugetsuFrames
	dw CGengetsuFrames
	dw GengetsuFrames
	dw EGengetsuFrames
	dw CSaraPlainFrames
	dw SaraPlainFrames
	dw ESaraPlainFrames
	dw CLuizePlainFrames
	dw LuizePlainFrames
	dw ELuizePlainFrames
	dw CAlicePlainFrames
	dw AliceFrames
	dw EAliceFrames
	dw CMaiPlainFrames
	dw MaiFrames
	dw EMaiFrames
	dw CYukiFrames
	dw YukiFrames
	dw EYukiPlainFrames
	dw CYumekoPlainFrames
	dw YumekoFrames
	dw EYumekoFrames
	dw CShinkiFrames
	dw ShinkiFrames
	dw EShinkiFrames
	dw CRumiaFrames
	dw RumiaFrames
	dw ERumiaFrames
	dw CDaichanFrames
	dw DaichanFrames
	dw EDaichanPlainFrames
	dw CCirnoPlainFrames
	dw CirnoFrames
	dw ECirnoPlainFrames
	dw CMeilingFrames
	dw MeilingPlainFrames
	dw EMeilingFrames
	dw CKoakumaFrames
	dw KoakumaFrames
	dw EKoakumaFrames
	dw CPatchouliPlainFrames
	dw PatchouliFrames
	dw EPatchouliFrames
	dw CRemiliaFrames
	dw RemiliaFrames
	dw ERemiliaFrames
	dw CFlandreFrames
	dw FlandreFrames
	dw EFlandreFrames
	dw CLettyFrames
	dw LettyFrames
	dw ELettyFrames
	dw MrMimePlainFrames
	dw ChenFrames
	dw EChenFrames
	dw CLilyWhiteFrames
	dw LilyWhiteFrames
	dw ELilyWhiteFrames
	dw CLilyBlackPlainFrames
	dw LilyBlackPlainFrames
	dw ELilyBlackPlainFrames
	dw CLyricaFrames
	dw LyricaFrames
	dw ELyricaFrames
	dw CMerlinFrames
	dw MerlinFrames
	dw EMerlinFrames
	dw CLunasaFrames
	dw LunasaFrames
	dw ELunasaFrames
	dw CYuyukoFrames
	dw YuyukoFrames
	dw EYuyukoFrames
	dw CRanFrames
	dw RanPlainFrames
	dw ERanPlainFrames
	dw CYukariPlainFrames
	dw YukariFrames
	dw EYukariFrames
	dw CSuikaFrames
	dw SuikaPlainFrames
	dw ESuikaFrames
	dw CYoumuFrames
	dw YoumuFrames
	dw EYoumuFrames
	dw CReisenFrames
	dw ReisenFrames
	dw EReisenPlainFrames
	dw CSanaeFrames
	dw SanaeFrames
	dw ESanaeFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuPlainFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperPlainFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingPlainFrames
	dw MisdreavusFrames
	dw UnownAFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishPlainFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselPlainFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaPlainFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw CLunasa2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw AzurillFrames
	dw WynautFrames
	dw AmbipomFrames
	dw EggFrames
	dw EggFrames ; $100
	dw MismagiusFrames
	dw HonchkrowFrames
	dw BonslyFrames
	dw MimeJrFrames
	dw HappinyFrames
	dw MunchlaxFrames
	dw MantykeFrames
	dw WeavileFrames
	dw MagnezoneFrames
	dw LickilickyFrames
	dw RhyperiorFrames
	dw TangrowthFrames
	dw ElectivireFrames
	dw MagmortarFrames
	dw TogekissFrames
	dw YanmegaFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw GliscorFrames
	dw MamoswineFrames
	dw CLunasaZFrames
	dw SylveonFrames
	dw PerrserkerFrames
	dw CursolaFrames
	dw SirfetchDFrames
	dw MrRimeFrames
	dw WyrdeerFrames
	dw KleavorFrames
	dw UrsalunaFrames
	dw SneaslerFrames
	dw OverqwilFrames
	dw DudunsparceTwoSegmentFrames
	dw FarigirafFrames
	dw ClodsireFrames
	dw AnnihilapeFrames
	assert_table_length NUM_SPECIES

	dw UnownBFrames
	dw UnownCFrames
	dw UnownDFrames
	dw UnownEFrames
	dw UnownFFrames
	dw UnownGFrames
	dw UnownHFrames
	dw UnownIFrames
	dw UnownJFrames
	dw UnownKFrames
	dw UnownLFrames
	dw UnownMFrames
	dw UnownNFrames
	dw UnownOFrames
	dw UnownPFrames
	dw UnownQFrames
	dw UnownRFrames
	dw UnownSFrames
	dw UnownTFrames
	dw UnownUFrames
	dw UnownVFrames
	dw UnownWFrames
	dw UnownXFrames
	dw UnownYFrames
	dw UnownZFrames
	dw UnownExclamationFrames
	dw UnownQuestionFrames

	dw KikuriKantoFrames
	dw KikuriKogaFrames
	dw KikuriAgathaFrames
	dw KikuriArianaFrames

	dw EKikuriFlyFrames
	dw EKikuriSurfFrames
	dw EKikuriPikaFrames
	dw EKikuriChuchuFrames
	dw EKikuriSparkFrames

	dw PichuSpikyFrames

	dw LilyBlackSkellyFrames
	dw LilyBlackCalico1Frames
	dw LilyBlackCalico2Frames
	dw LilyBlackCalico3Frames
	dw LilyBlackTwoToneFrames
	dw LilyBlackOrcaFrames
	dw LilyBlackDapplesFrames
	dw LilyBlackTigerFrames
	dw LilyBlackZebraFrames
	dw LilyBlackStripeFrames
	dw LilyBlackBubblesFrames
	dw LilyBlackDiamondsFrames
	dw LilyBlackPatchesFrames
	dw LilyBlackForehead1Frames
	dw LilyBlackMask1Frames
	dw LilyBlackForehead2Frames
	dw LilyBlackMask2Frames
	dw LilyBlackSaucyFrames
	dw LilyBlackRaindropFrames

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw ELilyBlackRedFrames

	dw SuikaArmoredFrames

	dw DudunsparceThreeSegmentFrames

	dw EMimaAlolanFrames
	dw CElisAlolanFrames
	dw CSarielAlolanFrames
	dw SarielAlolanFrames
	dw ESarielAlolanFrames
	dw EMeiraAlolanFrames
	dw CEllenAlolanFrames
	dw CChiyuriAlolanFrames
	dw ChiyuriAlolanFrames
	dw EChiyuriAlolanFrames
	dw CYumemiAlolanFrames
	dw CSaraAlolanFrames
	dw SaraAlolanFrames
	dw ESaraAlolanFrames
	dw EYukiAlolanFrames
	dw CYumekoAlolanFrames
	dw ECirnoAlolanFrames
	dw MeilingAlolanFrames

	dw EChiyuriGalarianFrames
	dw CLuizeGalarianFrames
	dw LuizeGalarianFrames
	dw ELuizeGalarianFrames
	dw CAliceGalarianFrames
	dw CMaiGalarianFrames
	dw CPatchouliGalarianFrames
	dw MrMimeGalarianFrames
	dw RanGalarianFrames
	dw ERanGalarianFrames
	dw CYukariGalarianFrames
	dw SlowkingGalarianFrames
	dw CorsolaGalarianFrames

	dw EOrangeHisuianFrames
	dw CKurumiHisuianFrames
	dw EDaichanHisuianFrames
	dw CCirnoHisuianFrames
	dw EReisenHisuianFrames
	dw QwilfishHisuianFrames
	dw SneaselHisuianFrames

	dw WooperPaldeanFrames
	dw CLilyBlackPaldeanFrames
	dw CLilyBlackPaldeanFireFrames
	dw CLilyBlackPaldeanWaterFrames

	assert_table_length NUM_UNIQUE_POKEMON
