KantoFrames:

CReimuFrames:  INCLUDE "gfx/pokemon/creimu/frames.asm"
ReimuFrames:    INCLUDE "gfx/pokemon/reimu/frames.asm"
TReimuFrames:   INCLUDE "gfx/pokemon/treimu/frames.asm"
CMarisaFrames: INCLUDE "gfx/pokemon/cmarisa/frames.asm"
MarisaFrames: INCLUDE "gfx/pokemon/marisa/frames.asm"
AMarisaFrames:  INCLUDE "gfx/pokemon/amarisa/frames.asm"
CSakuyaFrames:   INCLUDE "gfx/pokemon/csakuya/frames.asm"
SakuyaFrames:  INCLUDE "gfx/pokemon/sakuya/frames.asm"
HSakuyaFrames:  INCLUDE "gfx/pokemon/hsakuya/frames.asm"
CGyokuFrames:   INCLUDE "gfx/pokemon/cgyoku/frames.asm"
MGyokuFrames:    INCLUDE "gfx/pokemon/mgyoku/frames.asm"
FGyokuFrames: INCLUDE "gfx/pokemon/fgyoku/frames.asm"
OGyokuFrames:     INCLUDE "gfx/pokemon/ogyoku/frames.asm"
CMaganFrames:     INCLUDE "gfx/pokemon/cmagan/frames.asm"
MaganFrames:   INCLUDE "gfx/pokemon/magan/frames.asm"
CMimaFrames:  INCLUDE "gfx/pokemon/cmima/frames.asm"
MimaFrames:    INCLUDE "gfx/pokemon/mima/frames.asm"
ElisFrames:    INCLUDE "gfx/pokemon/elis/frames.asm"
CKikuriFrames:      INCLUDE "gfx/pokemon/ckikuri/frames.asm"
CKongaraFrames:   INCLUDE "gfx/pokemon/ckongara/frames.asm"
KongaraFrames:   INCLUDE "gfx/pokemon/kongara/frames.asm"
CRikaFrames:   INCLUDE "gfx/pokemon/crika/frames.asm"
RikaFrames:   INCLUDE "gfx/pokemon/rika/frames.asm"
ARikaFrames:   INCLUDE "gfx/pokemon/arika/frames.asm"
CMeiraFrames:   INCLUDE "gfx/pokemon/cmeira/frames.asm"
MeiraFrames:   INCLUDE "gfx/pokemon/meira/frames.asm"
EllenFrames: INCLUDE "gfx/pokemon/ellen/frames.asm"
CKotohimeFrames:      INCLUDE "gfx/pokemon/ckotohime/frames.asm"
KotohimeFrames:     INCLUDE "gfx/pokemon/kotohime/frames.asm"
CKanaFrames:      INCLUDE "gfx/pokemon/ckana/frames.asm"
KanaFrames:  INCLUDE "gfx/pokemon/kana/frames.asm"
CRikakoFrames:   INCLUDE "gfx/pokemon/crikako/frames.asm"
RikakoFrames:    INCLUDE "gfx/pokemon/rikako/frames.asm"
YumemiFrames:    INCLUDE "gfx/pokemon/yumemi/frames.asm"
COrangeFrames:     INCLUDE "gfx/pokemon/corange/frames.asm"
OrangeFrames:   INCLUDE "gfx/pokemon/orange/frames.asm"
KurumiFrames:    INCLUDE "gfx/pokemon/kurumi/frames.asm"
CEllyFrames:  INCLUDE "gfx/pokemon/celly/frames.asm"
EllyFrames:       INCLUDE "gfx/pokemon/elly/frames.asm"
CYukaFrames:   INCLUDE "gfx/pokemon/cyuka/frames.asm"
YukaFrames:     INCLUDE "gfx/pokemon/yuka/frames.asm"
AYukaFrames:    INCLUDE "gfx/pokemon/ayuka/frames.asm"
CMugetsuFrames:    INCLUDE "gfx/pokemon/cmugetsu/frames.asm"
MugetsuFrames: INCLUDE "gfx/pokemon/mugetsu/frames.asm"
CGengetsuFrames: INCLUDE "gfx/pokemon/cgengetsu/frames.asm"
GengetsuFrames:  INCLUDE "gfx/pokemon/gengetsu/frames.asm"
AliceFrames:  INCLUDE "gfx/pokemon/alice/frames.asm"
AAliceFrames:   INCLUDE "gfx/pokemon/aalice/frames.asm"
MaiFrames:      INCLUDE "gfx/pokemon/mai/frames.asm"
CYukiFrames:       INCLUDE "gfx/pokemon/cyuki/frames.asm"
YukiFrames:    INCLUDE "gfx/pokemon/yuki/frames.asm"
YumekoFrames:   INCLUDE "gfx/pokemon/yumeko/frames.asm"
CShinkiFrames:     INCLUDE "gfx/pokemon/cshinki/frames.asm"
ShinkiFrames:    INCLUDE "gfx/pokemon/shinki/frames.asm"
CRumiaFrames:       INCLUDE "gfx/pokemon/crumia/frames.asm"
RumiaFrames:    INCLUDE "gfx/pokemon/rumia/frames.asm"
ARumiaFrames:      INCLUDE "gfx/pokemon/arumia/frames.asm"
CDaichanFrames:     INCLUDE "gfx/pokemon/cdaichan/frames.asm"
DaichanFrames:    INCLUDE "gfx/pokemon/daichan/frames.asm"
CirnoFrames:  INCLUDE "gfx/pokemon/cirno/frames.asm"
CMeilingFrames:     INCLUDE "gfx/pokemon/cmeiling/frames.asm"
AMeilingFrames:  INCLUDE "gfx/pokemon/ameiling/frames.asm"
CKoakumaFrames: INCLUDE "gfx/pokemon/ckoakuma/frames.asm"
KoakumaFrames:  INCLUDE "gfx/pokemon/koakuma/frames.asm"
HKoakumaFrames:    INCLUDE "gfx/pokemon/hkoakuma/frames.asm"
PatchouliFrames:    INCLUDE "gfx/pokemon/patchouli/frames.asm"
TPatchouliFrames:     INCLUDE "gfx/pokemon/tpatchouli/frames.asm"
CRemiliaFrames:    INCLUDE "gfx/pokemon/cremilia/frames.asm"
RemiliaFrames:    INCLUDE "gfx/pokemon/remilia/frames.asm"
SRemiliaFrames: INCLUDE "gfx/pokemon/sremilia/frames.asm"
CFlandreFrames:     INCLUDE "gfx/pokemon/cflandre/frames.asm"
FlandreFrames:     INCLUDE "gfx/pokemon/flandre/frames.asm"
AFlandreFrames:    INCLUDE "gfx/pokemon/aflandre/frames.asm"
CLettyFrames:    INCLUDE "gfx/pokemon/seaking/frames.asm"
LettyFrames:     INCLUDE "gfx/pokemon/staryu/frames.asm"
DLettyFrames:    INCLUDE "gfx/pokemon/starmie/frames.asm"
ChenFrames:    INCLUDE "gfx/pokemon/scyther/frames.asm"
HChenFrames:       INCLUDE "gfx/pokemon/jynx/frames.asm"
CLilyWhiteFrames: INCLUDE "gfx/pokemon/electabuzz/frames.asm"
LilyWhiteFrames:     INCLUDE "gfx/pokemon/magmar/frames.asm"
ELilyWhiteFrames:     INCLUDE "gfx/pokemon/pinsir/frames.asm"
CLyricaFrames:     INCLUDE "gfx/pokemon/lapras/frames.asm"
LyricaFrames:      INCLUDE "gfx/pokemon/ditto/frames.asm"
TLyricaFrames:      INCLUDE "gfx/pokemon/eevee/frames.asm"
CMerlinFrames:   INCLUDE "gfx/pokemon/vaporeon/frames.asm"
MerlinFrames:    INCLUDE "gfx/pokemon/jolteon/frames.asm"
SMerlinFrames:    INCLUDE "gfx/pokemon/flareon/frames.asm"
CLunasaFrames:    INCLUDE "gfx/pokemon/porygon/frames.asm"
LunasaFrames:    INCLUDE "gfx/pokemon/omanyte/frames.asm"
ALunasaFrames:    INCLUDE "gfx/pokemon/omastar/frames.asm"
CYuyukoFrames:     INCLUDE "gfx/pokemon/kabuto/frames.asm"
YuyukoFrames:   INCLUDE "gfx/pokemon/kabutops/frames.asm"
AYuyukoFrames: INCLUDE "gfx/pokemon/aerodactyl/frames.asm"
CRanFrames:    INCLUDE "gfx/pokemon/snorlax/frames.asm"
YukariFrames:    INCLUDE "gfx/pokemon/dratini/frames.asm"
TYukariFrames:  INCLUDE "gfx/pokemon/dragonair/frames.asm"
CSuikaFrames:  INCLUDE "gfx/pokemon/dragonite/frames.asm"
TSuikaFrames:        INCLUDE "gfx/pokemon/mew/frames.asm"

KikuriJohtoFrames:  INCLUDE "gfx/pokemon/kikuri_johto/frames.asm"
KikuriKantoFrames:  INCLUDE "gfx/pokemon/kikuri_kanto/frames.asm"
KikuriKogaFrames:   INCLUDE "gfx/pokemon/kikuri_koga/frames.asm"
KikuriAgathaFrames: INCLUDE "gfx/pokemon/kikuri_agatha/frames.asm"
KikuriArianaFrames: INCLUDE "gfx/pokemon/kikuri_ariana/frames.asm"

LilyBlackFrames:     INCLUDE "gfx/pokemon/magikarp/frames.asm"
LilyBlackSkellyFrames:    INCLUDE "gfx/pokemon/magikarp_skelly/frames.asm"
LilyBlackCalico1Frames:   INCLUDE "gfx/pokemon/magikarp_calico1/frames.asm"
LilyBlackCalico2Frames:   INCLUDE "gfx/pokemon/magikarp_calico2/frames.asm"
LilyBlackCalico3Frames:   INCLUDE "gfx/pokemon/magikarp_calico3/frames.asm"
LilyBlackTwoToneFrames:   INCLUDE "gfx/pokemon/magikarp_twotone/frames.asm"
LilyBlackOrcaFrames:      INCLUDE "gfx/pokemon/magikarp_orca/frames.asm"
LilyBlackDapplesFrames:   INCLUDE "gfx/pokemon/magikarp_dapples/frames.asm"
LilyBlackTigerFrames:     INCLUDE "gfx/pokemon/magikarp_tiger/frames.asm"
LilyBlackZebraFrames:     INCLUDE "gfx/pokemon/magikarp_zebra/frames.asm"
LilyBlackStripeFrames:    INCLUDE "gfx/pokemon/magikarp_stripe/frames.asm"
LilyBlackBubblesFrames:   INCLUDE "gfx/pokemon/magikarp_bubbles/frames.asm"
LilyBlackDiamondsFrames:  INCLUDE "gfx/pokemon/magikarp_diamonds/frames.asm"
LilyBlackPatchesFrames:   INCLUDE "gfx/pokemon/magikarp_patches/frames.asm"
LilyBlackForehead1Frames: INCLUDE "gfx/pokemon/magikarp_forehead1/frames.asm"
LilyBlackMask1Frames:     INCLUDE "gfx/pokemon/magikarp_mask1/frames.asm"
LilyBlackForehead2Frames: INCLUDE "gfx/pokemon/magikarp_forehead2/frames.asm"
LilyBlackMask2Frames:     INCLUDE "gfx/pokemon/magikarp_mask2/frames.asm"
LilyBlackSaucyFrames:     INCLUDE "gfx/pokemon/magikarp_saucy/frames.asm"
LilyBlackRaindropFrames:  INCLUDE "gfx/pokemon/magikarp_raindrop/frames.asm"

ELilyBlackFrames: INCLUDE "gfx/pokemon/gyarados/frames.asm"
ELilyBlackRedFrames:   INCLUDE "gfx/pokemon/gyarados_red/frames.asm"

SuikaFrames:   INCLUDE "gfx/pokemon/mewtwo/frames.asm"
SuikaArmoredFrames: INCLUDE "gfx/pokemon/mewtwo_armored/frames.asm"

CElisFrames:  INCLUDE "gfx/pokemon/celis/frames.asm"

CSarielFrames:  INCLUDE "gfx/pokemon/csariel/frames.asm"

SarielFrames:  INCLUDE "gfx/pokemon/sariel/frames.asm"

CEllenFrames:  INCLUDE "gfx/pokemon/cellen/frames.asm"

CChiyuriFrames:  INCLUDE "gfx/pokemon/cchiyuri/frames.asm"

ChiyuriFrames:  INCLUDE "gfx/pokemon/chiyuri/frames.asm"

CYumemiFrames:  INCLUDE "gfx/pokemon/cyumemi/frames.asm"

CSaraFrames:  INCLUDE "gfx/pokemon/csara/frames.asm"

SaraFrames:  INCLUDE "gfx/pokemon/sara/frames.asm"

CYumekoFrames:  INCLUDE "gfx/pokemon/cyumeko/frames.asm"

SCirnoFrames:  INCLUDE "gfx/pokemon/scirno/frames.asm"

MeilingFrames:  INCLUDE "gfx/pokemon/meiling/frames.asm"

CLuizeFrames:    INCLUDE "gfx/pokemon/cluize/frames.asm"

LuizeFrames:    INCLUDE "gfx/pokemon/luize/frames.asm"

DLuizeFrames:   INCLUDE "gfx/pokemon/dluize/frames.asm"

CAliceFrames:    INCLUDE "gfx/pokemon/calice/frames.asm"

CMaiFrames:    INCLUDE "gfx/pokemon/cmai/frames.asm"

CPatchouliFrames:    INCLUDE "gfx/pokemon/cpatchouli/frames.asm"

MrMimeFrames:    INCLUDE "gfx/pokemon/mr__mime/frames.asm"

RanFrames:    INCLUDE "gfx/pokemon/articuno/frames.asm"

TRanFrames:    INCLUDE "gfx/pokemon/zapdos/frames.asm"

CYukariFrames:    INCLUDE "gfx/pokemon/moltres/frames.asm"

CKurumiFrames:   INCLUDE "gfx/pokemon/ckurumi/frames.asm"

DDaichanFrames:   INCLUDE "gfx/pokemon/ddaichan/frames.asm"

CCirnoFrames:   INCLUDE "gfx/pokemon/ccirno/frames.asm"

CLilyBlackFrames:        INCLUDE "gfx/pokemon/tauros/frames.asm"