KantoFrames:

CReimuFrames:  INCLUDE "gfx/pokemon/creimu/frames.asm"
ReimuFrames:    INCLUDE "gfx/pokemon/reimu/frames.asm"
EReimuFrames:   INCLUDE "gfx/pokemon/ereimu/frames.asm"
CMarisaFrames: INCLUDE "gfx/pokemon/cmarisa/frames.asm"
MarisaFrames: INCLUDE "gfx/pokemon/marisa/frames.asm"
EMarisaFrames:  INCLUDE "gfx/pokemon/emarisa/frames.asm"
CSakuyaFrames:   INCLUDE "gfx/pokemon/csakuya/frames.asm"
SakuyaFrames:  INCLUDE "gfx/pokemon/sakuya/frames.asm"
ESakuyaFrames:  INCLUDE "gfx/pokemon/esakuya/frames.asm"
CGyokuFrames:   INCLUDE "gfx/pokemon/cgyoku/frames.asm"
MGyokuFrames:    INCLUDE "gfx/pokemon/mgyoku/frames.asm"
FGyokuFrames: INCLUDE "gfx/pokemon/fgyoku/frames.asm"
OGyokuFrames:     INCLUDE "gfx/pokemon/ogyoku/frames.asm"
CMaganFrames:     INCLUDE "gfx/pokemon/cmagan/frames.asm"
MaganFrames:   INCLUDE "gfx/pokemon/magan/frames.asm"
EMaganFrames:     INCLUDE "gfx/pokemon/emagan/frames.asm"
CMimaFrames:  INCLUDE "gfx/pokemon/cmima/frames.asm"
MimaFrames:    INCLUDE "gfx/pokemon/mima/frames.asm"
ElisFrames:    INCLUDE "gfx/pokemon/elis/frames.asm"
EElisFrames:     INCLUDE "gfx/pokemon/eelis/frames.asm"
CKikuriFrames:      INCLUDE "gfx/pokemon/ckikuri/frames.asm"
CKongaraFrames:   INCLUDE "gfx/pokemon/ckongara/frames.asm"
KongaraFrames:   INCLUDE "gfx/pokemon/kongara/frames.asm"
EKongaraFrames:  INCLUDE "gfx/pokemon/ekongara/frames.asm"
CRikaFrames:   INCLUDE "gfx/pokemon/crika/frames.asm"
RikaFrames:   INCLUDE "gfx/pokemon/rika/frames.asm"
ERikaFrames:   INCLUDE "gfx/pokemon/erika/frames.asm"
CMeiraFrames:   INCLUDE "gfx/pokemon/cmeira/frames.asm"
MeiraFrames:   INCLUDE "gfx/pokemon/meira/frames.asm"
EllenFrames: INCLUDE "gfx/pokemon/ellen/frames.asm"
EEllenFrames: INCLUDE "gfx/pokemon/eellen/frames.asm"
CKotohimeFrames:      INCLUDE "gfx/pokemon/ckotohime/frames.asm"
KotohimeFrames:     INCLUDE "gfx/pokemon/kotohime/frames.asm"
EKotohimeFrames:     INCLUDE "gfx/pokemon/ekotohime/frames.asm"
CKanaFrames:      INCLUDE "gfx/pokemon/ckana/frames.asm"
KanaFrames:  INCLUDE "gfx/pokemon/kana/frames.asm"
EKanaFrames:      INCLUDE "gfx/pokemon/ekana/frames.asm"
CRikakoFrames:   INCLUDE "gfx/pokemon/crikako/frames.asm"
RikakoFrames:    INCLUDE "gfx/pokemon/rikako/frames.asm"
ERikakoFrames:   INCLUDE "gfx/pokemon/erikako/frames.asm"
YumemiFrames:    INCLUDE "gfx/pokemon/yumemi/frames.asm"
EYumemiFrames:    INCLUDE "gfx/pokemon/eyumemi/frames.asm"
COrangeFrames:     INCLUDE "gfx/pokemon/corange/frames.asm"
OrangeFrames:   INCLUDE "gfx/pokemon/orange/frames.asm"
KurumiFrames:    INCLUDE "gfx/pokemon/kurumi/frames.asm"
EKurumiFrames:  INCLUDE "gfx/pokemon/ekurumi/frames.asm"
CEllyFrames:  INCLUDE "gfx/pokemon/celly/frames.asm"
EllyFrames:       INCLUDE "gfx/pokemon/elly/frames.asm"
EEllyFrames:    INCLUDE "gfx/pokemon/eelly/frames.asm"
CYukaFrames:   INCLUDE "gfx/pokemon/cyuka/frames.asm"
YukaFrames:     INCLUDE "gfx/pokemon/yuka/frames.asm"
EYukaFrames:    INCLUDE "gfx/pokemon/eyuka/frames.asm"
CMugetsuFrames:    INCLUDE "gfx/pokemon/cmugetsu/frames.asm"
MugetsuFrames: INCLUDE "gfx/pokemon/mugetsu/frames.asm"
EMugetsuFrames: INCLUDE "gfx/pokemon/emugetsu/frames.asm"
CGengetsuFrames: INCLUDE "gfx/pokemon/cgengetsu/frames.asm"
GengetsuFrames:  INCLUDE "gfx/pokemon/gengetsu/frames.asm"
EGengetsuFrames: INCLUDE "gfx/pokemon/egengetsu/frames.asm"
AliceFrames:  INCLUDE "gfx/pokemon/alice/frames.asm"
EAliceFrames:   INCLUDE "gfx/pokemon/ealice/frames.asm"
MaiFrames:      INCLUDE "gfx/pokemon/mai/frames.asm"
EMaiFrames:     INCLUDE "gfx/pokemon/emai/frames.asm"
CYukiFrames:       INCLUDE "gfx/pokemon/cyuki/frames.asm"
YukiFrames:    INCLUDE "gfx/pokemon/yuki/frames.asm"
YumekoFrames:   INCLUDE "gfx/pokemon/yumeko/frames.asm"
EYumekoFrames:   INCLUDE "gfx/pokemon/eyumeko/frames.asm"
CShinkiFrames:     INCLUDE "gfx/pokemon/cshinki/frames.asm"
ShinkiFrames:    INCLUDE "gfx/pokemon/shinki/frames.asm"
EShinkiFrames:     INCLUDE "gfx/pokemon/eshinki/frames.asm"
CRumiaFrames:       INCLUDE "gfx/pokemon/crumia/frames.asm"
RumiaFrames:    INCLUDE "gfx/pokemon/rumia/frames.asm"
ERumiaFrames:      INCLUDE "gfx/pokemon/erumia/frames.asm"
CDaichanFrames:     INCLUDE "gfx/pokemon/cdaichan/frames.asm"
DaichanFrames:    INCLUDE "gfx/pokemon/daichan/frames.asm"
CirnoFrames:  INCLUDE "gfx/pokemon/cirno/frames.asm"
CMeilingFrames:     INCLUDE "gfx/pokemon/cmeiling/frames.asm"
EMeilingFrames:  INCLUDE "gfx/pokemon/emeiling/frames.asm"
CKoakumaFrames: INCLUDE "gfx/pokemon/ckoakuma/frames.asm"
KoakumaFrames:  INCLUDE "gfx/pokemon/koakuma/frames.asm"
EKoakumaFrames:    INCLUDE "gfx/pokemon/ekoakuma/frames.asm"
PatchouliFrames:    INCLUDE "gfx/pokemon/patchouli/frames.asm"
EPatchouliFrames:     INCLUDE "gfx/pokemon/epatchouli/frames.asm"
CRemiliaFrames:    INCLUDE "gfx/pokemon/cremilia/frames.asm"
RemiliaFrames:    INCLUDE "gfx/pokemon/remilia/frames.asm"
ERemiliaFrames: INCLUDE "gfx/pokemon/eremilia/frames.asm"
CFlandreFrames:     INCLUDE "gfx/pokemon/cflandre/frames.asm"
FlandreFrames:     INCLUDE "gfx/pokemon/flandre/frames.asm"
EFlandreFrames:    INCLUDE "gfx/pokemon/eflandre/frames.asm"
CLettyFrames:    INCLUDE "gfx/pokemon/seaking/frames.asm"
LettyFrames:     INCLUDE "gfx/pokemon/staryu/frames.asm"
ELettyFrames:    INCLUDE "gfx/pokemon/starmie/frames.asm"
ChenFrames:    INCLUDE "gfx/pokemon/scyther/frames.asm"
EChenFrames:       INCLUDE "gfx/pokemon/jynx/frames.asm"
CLilyWhiteFrames: INCLUDE "gfx/pokemon/electabuzz/frames.asm"
LilyWhiteFrames:     INCLUDE "gfx/pokemon/magmar/frames.asm"
ELilyWhiteFrames:     INCLUDE "gfx/pokemon/pinsir/frames.asm"
CLyricaFrames:     INCLUDE "gfx/pokemon/lapras/frames.asm"
LyricaFrames:      INCLUDE "gfx/pokemon/ditto/frames.asm"
ELyricaFrames:      INCLUDE "gfx/pokemon/eevee/frames.asm"
CMerlinFrames:   INCLUDE "gfx/pokemon/vaporeon/frames.asm"
MerlinFrames:    INCLUDE "gfx/pokemon/jolteon/frames.asm"
EMerlinFrames:    INCLUDE "gfx/pokemon/flareon/frames.asm"
CLunasaFrames:    INCLUDE "gfx/pokemon/porygon/frames.asm"
LunasaFrames:    INCLUDE "gfx/pokemon/omanyte/frames.asm"
ELunasaFrames:    INCLUDE "gfx/pokemon/omastar/frames.asm"
CYuyukoFrames:     INCLUDE "gfx/pokemon/kabuto/frames.asm"
YuyukoFrames:   INCLUDE "gfx/pokemon/kabutops/frames.asm"
EYuyukoFrames: INCLUDE "gfx/pokemon/aerodactyl/frames.asm"
CRanFrames:    INCLUDE "gfx/pokemon/snorlax/frames.asm"
YukariFrames:    INCLUDE "gfx/pokemon/dratini/frames.asm"
EYukariFrames:  INCLUDE "gfx/pokemon/dragonair/frames.asm"
CSuikaFrames:  INCLUDE "gfx/pokemon/dragonite/frames.asm"
ESuikaFrames:        INCLUDE "gfx/pokemon/mew/frames.asm"

EKikuriPlainFrames:  INCLUDE "gfx/pokemon/ekikuri_plain/frames.asm"
EKikuriFlyFrames:    INCLUDE "gfx/pokemon/ekikuri_fly/frames.asm"
EKikuriSurfFrames:   INCLUDE "gfx/pokemon/ekikuri_surf/frames.asm"
EKikuriPikaFrames:   INCLUDE "gfx/pokemon/ekikuri_pika/frames.asm"
EKikuriChuchuFrames: INCLUDE "gfx/pokemon/ekikuri_chuchu/frames.asm"
EKikuriSparkFrames:  INCLUDE "gfx/pokemon/ekikuri_spark/frames.asm"

KikuriJohtoFrames:  INCLUDE "gfx/pokemon/kikuri_johto/frames.asm"
KikuriKantoFrames:  INCLUDE "gfx/pokemon/kikuri_kanto/frames.asm"
KikuriKogaFrames:   INCLUDE "gfx/pokemon/kikuri_koga/frames.asm"
KikuriAgathaFrames: INCLUDE "gfx/pokemon/kikuri_agatha/frames.asm"
KikuriArianaFrames: INCLUDE "gfx/pokemon/kikuri_ariana/frames.asm"

LilyBlackPlainFrames:     INCLUDE "gfx/pokemon/magikarp_plain/frames.asm"
LilyBlackSkellyFrames:    INCLUDE "gfx/pokemon/magikarp_skelly/frames.asm"
LilyBlackCalico1Frames:   INCLUDE "gfx/pokemon/magikarp_calico1/frames.asm"
LilyBlackCalico2Frames:   INCLUDE "gfx/pokemon/magikarp_calico2/frames.asm"
LilyBlackCalico3Frames:   INCLUDE "gfx/pokemon/magikarp_calico3/frames.asm"
LilyBlackTwoToneFrames:   INCLUDE "gfx/pokemon/magikarp_twotone/frames.asm"
LilyBlackOrcaFrames:      INCLUDE "gfx/pokemon/magikarp_orca/frames.asm"
LilyBlackDapplesFrames:   INCLUDE "gfx/pokemon/magikarp_dapples/frames.asm"
LilyBlackTigerFrames:     INCLUDE "gfx/pokemon/magikarp_tiger/frames.asm"
LilyBlackZebraFrames:     INCLUDE "gfx/pokemon/magikarp_zebra/frames.asm"
LilyBlackStripeFrames:    INCLUDE "gfx/pokemon/magikarp_stripe/frames.asm"
LilyBlackBubblesFrames:   INCLUDE "gfx/pokemon/magikarp_bubbles/frames.asm"
LilyBlackDiamondsFrames:  INCLUDE "gfx/pokemon/magikarp_diamonds/frames.asm"
LilyBlackPatchesFrames:   INCLUDE "gfx/pokemon/magikarp_patches/frames.asm"
LilyBlackForehead1Frames: INCLUDE "gfx/pokemon/magikarp_forehead1/frames.asm"
LilyBlackMask1Frames:     INCLUDE "gfx/pokemon/magikarp_mask1/frames.asm"
LilyBlackForehead2Frames: INCLUDE "gfx/pokemon/magikarp_forehead2/frames.asm"
LilyBlackMask2Frames:     INCLUDE "gfx/pokemon/magikarp_mask2/frames.asm"
LilyBlackSaucyFrames:     INCLUDE "gfx/pokemon/magikarp_saucy/frames.asm"
LilyBlackRaindropFrames:  INCLUDE "gfx/pokemon/magikarp_raindrop/frames.asm"

ELilyBlackPlainFrames: INCLUDE "gfx/pokemon/gyarados_plain/frames.asm"
ELilyBlackRedFrames:   INCLUDE "gfx/pokemon/gyarados_red/frames.asm"

SuikaPlainFrames:   INCLUDE "gfx/pokemon/mewtwo_plain/frames.asm"
SuikaArmoredFrames: INCLUDE "gfx/pokemon/mewtwo_armored/frames.asm"

EMimaFrames:  INCLUDE "gfx/pokemon/emima_plain/frames.asm"
EMimaAlolanFrames: INCLUDE "gfx/pokemon/emima_alolan/frames.asm"

CElisPlainFrames:  INCLUDE "gfx/pokemon/celis_plain/frames.asm"
CElisAlolanFrames: INCLUDE "gfx/pokemon/celis_alolan/frames.asm"

CSarielPlainFrames:  INCLUDE "gfx/pokemon/csariel_plain/frames.asm"
CSarielAlolanFrames: INCLUDE "gfx/pokemon/csariel_alolan/frames.asm"

SarielPlainFrames:  INCLUDE "gfx/pokemon/sariel_plain/frames.asm"
SarielAlolanFrames: INCLUDE "gfx/pokemon/sariel_alolan/frames.asm"

ESarielPlainFrames:  INCLUDE "gfx/pokemon/esariel_plain/frames.asm"
ESarielAlolanFrames: INCLUDE "gfx/pokemon/esariel_alolan/frames.asm"

EMeiraPlainFrames:  INCLUDE "gfx/pokemon/emeira_plain/frames.asm"
EMeiraAlolanFrames: INCLUDE "gfx/pokemon/emeira_alolan/frames.asm"

CEllenPlainFrames:  INCLUDE "gfx/pokemon/cellen_plain/frames.asm"
CEllenAlolanFrames: INCLUDE "gfx/pokemon/cellen_alolan/frames.asm"

CChiyuriPlainFrames:  INCLUDE "gfx/pokemon/cchiyuri_plain/frames.asm"
CChiyuriAlolanFrames: INCLUDE "gfx/pokemon/cchiyuri_alolan/frames.asm"

ChiyuriPlainFrames:  INCLUDE "gfx/pokemon/chiyuri_plain/frames.asm"
ChiyuriAlolanFrames: INCLUDE "gfx/pokemon/chiyuri_alolan/frames.asm"

EChiyuriPlainFrames:    INCLUDE "gfx/pokemon/echiyuri_plain/frames.asm"
EChiyuriAlolanFrames:   INCLUDE "gfx/pokemon/echiyuri_alolan/frames.asm"
EChiyuriGalarianFrames: INCLUDE "gfx/pokemon/echiyuri_galarian/frames.asm"

CYumemiPlainFrames:  INCLUDE "gfx/pokemon/cyumemi_plain/frames.asm"
CYumemiAlolanFrames: INCLUDE "gfx/pokemon/cyumemi_alolan/frames.asm"

CSaraPlainFrames:  INCLUDE "gfx/pokemon/csara_plain/frames.asm"
CSaraAlolanFrames: INCLUDE "gfx/pokemon/csara_alolan/frames.asm"

SaraPlainFrames:  INCLUDE "gfx/pokemon/sara_plain/frames.asm"
SaraAlolanFrames: INCLUDE "gfx/pokemon/sara_alolan/frames.asm"

ESaraPlainFrames:  INCLUDE "gfx/pokemon/esara_plain/frames.asm"
ESaraAlolanFrames: INCLUDE "gfx/pokemon/esara_alolan/frames.asm"

EYukiPlainFrames:  INCLUDE "gfx/pokemon/eyuki_plain/frames.asm"
EYukiAlolanFrames: INCLUDE "gfx/pokemon/eyuki_alolan/frames.asm"

CYumekoPlainFrames:  INCLUDE "gfx/pokemon/cyumeko_plain/frames.asm"
CYumekoAlolanFrames: INCLUDE "gfx/pokemon/cyumeko_alolan/frames.asm"

ECirnoPlainFrames:  INCLUDE "gfx/pokemon/ecirno_plain/frames.asm"
ECirnoAlolanFrames: INCLUDE "gfx/pokemon/ecirno_alolan/frames.asm"

MeilingPlainFrames:  INCLUDE "gfx/pokemon/meiling_plain/frames.asm"
MeilingAlolanFrames: INCLUDE "gfx/pokemon/meiling_alolan/frames.asm"

CLuizePlainFrames:    INCLUDE "gfx/pokemon/cluize_plain/frames.asm"
CLuizeGalarianFrames: INCLUDE "gfx/pokemon/cluize_galarian/frames.asm"

LuizePlainFrames:    INCLUDE "gfx/pokemon/luize_plain/frames.asm"
LuizeGalarianFrames: INCLUDE "gfx/pokemon/luize_galarian/frames.asm"

ELuizePlainFrames:   INCLUDE "gfx/pokemon/eluize_plain/frames.asm"
ELuizeGalarianFrames: INCLUDE "gfx/pokemon/eluize_galarian/frames.asm"

CAlicePlainFrames:    INCLUDE "gfx/pokemon/calice_plain/frames.asm"
CAliceGalarianFrames: INCLUDE "gfx/pokemon/calice_galarian/frames.asm"

CMaiPlainFrames:    INCLUDE "gfx/pokemon/cmai_plain/frames.asm"
CMaiGalarianFrames: INCLUDE "gfx/pokemon/cmai_galarian/frames.asm"

CPatchouliPlainFrames:    INCLUDE "gfx/pokemon/cpatchouli_plain/frames.asm"
CPatchouliGalarianFrames: INCLUDE "gfx/pokemon/cpatchouli_galarian/frames.asm"

MrMimePlainFrames:    INCLUDE "gfx/pokemon/mr__mime_plain/frames.asm"
MrMimeGalarianFrames: INCLUDE "gfx/pokemon/mr__mime_galarian/frames.asm"

RanPlainFrames:    INCLUDE "gfx/pokemon/articuno_plain/frames.asm"
RanGalarianFrames: INCLUDE "gfx/pokemon/articuno_galarian/frames.asm"

ERanPlainFrames:    INCLUDE "gfx/pokemon/zapdos_plain/frames.asm"
ERanGalarianFrames: INCLUDE "gfx/pokemon/zapdos_galarian/frames.asm"

CYukariPlainFrames:    INCLUDE "gfx/pokemon/moltres_plain/frames.asm"
CYukariGalarianFrames: INCLUDE "gfx/pokemon/moltres_galarian/frames.asm"

EOrangePlainFrames:   INCLUDE "gfx/pokemon/eorange_plain/frames.asm"
EOrangeHisuianFrames: INCLUDE "gfx/pokemon/eorange_hisuian/frames.asm"

CKurumiPlainFrames:   INCLUDE "gfx/pokemon/ckurumi_plain/frames.asm"
CKurumiHisuianFrames: INCLUDE "gfx/pokemon/ckurumi_hisuian/frames.asm"

EDaichanPlainFrames:   INCLUDE "gfx/pokemon/edaichan_plain/frames.asm"
EDaichanHisuianFrames: INCLUDE "gfx/pokemon/edaichan_hisuian/frames.asm"

CCirnoPlainFrames:   INCLUDE "gfx/pokemon/ccirno_plain/frames.asm"
CCirnoHisuianFrames: INCLUDE "gfx/pokemon/ccirno_hisuian/frames.asm"

CLilyBlackPlainFrames:        INCLUDE "gfx/pokemon/tauros_plain/frames.asm"
CLilyBlackPaldeanFrames:      INCLUDE "gfx/pokemon/tauros_paldean/frames.asm"
CLilyBlackPaldeanFireFrames:  INCLUDE "gfx/pokemon/tauros_paldean_fire/frames.asm"
CLilyBlackPaldeanWaterFrames: INCLUDE "gfx/pokemon/tauros_paldean_water/frames.asm"
